version: '3.8'

networks:
  k6:
  grafana:

services:

  influxdb:
    image: influxdb:1.8
    networks:
      - k6
      - grafana
    ports:
      - '8086:8086'
    environment:
      - INFLUXDB_DB=k6
    logging:
      driver: none

  grafana:
    image: grafana/grafana:latest
    networks:
      - grafana
    ports:
      - '3000:3000'
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./Dashboards:/var/lib/grafana/dashboards
      - ./grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    logging:
      driver: none

  load_tests:
    image: loadimpact/k6
    container_name: k6_load_tests
    networks:
      - k6
    ports:
      - "6565:6565"
    environment: 
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./LoadTests:/PerformanceTests/LoadTests
    command: run -e BASE_ADDRESS=${BASE_ADDRESS} /PerformanceTests/LoadTests/load-tests.js
  
            
    
    
