// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace _4_Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200329170134_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.Collaborator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Collaborators");

                    b.HasData(
                        new
                        {
                            Id = 678,
                            FullName = "Jana Lesch",
                            ProjectId = 1,
                            Role = "Future Intranet Associate"
                        },
                        new
                        {
                            Id = 185,
                            FullName = "Marcia Terry",
                            ProjectId = 1,
                            Role = "International Markets Agent"
                        },
                        new
                        {
                            Id = 2754,
                            FullName = "Helen Simonis",
                            ProjectId = 2,
                            Role = "Lead Tactics Architect"
                        },
                        new
                        {
                            Id = 1950,
                            FullName = "Sandra Muller",
                            ProjectId = 2,
                            Role = "District Usability Planner"
                        },
                        new
                        {
                            Id = 7567,
                            FullName = "Bertrand Bernhard",
                            ProjectId = 3,
                            Role = "District Mobility Coordinator"
                        },
                        new
                        {
                            Id = 3386,
                            FullName = "Melyna Marks",
                            ProjectId = 3,
                            Role = "International Response Coordinator"
                        },
                        new
                        {
                            Id = 8461,
                            FullName = "Damien Schinner",
                            ProjectId = 4,
                            Role = "Chief Tactics Designer"
                        },
                        new
                        {
                            Id = 9948,
                            FullName = "Coby Wilderman",
                            ProjectId = 4,
                            Role = "District Factors Manager"
                        },
                        new
                        {
                            Id = 7301,
                            FullName = "Geovanni Sipes",
                            ProjectId = 5,
                            Role = "Dynamic Integration Consultant"
                        },
                        new
                        {
                            Id = 9127,
                            FullName = "Lexus Kutch",
                            ProjectId = 5,
                            Role = "Chief Optimization Architect"
                        },
                        new
                        {
                            Id = 9835,
                            FullName = "Kory Ward",
                            ProjectId = 6,
                            Role = "Central Identity Technician"
                        },
                        new
                        {
                            Id = 3251,
                            FullName = "Keaton Considine",
                            ProjectId = 6,
                            Role = "Central Implementation Executive"
                        },
                        new
                        {
                            Id = 6689,
                            FullName = "Eddie Lindgren",
                            ProjectId = 7,
                            Role = "Senior Division Consultant"
                        },
                        new
                        {
                            Id = 6337,
                            FullName = "Everett Dickinson",
                            ProjectId = 7,
                            Role = "Internal Assurance Director"
                        },
                        new
                        {
                            Id = 5598,
                            FullName = "Blaise Kulas",
                            ProjectId = 8,
                            Role = "Legacy Data Technician"
                        },
                        new
                        {
                            Id = 8630,
                            FullName = "Sophie Renner",
                            ProjectId = 8,
                            Role = "National Factors Producer"
                        },
                        new
                        {
                            Id = 6098,
                            FullName = "Johnpaul Simonis",
                            ProjectId = 9,
                            Role = "Product Security Coordinator"
                        },
                        new
                        {
                            Id = 621,
                            FullName = "Diana Dickens",
                            ProjectId = 9,
                            Role = "International Infrastructure Representative"
                        },
                        new
                        {
                            Id = 2592,
                            FullName = "Rhea Crooks",
                            ProjectId = 10,
                            Role = "Legacy Paradigm Liaison"
                        },
                        new
                        {
                            Id = 2677,
                            FullName = "Bonnie Swaniawski",
                            ProjectId = 10,
                            Role = "Customer Factors Engineer"
                        },
                        new
                        {
                            Id = 1821,
                            FullName = "Kayden Romaguera",
                            ProjectId = 11,
                            Role = "Central Communications Specialist"
                        },
                        new
                        {
                            Id = 3890,
                            FullName = "Estella Herzog",
                            ProjectId = 11,
                            Role = "Forward Applications Representative"
                        },
                        new
                        {
                            Id = 9385,
                            FullName = "Fiona Gaylord",
                            ProjectId = 12,
                            Role = "Internal Data Architect"
                        },
                        new
                        {
                            Id = 1678,
                            FullName = "Rose Marks",
                            ProjectId = 12,
                            Role = "Customer Optimization Strategist"
                        },
                        new
                        {
                            Id = 4959,
                            FullName = "Brennon McClure",
                            ProjectId = 13,
                            Role = "Customer Brand Assistant"
                        },
                        new
                        {
                            Id = 8750,
                            FullName = "Alicia McKenzie",
                            ProjectId = 13,
                            Role = "Customer Security Designer"
                        },
                        new
                        {
                            Id = 6074,
                            FullName = "Kieran Olson",
                            ProjectId = 14,
                            Role = "Human Tactics Manager"
                        },
                        new
                        {
                            Id = 5757,
                            FullName = "Jamel Herman",
                            ProjectId = 14,
                            Role = "Dynamic Data Strategist"
                        },
                        new
                        {
                            Id = 8942,
                            FullName = "Hudson Hand",
                            ProjectId = 15,
                            Role = "District Markets Associate"
                        },
                        new
                        {
                            Id = 6804,
                            FullName = "Linnea Baumbach",
                            ProjectId = 15,
                            Role = "Forward Metrics Architect"
                        },
                        new
                        {
                            Id = 7142,
                            FullName = "Rafael Gleason",
                            ProjectId = 16,
                            Role = "Customer Interactions Administrator"
                        },
                        new
                        {
                            Id = 3556,
                            FullName = "Flo Gerlach",
                            ProjectId = 16,
                            Role = "International Integration Manager"
                        },
                        new
                        {
                            Id = 7848,
                            FullName = "Dora Lebsack",
                            ProjectId = 17,
                            Role = "National Metrics Associate"
                        },
                        new
                        {
                            Id = 6246,
                            FullName = "Duane Heaney",
                            ProjectId = 17,
                            Role = "Investor Quality Orchestrator"
                        },
                        new
                        {
                            Id = 4816,
                            FullName = "Isaiah Nicolas",
                            ProjectId = 18,
                            Role = "Global Interactions Architect"
                        },
                        new
                        {
                            Id = 4907,
                            FullName = "Richie McCullough",
                            ProjectId = 18,
                            Role = "Dynamic Directives Analyst"
                        },
                        new
                        {
                            Id = 9501,
                            FullName = "Alana Lockman",
                            ProjectId = 19,
                            Role = "Chief Configuration Administrator"
                        },
                        new
                        {
                            Id = 7016,
                            FullName = "Chad Effertz",
                            ProjectId = 19,
                            Role = "Direct Web Liaison"
                        },
                        new
                        {
                            Id = 5548,
                            FullName = "Erling Nolan",
                            ProjectId = 20,
                            Role = "Principal Marketing Developer"
                        },
                        new
                        {
                            Id = 1298,
                            FullName = "Augustine Cartwright",
                            ProjectId = 20,
                            Role = "Investor Brand Architect"
                        },
                        new
                        {
                            Id = 8031,
                            FullName = "Rosalind Klocko",
                            ProjectId = 21,
                            Role = "Forward Integration Coordinator"
                        },
                        new
                        {
                            Id = 6428,
                            FullName = "Laurie Bosco",
                            ProjectId = 21,
                            Role = "Lead Markets Representative"
                        },
                        new
                        {
                            Id = 4996,
                            FullName = "Melyna Johns",
                            ProjectId = 22,
                            Role = "Human Factors Analyst"
                        },
                        new
                        {
                            Id = 4178,
                            FullName = "Geraldine Schoen",
                            ProjectId = 22,
                            Role = "Global Usability Planner"
                        },
                        new
                        {
                            Id = 8288,
                            FullName = "Jeremie Pagac",
                            ProjectId = 23,
                            Role = "Human Brand Executive"
                        },
                        new
                        {
                            Id = 3963,
                            FullName = "Emely Wiegand",
                            ProjectId = 23,
                            Role = "Senior Research Supervisor"
                        },
                        new
                        {
                            Id = 9784,
                            FullName = "Tavares Weissnat",
                            ProjectId = 24,
                            Role = "Internal Division Associate"
                        },
                        new
                        {
                            Id = 385,
                            FullName = "Katherine Walsh",
                            ProjectId = 24,
                            Role = "International Optimization Architect"
                        },
                        new
                        {
                            Id = 2985,
                            FullName = "Damion Daniel",
                            ProjectId = 25,
                            Role = "Investor Integration Developer"
                        },
                        new
                        {
                            Id = 6648,
                            FullName = "Elinore Torphy",
                            ProjectId = 25,
                            Role = "Human Usability Producer"
                        },
                        new
                        {
                            Id = 7166,
                            FullName = "Onie Leuschke",
                            ProjectId = 26,
                            Role = "Lead Communications Executive"
                        },
                        new
                        {
                            Id = 100,
                            FullName = "Henriette Metz",
                            ProjectId = 26,
                            Role = "Regional Factors Supervisor"
                        },
                        new
                        {
                            Id = 5713,
                            FullName = "Lavina Ward",
                            ProjectId = 27,
                            Role = "Legacy Applications Administrator"
                        },
                        new
                        {
                            Id = 6474,
                            FullName = "Burnice Zieme",
                            ProjectId = 27,
                            Role = "Future Intranet Assistant"
                        },
                        new
                        {
                            Id = 9131,
                            FullName = "Patricia Boyer",
                            ProjectId = 28,
                            Role = "Future Group Assistant"
                        },
                        new
                        {
                            Id = 1311,
                            FullName = "Austen Will",
                            ProjectId = 28,
                            Role = "Dynamic Security Developer"
                        },
                        new
                        {
                            Id = 5101,
                            FullName = "Alexie Weimann",
                            ProjectId = 29,
                            Role = "Internal Branding Associate"
                        },
                        new
                        {
                            Id = 8446,
                            FullName = "Stephanie Grimes",
                            ProjectId = 29,
                            Role = "Corporate Program Orchestrator"
                        },
                        new
                        {
                            Id = 7596,
                            FullName = "Susana Skiles",
                            ProjectId = 30,
                            Role = "Central Integration Assistant"
                        },
                        new
                        {
                            Id = 7406,
                            FullName = "Jaylen Doyle",
                            ProjectId = 30,
                            Role = "International Security Assistant"
                        });
                });

            modelBuilder.Entity("Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Project");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2020, 3, 27, 19, 1, 33, 371, DateTimeKind.Local).AddTicks(2908),
                            Description = @"Asperiores dolor necessitatibus neque dolore incidunt.
Et et dolor rerum autem ipsa.
Nisi voluptas assumenda optio.
Autem inventore eligendi blanditiis ipsa qui ratione est.
Amet molestias provident provident quo deleniti nulla sapiente.
Quis distinctio doloremque at animi ullam quo.
Velit animi adipisci iste vel ipsa et magni illo.
Corporis est pariatur impedit aspernatur.
Id debitis quia dolore velit distinctio error.
Vel dolorem atque aperiam tempore.",
                            Name = "Incredible Fresh Pizza",
                            ShortDescription = "Praesentium reprehenderit dolorum quis ipsa perspiciatis dolores amet autem totam.",
                            Updated = new DateTime(2020, 3, 29, 19, 1, 33, 375, DateTimeKind.Local).AddTicks(5520),
                            Uri = "https://bryce.net",
                            UserId = 14
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2020, 3, 27, 19, 1, 33, 381, DateTimeKind.Local).AddTicks(3458),
                            Description = @"Culpa error corrupti sed quisquam dolor officia nisi.
Eaque eveniet quia doloribus natus culpa blanditiis fugit.
Repudiandae aut natus libero omnis quae unde quas et.
Aut alias ea possimus eos.
Et rem sit qui.
Numquam aperiam rerum nostrum molestias animi aut eum.
Suscipit rerum ut corporis harum dolores explicabo repudiandae aut dignissimos.
Numquam cupiditate aliquam suscipit maxime harum eos.
Qui expedita aut.
Exercitationem sed optio quasi et.",
                            Name = "Rustic Granite Bike",
                            ShortDescription = "Quae ducimus ut sed placeat.",
                            Updated = new DateTime(2020, 3, 29, 19, 1, 33, 381, DateTimeKind.Local).AddTicks(4191),
                            Uri = "https://gudrun.name",
                            UserId = 13
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2020, 3, 27, 19, 1, 33, 387, DateTimeKind.Local).AddTicks(4745),
                            Description = @"Asperiores laudantium quod.
Cupiditate est omnis laborum perspiciatis.
Praesentium aut error magnam tempora cum dolore sit recusandae.
Voluptatum sed sapiente.
Doloremque explicabo omnis quaerat ad quis provident perferendis aperiam maxime.
Est non eaque mollitia aut exercitationem consequatur eum.
Maiores error iste dolores.
Eum non et consectetur earum animi blanditiis et maxime.
Molestiae repudiandae occaecati suscipit.
Nisi dignissimos earum qui officia.",
                            Name = "Ergonomic Wooden Chair",
                            ShortDescription = "Ratione non officia molestiae assumenda rem impedit.",
                            Updated = new DateTime(2020, 3, 29, 19, 1, 33, 387, DateTimeKind.Local).AddTicks(4833),
                            Uri = "https://angel.info",
                            UserId = 25
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2020, 3, 27, 19, 1, 33, 392, DateTimeKind.Local).AddTicks(4304),
                            Description = @"Architecto laborum dolorem explicabo ratione quia ratione repellendus illum dolorem.
Est libero similique.
Perspiciatis fuga minus voluptates adipisci labore alias sit ut.
Consequuntur placeat quo id.
Necessitatibus harum aperiam ducimus amet minus et pariatur cum.
Et commodi reprehenderit nihil eum repellat.
Eos a laudantium voluptas consequatur consequatur nostrum et quasi.
Natus et sit praesentium iusto.
Inventore minima laudantium.
Modi eum aut molestiae est inventore provident omnis.",
                            Name = "Awesome Plastic Shoes",
                            ShortDescription = "Est voluptates odio ipsum voluptas laborum possimus enim sint vitae.",
                            Updated = new DateTime(2020, 3, 29, 19, 1, 33, 392, DateTimeKind.Local).AddTicks(4377),
                            Uri = "https://addison.info",
                            UserId = 25
                        },
                        new
                        {
                            Id = 5,
                            Created = new DateTime(2020, 3, 27, 19, 1, 33, 398, DateTimeKind.Local).AddTicks(6481),
                            Description = @"Distinctio sint asperiores ipsam suscipit qui commodi quaerat culpa possimus.
Ut et placeat quo non omnis praesentium consequatur sed.
Eligendi pariatur soluta est eos velit adipisci asperiores nihil.
Facilis et pariatur qui laborum.
Natus ad voluptas architecto repudiandae maxime at eveniet minus.
Sit et numquam sit distinctio dicta earum quia ut.
Ipsam perspiciatis velit.
Ipsum ut sequi quos non tempore eius ex modi voluptas.
Amet animi quae quo.
Asperiores dolor ipsa quis et voluptas omnis ea id natus.",
                            Name = "Rustic Cotton Car",
                            ShortDescription = "Tempore molestiae perspiciatis qui sit beatae illum et facilis officia.",
                            Updated = new DateTime(2020, 3, 29, 19, 1, 33, 398, DateTimeKind.Local).AddTicks(6574),
                            Uri = "http://natasha.net",
                            UserId = 22
                        },
                        new
                        {
                            Id = 6,
                            Created = new DateTime(2020, 3, 27, 19, 1, 33, 404, DateTimeKind.Local).AddTicks(1100),
                            Description = @"Et voluptatum corrupti saepe suscipit voluptatem.
Provident et voluptates.
Ea corrupti placeat.
Est placeat perspiciatis molestiae soluta ipsam sed aut dolor eos.
Ea et sunt voluptatibus.
Necessitatibus iste voluptas id magni architecto doloremque suscipit.
Totam sint sint dolorem id et.
Quo voluptatum ipsa nemo.
Ab non eos.
Commodi nihil facere qui nam dignissimos dignissimos.",
                            Name = "Generic Frozen Mouse",
                            ShortDescription = "Magnam consectetur nulla neque ratione possimus in.",
                            Updated = new DateTime(2020, 3, 29, 19, 1, 33, 404, DateTimeKind.Local).AddTicks(1188),
                            Uri = "http://mary.com",
                            UserId = 15
                        },
                        new
                        {
                            Id = 7,
                            Created = new DateTime(2020, 3, 27, 19, 1, 33, 408, DateTimeKind.Local).AddTicks(9338),
                            Description = @"Ipsa rerum eaque occaecati sequi ab cum similique voluptas doloremque.
Alias voluptas consequatur ad.
Quod voluptatem voluptatum repellat.
Unde et asperiores est quisquam laudantium officia aut non ipsam.
Repudiandae nihil nam fugit odit qui nostrum reprehenderit.
Nobis aliquid illum ut qui doloribus non dignissimos perferendis.
Consectetur et est accusantium dolores maiores ipsa fugiat et.
Dicta nobis enim quo ducimus sunt laboriosam.
Nesciunt dicta animi qui dicta sequi incidunt velit.
Voluptatem perspiciatis qui magnam ratione et placeat consequuntur qui.",
                            Name = "Intelligent Cotton Chicken",
                            ShortDescription = "In dolorem magni veritatis.",
                            Updated = new DateTime(2020, 3, 29, 19, 1, 33, 408, DateTimeKind.Local).AddTicks(9407),
                            Uri = "https://cordelia.name",
                            UserId = 27
                        },
                        new
                        {
                            Id = 8,
                            Created = new DateTime(2020, 3, 27, 19, 1, 33, 413, DateTimeKind.Local).AddTicks(5655),
                            Description = @"Cupiditate illo est.
Veniam molestiae dolor praesentium quo sed quibusdam.
Voluptatem sit quis cumque suscipit.
Illum natus officia et et earum sed doloremque accusantium nostrum.
Veniam qui incidunt nesciunt minus et corrupti vitae maxime.
Earum sunt nam voluptatibus est id accusamus voluptatibus ipsa.
Nesciunt totam illum.
Voluptatum sint saepe consectetur.
Ut aliquam ut necessitatibus deserunt iste eos error.
Esse occaecati quibusdam dolorum.",
                            Name = "Handmade Frozen Chair",
                            ShortDescription = "Vitae debitis doloribus et facilis quia suscipit.",
                            Updated = new DateTime(2020, 3, 29, 19, 1, 33, 413, DateTimeKind.Local).AddTicks(5743),
                            Uri = "http://sabina.net",
                            UserId = 3
                        },
                        new
                        {
                            Id = 9,
                            Created = new DateTime(2020, 3, 27, 19, 1, 33, 418, DateTimeKind.Local).AddTicks(643),
                            Description = @"Ab soluta numquam est exercitationem quis omnis.
Ipsa nobis architecto molestiae unde eaque minus.
Cupiditate tempora ut debitis id corporis corrupti.
Magnam sit quis corporis quia sint dolorum.
Quod natus sint blanditiis velit voluptates et dolore vel voluptatum.
Corporis pariatur numquam fuga ullam recusandae atque blanditiis eaque.
Itaque nulla maxime consectetur.
Ex minima repellat rem in quia veritatis.
Est doloribus cupiditate ad.
Laborum qui nostrum et quaerat.",
                            Name = "Gorgeous Metal Bacon",
                            ShortDescription = "Sit maxime aperiam reprehenderit architecto consequatur.",
                            Updated = new DateTime(2020, 3, 29, 19, 1, 33, 418, DateTimeKind.Local).AddTicks(716),
                            Uri = "https://amani.org",
                            UserId = 4
                        },
                        new
                        {
                            Id = 10,
                            Created = new DateTime(2020, 3, 27, 19, 1, 33, 422, DateTimeKind.Local).AddTicks(1783),
                            Description = @"Voluptatem in iste eius magnam laboriosam beatae quo et.
Cupiditate harum omnis distinctio quia voluptas enim debitis.
Qui minima aut debitis quia rerum molestiae aut cum.
Deleniti deleniti rerum minima facere aut repellendus inventore.
Ipsa est dolor facere earum sunt molestias.
Ullam impedit animi dolorum enim fugiat non consequuntur corrupti.
Cumque incidunt sit voluptas ut.
Illo omnis quia rerum ex voluptatem.
Suscipit dolor aut quo ratione voluptate non et.
Vel magni et qui beatae ipsa non est a.",
                            Name = "Handmade Soft Fish",
                            ShortDescription = "Voluptatem facere dicta eum.",
                            Updated = new DateTime(2020, 3, 29, 19, 1, 33, 422, DateTimeKind.Local).AddTicks(1856),
                            Uri = "https://jake.name",
                            UserId = 8
                        },
                        new
                        {
                            Id = 11,
                            Created = new DateTime(2020, 3, 27, 19, 1, 33, 427, DateTimeKind.Local).AddTicks(951),
                            Description = @"Accusamus in ad illo voluptatem quo laudantium asperiores repellendus quisquam.
Amet voluptates esse sed optio voluptas quia perferendis unde non.
Quia possimus eveniet magnam tenetur et quia expedita.
Eum rerum officiis rerum qui aliquid laboriosam illum.
Placeat et ipsum molestiae.
Error quia velit ut sit.
Blanditiis est harum reprehenderit amet adipisci sint nesciunt.
Aut fugiat officiis.
Explicabo dolores corporis eaque.
Rem ut et quas consequatur et.",
                            Name = "Licensed Metal Mouse",
                            ShortDescription = "Excepturi dolor blanditiis suscipit architecto perspiciatis expedita odit consequatur.",
                            Updated = new DateTime(2020, 3, 29, 19, 1, 33, 427, DateTimeKind.Local).AddTicks(1000),
                            Uri = "http://micheal.info",
                            UserId = 29
                        },
                        new
                        {
                            Id = 12,
                            Created = new DateTime(2020, 3, 27, 19, 1, 33, 431, DateTimeKind.Local).AddTicks(7048),
                            Description = @"Sit aut voluptatem repudiandae dolor ipsa sit ipsum voluptatem.
Itaque et tempore ratione.
Debitis fugiat sint cum esse veritatis qui itaque laboriosam quia.
Sed molestiae doloribus ab iste quo itaque molestias voluptatem.
Corrupti rerum explicabo totam ducimus veniam quasi itaque.
Nesciunt iusto vero eius voluptatem quam delectus.
Quia omnis ea.
Voluptatibus quod aut et voluptate dolor non in tempora.
Neque eum magnam iure hic quam quia.
Omnis facere repellat minus perferendis suscipit voluptatem impedit qui harum.",
                            Name = "Sleek Soft Hat",
                            ShortDescription = "Et vel minus a quo molestias ratione.",
                            Updated = new DateTime(2020, 3, 29, 19, 1, 33, 431, DateTimeKind.Local).AddTicks(7140),
                            Uri = "http://brown.biz",
                            UserId = 1
                        },
                        new
                        {
                            Id = 13,
                            Created = new DateTime(2020, 3, 27, 19, 1, 33, 435, DateTimeKind.Local).AddTicks(8720),
                            Description = @"Animi enim doloremque ut officiis rem.
Debitis sequi alias est et dolore est.
Distinctio optio qui culpa maiores mollitia placeat et.
Velit aut aut suscipit distinctio non tempore saepe quidem.
Esse veritatis incidunt quod at.
Quae facere distinctio minus.
Ut quaerat quam voluptate aut.
Et minima autem dolor at.
Nesciunt iste doloribus libero non numquam tempora sit porro.
Necessitatibus nemo et et.",
                            Name = "Ergonomic Fresh Pants",
                            ShortDescription = "Mollitia quam earum nulla dicta optio occaecati dignissimos fuga eum.",
                            Updated = new DateTime(2020, 3, 29, 19, 1, 33, 435, DateTimeKind.Local).AddTicks(8799),
                            Uri = "http://karlee.com",
                            UserId = 25
                        },
                        new
                        {
                            Id = 14,
                            Created = new DateTime(2020, 3, 27, 19, 1, 33, 440, DateTimeKind.Local).AddTicks(2784),
                            Description = @"Error modi architecto sit eos quos quo.
Et ea quidem quod consequatur aut autem.
Eum inventore vero et itaque voluptas.
Rerum aut consequatur veniam.
Iusto rerum enim aut delectus.
Maxime reprehenderit ex est minus.
Odit nemo expedita exercitationem aut nihil aliquam enim eos voluptas.
A possimus eum quidem.
Vitae et architecto quos quia iste aut autem sunt.
Est ab consequatur in aspernatur est quia.",
                            Name = "Small Rubber Ball",
                            ShortDescription = "Voluptas harum odit nulla possimus ea fugit perferendis eos aut.",
                            Updated = new DateTime(2020, 3, 29, 19, 1, 33, 440, DateTimeKind.Local).AddTicks(2857),
                            Uri = "https://orlo.name",
                            UserId = 1
                        },
                        new
                        {
                            Id = 15,
                            Created = new DateTime(2020, 3, 27, 19, 1, 33, 443, DateTimeKind.Local).AddTicks(9999),
                            Description = @"Et cumque labore quisquam unde.
Et quia ut non.
Ut quod tempora mollitia.
Eum et consequatur eligendi ut cum libero vel.
Quam doloribus ex id.
Quidem quis nihil dicta.
Voluptates vitae quia dolor.
Et rerum voluptate voluptatum voluptates aut.
Aut quo porro sint quidem cum.
Beatae dolore doloremque eos.",
                            Name = "Rustic Metal Sausages",
                            ShortDescription = "Consequuntur non molestias totam nesciunt exercitationem fugiat.",
                            Updated = new DateTime(2020, 3, 29, 19, 1, 33, 444, DateTimeKind.Local).AddTicks(53),
                            Uri = "http://ferne.info",
                            UserId = 27
                        },
                        new
                        {
                            Id = 16,
                            Created = new DateTime(2020, 3, 27, 19, 1, 33, 448, DateTimeKind.Local).AddTicks(8760),
                            Description = @"Culpa ducimus mollitia enim adipisci totam vitae voluptatem.
Sint sit cum.
Optio quia aut.
Debitis modi soluta et numquam id ipsum dolore dolor beatae.
Maxime dolorem voluptatem dolorem saepe sint explicabo et.
Reiciendis quo reprehenderit dignissimos odit aut.
Qui atque exercitationem eos corporis rerum consequuntur vel voluptas earum.
Commodi quo nihil.
Perferendis reprehenderit ducimus.
Veniam consequatur pariatur dolor dicta.",
                            Name = "Handcrafted Rubber Soap",
                            ShortDescription = "Autem non hic eaque eum labore unde.",
                            Updated = new DateTime(2020, 3, 29, 19, 1, 33, 448, DateTimeKind.Local).AddTicks(8834),
                            Uri = "http://macie.com",
                            UserId = 23
                        },
                        new
                        {
                            Id = 17,
                            Created = new DateTime(2020, 3, 27, 19, 1, 33, 453, DateTimeKind.Local).AddTicks(6656),
                            Description = @"Odit optio laboriosam quo hic.
Minus dicta inventore tenetur qui alias asperiores fugiat illum.
Animi cumque non ut molestiae aut dolor.
Et nihil sint aliquam delectus nihil quaerat magni qui.
Ipsum qui accusantium.
Fugiat ut accusamus.
Rem asperiores eius eum et.
Exercitationem consequuntur sed inventore cum in voluptate asperiores.
Similique laboriosam dolore suscipit deleniti quia ex.
Eligendi omnis debitis distinctio incidunt mollitia officia accusamus.",
                            Name = "Handmade Fresh Sausages",
                            ShortDescription = "Libero quidem rerum sit omnis libero praesentium et a voluptas.",
                            Updated = new DateTime(2020, 3, 29, 19, 1, 33, 453, DateTimeKind.Local).AddTicks(6739),
                            Uri = "http://neha.net",
                            UserId = 8
                        },
                        new
                        {
                            Id = 18,
                            Created = new DateTime(2020, 3, 27, 19, 1, 33, 457, DateTimeKind.Local).AddTicks(6013),
                            Description = @"Praesentium tempore qui.
Reprehenderit dolorem fugit ullam non ad consequatur illo veritatis non.
Amet cumque minus assumenda ex laboriosam perferendis.
Temporibus provident occaecati veniam est dolores labore quas.
Corrupti dolorem eos repudiandae.
Architecto minima totam cupiditate aut.
Qui sunt placeat.
Enim ab aut facere voluptatem earum illum qui dignissimos alias.
Consequatur officiis rerum nisi aut quis est velit error.
Reprehenderit et ut fuga qui ullam fugiat blanditiis maiores ad.",
                            Name = "Small Metal Mouse",
                            ShortDescription = "Repellendus dolorum ut quisquam atque corrupti amet tempora.",
                            Updated = new DateTime(2020, 3, 29, 19, 1, 33, 457, DateTimeKind.Local).AddTicks(6066),
                            Uri = "https://colby.info",
                            UserId = 11
                        },
                        new
                        {
                            Id = 19,
                            Created = new DateTime(2020, 3, 27, 19, 1, 33, 461, DateTimeKind.Local).AddTicks(2694),
                            Description = @"Qui dolor beatae quod dolorum saepe.
Consequatur et iusto aut.
Et rerum maiores ad.
Est aspernatur qui aliquam sint fuga.
Et officia aut eveniet blanditiis.
Nihil voluptate sint quae porro et autem dolore.
Aut id laborum ab quis quis ea voluptatem.
Soluta dolorem ut consectetur qui consequuntur sequi.
Iste possimus itaque doloremque sint veniam unde modi.
Nihil quia qui et suscipit eveniet quia et.",
                            Name = "Unbranded Granite Chicken",
                            ShortDescription = "Voluptatibus rerum et laboriosam rerum.",
                            Updated = new DateTime(2020, 3, 29, 19, 1, 33, 461, DateTimeKind.Local).AddTicks(2738),
                            Uri = "https://ian.net",
                            UserId = 12
                        },
                        new
                        {
                            Id = 20,
                            Created = new DateTime(2020, 3, 27, 19, 1, 33, 465, DateTimeKind.Local).AddTicks(5016),
                            Description = @"Aut autem necessitatibus ab aspernatur et enim.
Rerum voluptatem veritatis dolorem iste libero sequi et.
Ut ut accusantium quia aut qui sint et.
Consequatur et omnis provident.
Quaerat omnis numquam.
Esse non officiis labore minima eveniet odio voluptate.
In eaque dolor minima quis assumenda quisquam accusamus.
Iusto reprehenderit et.
Autem dolore aut consequatur vel et ex magnam.
Et laboriosam reiciendis id similique autem aut doloribus magni.",
                            Name = "Intelligent Plastic Shoes",
                            ShortDescription = "Optio deleniti earum omnis iusto provident non doloribus.",
                            Updated = new DateTime(2020, 3, 29, 19, 1, 33, 465, DateTimeKind.Local).AddTicks(5080),
                            Uri = "http://dominic.info",
                            UserId = 25
                        },
                        new
                        {
                            Id = 21,
                            Created = new DateTime(2020, 3, 27, 19, 1, 33, 471, DateTimeKind.Local).AddTicks(3683),
                            Description = @"Omnis fuga ex rem dicta in ab esse assumenda.
Odio ullam unde velit non omnis aperiam corporis quo quia.
Iusto corrupti dignissimos ad.
Officiis perspiciatis ab similique id sint adipisci.
Sit dolorem facere sint ipsa odit est et ipsum repellendus.
Ut nam temporibus aut iusto sed voluptatem aut in mollitia.
Eos repudiandae adipisci.
Cumque molestias commodi sed ut et.
In sit omnis.
Sint voluptatem est.",
                            Name = "Incredible Fresh Cheese",
                            ShortDescription = "Aut ut cumque ducimus ipsa itaque vitae.",
                            Updated = new DateTime(2020, 3, 29, 19, 1, 33, 471, DateTimeKind.Local).AddTicks(3771),
                            Uri = "https://clinton.biz",
                            UserId = 9
                        },
                        new
                        {
                            Id = 22,
                            Created = new DateTime(2020, 3, 27, 19, 1, 33, 476, DateTimeKind.Local).AddTicks(6004),
                            Description = @"Eveniet doloremque voluptas quia omnis ea.
Nihil delectus unde quasi.
Dicta est sed molestiae.
Omnis quas perferendis quos pariatur odio laudantium voluptatem.
Et pariatur maxime quo occaecati sint quos.
Veniam minus dolorem adipisci.
Sed nihil in ullam voluptatem autem sint pariatur.
Ut amet soluta tenetur et animi.
Quae deserunt vel ipsum alias temporibus nostrum a magni doloremque.
Quidem necessitatibus quia iure quaerat quos ab.",
                            Name = "Handmade Cotton Soap",
                            ShortDescription = "Deserunt explicabo omnis quis dicta.",
                            Updated = new DateTime(2020, 3, 29, 19, 1, 33, 476, DateTimeKind.Local).AddTicks(6077),
                            Uri = "https://letitia.info",
                            UserId = 2
                        },
                        new
                        {
                            Id = 23,
                            Created = new DateTime(2020, 3, 27, 19, 1, 33, 481, DateTimeKind.Local).AddTicks(9327),
                            Description = @"Laborum necessitatibus enim ut qui temporibus voluptatem.
Esse dolores odio dolorem quia qui minima a.
Sequi non amet et.
Consequatur temporibus dolores corporis nostrum recusandae ullam.
Voluptatibus in aut laudantium rerum maxime in dicta.
Totam rem nisi rerum.
Et eum dolorem voluptatem a maxime.
Voluptatem et ut distinctio consequatur aut occaecati quod voluptas dolores.
Voluptate assumenda voluptatem.
Adipisci distinctio officiis.",
                            Name = "Incredible Rubber Keyboard",
                            ShortDescription = "Vel et repudiandae praesentium porro natus quisquam.",
                            Updated = new DateTime(2020, 3, 29, 19, 1, 33, 481, DateTimeKind.Local).AddTicks(9401),
                            Uri = "http://mayra.com",
                            UserId = 4
                        },
                        new
                        {
                            Id = 24,
                            Created = new DateTime(2020, 3, 27, 19, 1, 33, 486, DateTimeKind.Local).AddTicks(6506),
                            Description = @"Distinctio eum est alias et earum eos.
Nisi ea ut.
Itaque fugit nemo laborum amet molestias.
Nihil commodi sint labore dolorem aliquam.
Veniam sit eum.
Nihil totam aut at odit voluptatem enim consectetur.
Recusandae tempore quia quisquam molestias corrupti suscipit dolorum id.
Cupiditate molestiae harum quidem.
Consectetur quod deserunt id placeat optio expedita.
Tempore porro cumque quas enim dicta aut.",
                            Name = "Rustic Steel Chips",
                            ShortDescription = "Nisi repellat est blanditiis placeat ipsa adipisci qui cum sint.",
                            Updated = new DateTime(2020, 3, 29, 19, 1, 33, 486, DateTimeKind.Local).AddTicks(6589),
                            Uri = "https://brigitte.com",
                            UserId = 17
                        },
                        new
                        {
                            Id = 25,
                            Created = new DateTime(2020, 3, 27, 19, 1, 33, 491, DateTimeKind.Local).AddTicks(5448),
                            Description = @"Iste nam consequatur qui nam odio nesciunt ad qui.
Consequatur consequatur maiores veritatis provident mollitia quaerat dolor.
Voluptatibus sit aut ratione perspiciatis eos molestiae eum numquam reiciendis.
Vel perferendis et tempore porro nihil.
Quaerat soluta iste corrupti dolor est reprehenderit consectetur.
Est vero hic vitae fugiat soluta omnis sunt est placeat.
Qui et id est rerum ullam cumque.
Doloribus sit ipsam ut aut tenetur repellat et quis.
Alias velit facere ex earum labore.
Ut eveniet est dolores labore sed voluptatem delectus et qui.",
                            Name = "Refined Metal Car",
                            ShortDescription = "Earum rerum perspiciatis aut et iste.",
                            Updated = new DateTime(2020, 3, 29, 19, 1, 33, 491, DateTimeKind.Local).AddTicks(5512),
                            Uri = "http://marie.com",
                            UserId = 16
                        },
                        new
                        {
                            Id = 26,
                            Created = new DateTime(2020, 3, 27, 19, 1, 33, 495, DateTimeKind.Local).AddTicks(9678),
                            Description = @"Dolor ea deserunt facilis omnis omnis totam molestiae et.
Cum ea sunt nihil facere facilis exercitationem vel.
Dolores est natus nihil.
Quia nostrum velit sequi sed et totam molestiae assumenda omnis.
Fugiat earum autem esse ratione ex laudantium dignissimos enim et.
Vel at ducimus explicabo beatae consequuntur.
Asperiores tempora dolorum reiciendis rerum cupiditate quaerat error.
Est quidem dolorem dolore harum.
Placeat sint cumque sint delectus.
Dolor qui sed.",
                            Name = "Sleek Fresh Keyboard",
                            ShortDescription = "Dicta facilis voluptatum.",
                            Updated = new DateTime(2020, 3, 29, 19, 1, 33, 495, DateTimeKind.Local).AddTicks(9751),
                            Uri = "http://myrtie.info",
                            UserId = 18
                        },
                        new
                        {
                            Id = 27,
                            Created = new DateTime(2020, 3, 27, 19, 1, 33, 501, DateTimeKind.Local).AddTicks(3622),
                            Description = @"Omnis suscipit at corporis at sequi culpa ipsa id.
Qui dolorum nulla et aut provident reprehenderit neque neque.
Non vitae quas et iste debitis repellendus.
Est dolorum pariatur eum.
At voluptas esse veritatis in veritatis.
Deleniti id voluptate enim ut totam quibusdam reiciendis et.
Quo dolorum quia eius.
Totam eum maiores maxime aut quis ea.
Sed a ipsam dolorem doloribus minus.
Totam asperiores aspernatur aliquid aspernatur rem cum consectetur.",
                            Name = "Licensed Plastic Bacon",
                            ShortDescription = "Sunt beatae aut aut et et incidunt et ut quis.",
                            Updated = new DateTime(2020, 3, 29, 19, 1, 33, 501, DateTimeKind.Local).AddTicks(3724),
                            Uri = "http://meaghan.com",
                            UserId = 17
                        },
                        new
                        {
                            Id = 28,
                            Created = new DateTime(2020, 3, 27, 19, 1, 33, 507, DateTimeKind.Local).AddTicks(2230),
                            Description = @"Corporis quis ex.
Ullam aut et natus nihil quisquam occaecati dolorem.
Sunt autem quidem.
Et saepe error.
Alias non est distinctio non nihil.
Aspernatur reprehenderit laboriosam aut voluptates voluptatibus.
Iure quo et temporibus.
Natus velit qui amet impedit.
Fugit adipisci quas hic maiores alias consectetur debitis qui.
Beatae et asperiores consequatur aut.",
                            Name = "Handcrafted Steel Table",
                            ShortDescription = "Laudantium enim vel molestias repudiandae eos et voluptate et.",
                            Updated = new DateTime(2020, 3, 29, 19, 1, 33, 507, DateTimeKind.Local).AddTicks(2308),
                            Uri = "http://kyler.com",
                            UserId = 9
                        },
                        new
                        {
                            Id = 29,
                            Created = new DateTime(2020, 3, 27, 19, 1, 33, 516, DateTimeKind.Local).AddTicks(9817),
                            Description = @"Sit eum illum.
Recusandae voluptatem voluptate laboriosam illum aperiam magnam.
Enim non dolore nihil ipsum facere hic esse aut.
Repudiandae reiciendis ad aspernatur.
Eos dolores similique debitis.
Doloremque illo est dolorem omnis mollitia debitis ipsam et.
Est aut rerum.
Explicabo deserunt animi.
Qui dolore voluptatem vero eius qui.
Voluptas ut fugiat alias ut sed magnam sequi dolores quo.",
                            Name = "Small Frozen Ball",
                            ShortDescription = "Animi vitae accusamus sunt debitis.",
                            Updated = new DateTime(2020, 3, 29, 19, 1, 33, 516, DateTimeKind.Local).AddTicks(9915),
                            Uri = "https://salvatore.name",
                            UserId = 2
                        },
                        new
                        {
                            Id = 30,
                            Created = new DateTime(2020, 3, 27, 19, 1, 33, 522, DateTimeKind.Local).AddTicks(8997),
                            Description = @"Alias iste ut optio.
Et minus quia.
Repellendus magnam quo commodi ipsa ipsam quidem voluptas odio.
Reprehenderit eius voluptas doloribus sint sunt debitis quis.
Nisi blanditiis ipsam aut placeat sit.
Dignissimos qui molestias dolores non voluptas distinctio quam vel.
Nesciunt non fugiat voluptatem officiis et et nemo optio.
Neque similique voluptatem quia labore aliquam nisi eum vel rem.
Sapiente nisi non accusamus et.
Nemo adipisci et natus quam.",
                            Name = "Sleek Steel Computer",
                            ShortDescription = "Nobis velit libero sed.",
                            Updated = new DateTime(2020, 3, 29, 19, 1, 33, 522, DateTimeKind.Local).AddTicks(9071),
                            Uri = "https://johnpaul.net",
                            UserId = 19
                        });
                });

            modelBuilder.Entity("Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Stanton_Ullrich@hotmail.com",
                            IdentityId = "2",
                            Name = "Melyssa"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Hellen35@yahoo.com",
                            IdentityId = "3",
                            Name = "Rhett"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Myriam.Kohler6@gmail.com",
                            IdentityId = "4",
                            Name = "Jeff"
                        },
                        new
                        {
                            Id = 4,
                            Email = "Jaiden77@gmail.com",
                            IdentityId = "5",
                            Name = "Tracy"
                        },
                        new
                        {
                            Id = 5,
                            Email = "Gay_Hermann34@hotmail.com",
                            IdentityId = "6",
                            Name = "Beverly"
                        },
                        new
                        {
                            Id = 6,
                            Email = "Lonnie74@yahoo.com",
                            IdentityId = "7",
                            Name = "Pauline"
                        },
                        new
                        {
                            Id = 7,
                            Email = "Nicholaus_Nikolaus72@yahoo.com",
                            IdentityId = "8",
                            Name = "Ida"
                        },
                        new
                        {
                            Id = 8,
                            Email = "Carlie_Goyette17@hotmail.com",
                            IdentityId = "9",
                            Name = "Adela"
                        },
                        new
                        {
                            Id = 9,
                            Email = "Vergie75@hotmail.com",
                            IdentityId = "10",
                            Name = "Isaiah"
                        },
                        new
                        {
                            Id = 10,
                            Email = "Ramona47@gmail.com",
                            IdentityId = "11",
                            Name = "Branson"
                        },
                        new
                        {
                            Id = 11,
                            Email = "Kenny.Wintheiser@hotmail.com",
                            IdentityId = "12",
                            Name = "Ashlynn"
                        },
                        new
                        {
                            Id = 12,
                            Email = "Laurianne63@gmail.com",
                            IdentityId = "13",
                            Name = "Ericka"
                        },
                        new
                        {
                            Id = 13,
                            Email = "Haskell61@gmail.com",
                            IdentityId = "14",
                            Name = "Jessica"
                        },
                        new
                        {
                            Id = 14,
                            Email = "Elissa.Lubowitz56@yahoo.com",
                            IdentityId = "15",
                            Name = "Ayden"
                        },
                        new
                        {
                            Id = 15,
                            Email = "Genoveva59@yahoo.com",
                            IdentityId = "16",
                            Name = "Georgiana"
                        },
                        new
                        {
                            Id = 16,
                            Email = "Jeanne.Kreiger88@yahoo.com",
                            IdentityId = "17",
                            Name = "Ella"
                        },
                        new
                        {
                            Id = 17,
                            Email = "Kattie_Kunze@gmail.com",
                            IdentityId = "18",
                            Name = "Nelle"
                        },
                        new
                        {
                            Id = 18,
                            Email = "Neva.Windler@gmail.com",
                            IdentityId = "19",
                            Name = "Jesse"
                        },
                        new
                        {
                            Id = 19,
                            Email = "Felton53@gmail.com",
                            IdentityId = "20",
                            Name = "Alden"
                        },
                        new
                        {
                            Id = 20,
                            Email = "Grace_Balistreri52@yahoo.com",
                            IdentityId = "21",
                            Name = "Vinnie"
                        },
                        new
                        {
                            Id = 21,
                            Email = "Shakira72@gmail.com",
                            IdentityId = "22",
                            Name = "Itzel"
                        },
                        new
                        {
                            Id = 22,
                            Email = "Gerhard92@gmail.com",
                            IdentityId = "23",
                            Name = "Katelyn"
                        },
                        new
                        {
                            Id = 23,
                            Email = "Benedict63@hotmail.com",
                            IdentityId = "24",
                            Name = "Quinn"
                        },
                        new
                        {
                            Id = 24,
                            Email = "Dexter_Carter@gmail.com",
                            IdentityId = "25",
                            Name = "Gregg"
                        },
                        new
                        {
                            Id = 25,
                            Email = "Treva.Turcotte72@gmail.com",
                            IdentityId = "26",
                            Name = "Lizeth"
                        },
                        new
                        {
                            Id = 26,
                            Email = "Wade_Cassin7@yahoo.com",
                            IdentityId = "27",
                            Name = "Dagmar"
                        },
                        new
                        {
                            Id = 27,
                            Email = "Pearlie.Bartell@gmail.com",
                            IdentityId = "28",
                            Name = "Myrtle"
                        },
                        new
                        {
                            Id = 28,
                            Email = "Freida_Maggio14@hotmail.com",
                            IdentityId = "29",
                            Name = "Emmitt"
                        },
                        new
                        {
                            Id = 29,
                            Email = "Sydni66@yahoo.com",
                            IdentityId = "30",
                            Name = "Godfrey"
                        },
                        new
                        {
                            Id = 30,
                            Email = "Maximilian.Schaden@yahoo.com",
                            IdentityId = "31",
                            Name = "Tina"
                        });
                });

            modelBuilder.Entity("Models.Collaborator", b =>
                {
                    b.HasOne("Models.Project", null)
                        .WithMany("Collaborators")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.Project", b =>
                {
                    b.HasOne("Models.User", "User")
                        .WithMany("Projects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
