// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace _4_Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200419124523_HighlightBooleanRemoval")]
    partial class HighlightBooleanRemoval
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.Collaborator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Collaborators");

                    b.HasData(
                        new
                        {
                            Id = 2046,
                            FullName = "Ressie Rodriguez",
                            ProjectId = 1,
                            Role = "Chief Metrics Associate"
                        },
                        new
                        {
                            Id = 2447,
                            FullName = "Alia Barton",
                            ProjectId = 1,
                            Role = "Legacy Configuration Producer"
                        },
                        new
                        {
                            Id = 9113,
                            FullName = "Elyssa Blick",
                            ProjectId = 2,
                            Role = "Regional Communications Officer"
                        },
                        new
                        {
                            Id = 8461,
                            FullName = "Bennie Shanahan",
                            ProjectId = 2,
                            Role = "Investor Accountability Liaison"
                        },
                        new
                        {
                            Id = 2477,
                            FullName = "Gerhard Cartwright",
                            ProjectId = 3,
                            Role = "Legacy Brand Executive"
                        },
                        new
                        {
                            Id = 6201,
                            FullName = "Imani Bergstrom",
                            ProjectId = 3,
                            Role = "Corporate Response Director"
                        },
                        new
                        {
                            Id = 928,
                            FullName = "Thurman Daniel",
                            ProjectId = 4,
                            Role = "Future Security Facilitator"
                        },
                        new
                        {
                            Id = 1826,
                            FullName = "Hermann Mante",
                            ProjectId = 4,
                            Role = "Legacy Creative Consultant"
                        },
                        new
                        {
                            Id = 9512,
                            FullName = "Sierra Altenwerth",
                            ProjectId = 5,
                            Role = "Human Branding Assistant"
                        },
                        new
                        {
                            Id = 8969,
                            FullName = "Larissa West",
                            ProjectId = 5,
                            Role = "Investor Quality Planner"
                        },
                        new
                        {
                            Id = 9355,
                            FullName = "Jensen Wolff",
                            ProjectId = 6,
                            Role = "Chief Research Administrator"
                        },
                        new
                        {
                            Id = 6888,
                            FullName = "Myra Bahringer",
                            ProjectId = 6,
                            Role = "Legacy Response Technician"
                        },
                        new
                        {
                            Id = 9959,
                            FullName = "Lavonne Abshire",
                            ProjectId = 7,
                            Role = "Chief Group Architect"
                        },
                        new
                        {
                            Id = 5753,
                            FullName = "Jimmy Lowe",
                            ProjectId = 7,
                            Role = "National Data Officer"
                        },
                        new
                        {
                            Id = 753,
                            FullName = "Millie Schamberger",
                            ProjectId = 8,
                            Role = "Future Response Developer"
                        },
                        new
                        {
                            Id = 3803,
                            FullName = "Jennings Friesen",
                            ProjectId = 8,
                            Role = "Customer Paradigm Orchestrator"
                        },
                        new
                        {
                            Id = 8950,
                            FullName = "Darian Hagenes",
                            ProjectId = 9,
                            Role = "Corporate Brand Executive"
                        },
                        new
                        {
                            Id = 7525,
                            FullName = "Colleen Moore",
                            ProjectId = 9,
                            Role = "National Interactions Associate"
                        },
                        new
                        {
                            Id = 7958,
                            FullName = "Tyrese Crooks",
                            ProjectId = 10,
                            Role = "Central Solutions Officer"
                        },
                        new
                        {
                            Id = 445,
                            FullName = "Lacey Pollich",
                            ProjectId = 10,
                            Role = "Forward Accountability Coordinator"
                        },
                        new
                        {
                            Id = 6223,
                            FullName = "Hermann Koelpin",
                            ProjectId = 11,
                            Role = "National Identity Consultant"
                        },
                        new
                        {
                            Id = 4303,
                            FullName = "Harmon Green",
                            ProjectId = 11,
                            Role = "Regional Brand Officer"
                        },
                        new
                        {
                            Id = 1419,
                            FullName = "Heaven King",
                            ProjectId = 12,
                            Role = "District Communications Orchestrator"
                        },
                        new
                        {
                            Id = 5569,
                            FullName = "Nathaniel Schultz",
                            ProjectId = 12,
                            Role = "Legacy Applications Director"
                        },
                        new
                        {
                            Id = 5374,
                            FullName = "Sheridan Kohler",
                            ProjectId = 13,
                            Role = "Senior Operations Producer"
                        },
                        new
                        {
                            Id = 9190,
                            FullName = "Asa Hermann",
                            ProjectId = 13,
                            Role = "Chief Operations Orchestrator"
                        },
                        new
                        {
                            Id = 6404,
                            FullName = "Hipolito Sipes",
                            ProjectId = 14,
                            Role = "Internal Interactions Analyst"
                        },
                        new
                        {
                            Id = 7666,
                            FullName = "Granville Towne",
                            ProjectId = 14,
                            Role = "Principal Identity Orchestrator"
                        },
                        new
                        {
                            Id = 7262,
                            FullName = "Laury Zemlak",
                            ProjectId = 15,
                            Role = "Senior Functionality Liaison"
                        },
                        new
                        {
                            Id = 5798,
                            FullName = "Shirley Will",
                            ProjectId = 15,
                            Role = "Direct Data Analyst"
                        },
                        new
                        {
                            Id = 3224,
                            FullName = "Filiberto Swift",
                            ProjectId = 16,
                            Role = "Customer Applications Strategist"
                        },
                        new
                        {
                            Id = 8448,
                            FullName = "Daniela Torphy",
                            ProjectId = 16,
                            Role = "Forward Data Officer"
                        },
                        new
                        {
                            Id = 7690,
                            FullName = "Morton Stamm",
                            ProjectId = 17,
                            Role = "National Usability Associate"
                        },
                        new
                        {
                            Id = 4430,
                            FullName = "Kieran Leuschke",
                            ProjectId = 17,
                            Role = "Internal Tactics Representative"
                        },
                        new
                        {
                            Id = 7311,
                            FullName = "Richie Skiles",
                            ProjectId = 18,
                            Role = "Dynamic Tactics Technician"
                        },
                        new
                        {
                            Id = 6739,
                            FullName = "Jon Oberbrunner",
                            ProjectId = 18,
                            Role = "National Optimization Designer"
                        },
                        new
                        {
                            Id = 6166,
                            FullName = "Colten Waelchi",
                            ProjectId = 19,
                            Role = "Chief Research Liaison"
                        },
                        new
                        {
                            Id = 7211,
                            FullName = "Talon Schamberger",
                            ProjectId = 19,
                            Role = "Internal Paradigm Designer"
                        },
                        new
                        {
                            Id = 2837,
                            FullName = "Derrick Waelchi",
                            ProjectId = 20,
                            Role = "Human Quality Manager"
                        },
                        new
                        {
                            Id = 9476,
                            FullName = "Jamarcus Abshire",
                            ProjectId = 20,
                            Role = "Chief Creative Technician"
                        },
                        new
                        {
                            Id = 1360,
                            FullName = "Lillian Toy",
                            ProjectId = 21,
                            Role = "Future Marketing Specialist"
                        },
                        new
                        {
                            Id = 5177,
                            FullName = "Hector Farrell",
                            ProjectId = 21,
                            Role = "Product Assurance Consultant"
                        },
                        new
                        {
                            Id = 1495,
                            FullName = "Jude Klocko",
                            ProjectId = 22,
                            Role = "District Marketing Administrator"
                        },
                        new
                        {
                            Id = 1532,
                            FullName = "Stevie Langosh",
                            ProjectId = 22,
                            Role = "Product Factors Associate"
                        },
                        new
                        {
                            Id = 7258,
                            FullName = "Palma Shields",
                            ProjectId = 23,
                            Role = "District Markets Supervisor"
                        },
                        new
                        {
                            Id = 5401,
                            FullName = "Mark Hills",
                            ProjectId = 23,
                            Role = "Future Accounts Analyst"
                        },
                        new
                        {
                            Id = 2351,
                            FullName = "Jayde Runte",
                            ProjectId = 24,
                            Role = "Central Paradigm Agent"
                        },
                        new
                        {
                            Id = 2923,
                            FullName = "William Lowe",
                            ProjectId = 24,
                            Role = "Corporate Mobility Officer"
                        },
                        new
                        {
                            Id = 7543,
                            FullName = "Kaleb Harber",
                            ProjectId = 25,
                            Role = "Customer Accounts Representative"
                        },
                        new
                        {
                            Id = 1389,
                            FullName = "Reinhold Parker",
                            ProjectId = 25,
                            Role = "Forward Operations Director"
                        },
                        new
                        {
                            Id = 4672,
                            FullName = "Armani Aufderhar",
                            ProjectId = 26,
                            Role = "Dynamic Accounts Supervisor"
                        },
                        new
                        {
                            Id = 3963,
                            FullName = "Seth Robel",
                            ProjectId = 26,
                            Role = "Principal Directives Technician"
                        },
                        new
                        {
                            Id = 6702,
                            FullName = "Magali Medhurst",
                            ProjectId = 27,
                            Role = "Investor Solutions Representative"
                        },
                        new
                        {
                            Id = 5312,
                            FullName = "Khalid Beahan",
                            ProjectId = 27,
                            Role = "Dynamic Quality Facilitator"
                        },
                        new
                        {
                            Id = 7094,
                            FullName = "Weldon Turner",
                            ProjectId = 28,
                            Role = "District Research Strategist"
                        },
                        new
                        {
                            Id = 8163,
                            FullName = "Herbert Wisoky",
                            ProjectId = 28,
                            Role = "District Solutions Manager"
                        },
                        new
                        {
                            Id = 8807,
                            FullName = "Bartholome Erdman",
                            ProjectId = 29,
                            Role = "Global Accounts Facilitator"
                        },
                        new
                        {
                            Id = 4187,
                            FullName = "Peter Hettinger",
                            ProjectId = 29,
                            Role = "Dynamic Interactions Liaison"
                        },
                        new
                        {
                            Id = 3375,
                            FullName = "Junior Schmidt",
                            ProjectId = 30,
                            Role = "International Response Representative"
                        },
                        new
                        {
                            Id = 3071,
                            FullName = "Piper Jacobi",
                            ProjectId = 30,
                            Role = "Corporate Applications Consultant"
                        });
                });

            modelBuilder.Entity("Models.Highlight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Highlight");
                });

            modelBuilder.Entity("Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Project");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2020, 4, 17, 14, 45, 22, 151, DateTimeKind.Local).AddTicks(2056),
                            Description = @"Voluptas quia nemo magnam natus dolor.
Eos assumenda dolorem ut consectetur voluptatem.
Et aliquam perferendis deserunt impedit iure eaque hic iste.
Laborum pariatur tempora minima maxime ut assumenda et eveniet beatae.
Laborum rem nulla quae.
Assumenda et molestiae et.
Eveniet ullam consectetur et exercitationem non et fugiat.
Odio vel dolorum quam.
Impedit hic aspernatur reprehenderit quas in quis nostrum.
Libero magnam repellendus.",
                            Name = "Intelligent Granite Towels",
                            ShortDescription = "Perspiciatis praesentium et ut.",
                            Updated = new DateTime(2020, 4, 19, 14, 45, 22, 155, DateTimeKind.Local).AddTicks(5088),
                            Uri = "https://kattie.org",
                            UserId = 25
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2020, 4, 17, 14, 45, 22, 159, DateTimeKind.Local).AddTicks(8491),
                            Description = @"Ducimus laboriosam eos aperiam id rerum maxime asperiores.
Sed suscipit exercitationem.
Velit nihil ea commodi id incidunt cupiditate in.
Possimus vitae quis perspiciatis sed ex accusamus.
Molestiae nesciunt voluptates rem rerum.
Quaerat laboriosam iste molestiae.
Quaerat id delectus non neque rerum dolorem id aliquid temporibus.
Quia sint tempora.
Culpa inventore distinctio adipisci iusto reprehenderit quia dolor ad dolor.
Velit laudantium quaerat qui accusantium ab.",
                            Name = "Handmade Rubber Chair",
                            ShortDescription = "Animi eos est temporibus officiis quia animi vel placeat.",
                            Updated = new DateTime(2020, 4, 19, 14, 45, 22, 159, DateTimeKind.Local).AddTicks(8565),
                            Uri = "http://nicholas.com",
                            UserId = 11
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2020, 4, 17, 14, 45, 22, 164, DateTimeKind.Local).AddTicks(2951),
                            Description = @"Qui sed cum.
Asperiores non eos tenetur eligendi.
Omnis maxime ea.
Quia omnis inventore occaecati repudiandae.
Neque temporibus sit.
Deserunt inventore rerum id ullam blanditiis.
Asperiores tenetur blanditiis cum earum.
Est consequatur architecto alias qui.
Nulla et at.
Voluptate ipsam porro.",
                            Name = "Refined Cotton Bike",
                            ShortDescription = "Enim deleniti neque nulla autem sit modi assumenda itaque.",
                            Updated = new DateTime(2020, 4, 19, 14, 45, 22, 164, DateTimeKind.Local).AddTicks(3019),
                            Uri = "https://jaycee.net",
                            UserId = 23
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2020, 4, 17, 14, 45, 22, 168, DateTimeKind.Local).AddTicks(7401),
                            Description = @"Ut libero voluptatem velit consequatur quo voluptas vitae nisi.
Laboriosam voluptatem quod eaque ut nostrum culpa eligendi.
Sint temporibus laborum.
Molestiae consequuntur et officiis amet rem dolorem et nesciunt est.
Fugit id ab.
Qui animi quidem beatae quas.
Soluta sed accusantium.
Et et architecto ut et ut alias nostrum temporibus laboriosam.
Dignissimos voluptas et laborum dolor.
Sit autem soluta et et labore ad ullam et.",
                            Name = "Intelligent Metal Cheese",
                            ShortDescription = "Quo odit dolor et et saepe aut sed tempora sunt.",
                            Updated = new DateTime(2020, 4, 19, 14, 45, 22, 168, DateTimeKind.Local).AddTicks(7455),
                            Uri = "https://kacey.name",
                            UserId = 22
                        },
                        new
                        {
                            Id = 5,
                            Created = new DateTime(2020, 4, 17, 14, 45, 22, 173, DateTimeKind.Local).AddTicks(3937),
                            Description = @"Sit hic possimus voluptatibus totam voluptas enim dolores.
Nisi reiciendis voluptatem alias quibusdam et modi reprehenderit nostrum.
Consequatur explicabo consequatur unde.
Sed eum dicta quas cum repellat et aspernatur omnis.
Quaerat ut cum saepe et omnis excepturi.
Explicabo omnis repellat eum modi exercitationem beatae veniam.
Voluptas rerum earum et et in rerum et vitae et.
Illum fugiat porro aut mollitia rem ut saepe perspiciatis.
Quae ea dolores ut enim repellat.
Minus nesciunt temporibus molestiae qui consequatur eos blanditiis est.",
                            Name = "Small Fresh Sausages",
                            ShortDescription = "Id rerum temporibus accusantium neque sed maxime non voluptatem fugiat.",
                            Updated = new DateTime(2020, 4, 19, 14, 45, 22, 173, DateTimeKind.Local).AddTicks(3996),
                            Uri = "http://joan.info",
                            UserId = 19
                        },
                        new
                        {
                            Id = 6,
                            Created = new DateTime(2020, 4, 17, 14, 45, 22, 177, DateTimeKind.Local).AddTicks(4794),
                            Description = @"Porro ut ducimus enim vel in.
Dolores molestiae qui.
Nihil dolorem vero nihil doloribus.
Recusandae hic possimus totam rerum accusamus placeat.
Aut dolorem facere rerum voluptate aperiam.
Distinctio sint qui modi.
Facilis modi perspiciatis est.
Labore vitae ea molestias odio reiciendis eligendi quibusdam consectetur dolorem.
Voluptatibus voluptatem fugiat consequatur.
At quis ut quaerat consectetur sint quam explicabo.",
                            Name = "Handmade Concrete Fish",
                            ShortDescription = "Nemo quo sed dolorem sint impedit ea voluptatibus in.",
                            Updated = new DateTime(2020, 4, 19, 14, 45, 22, 177, DateTimeKind.Local).AddTicks(4838),
                            Uri = "http://pansy.net",
                            UserId = 20
                        },
                        new
                        {
                            Id = 7,
                            Created = new DateTime(2020, 4, 17, 14, 45, 22, 181, DateTimeKind.Local).AddTicks(8467),
                            Description = @"Ratione eius non.
Cum quos enim.
Laudantium autem pariatur enim excepturi nihil quisquam distinctio nemo.
Magni ut quos ut ad fugit fugiat alias.
Amet culpa aliquid earum aut ab.
Ipsa exercitationem non sunt.
Illum in ut.
Quia vero explicabo totam accusamus.
Consequuntur eaque neque iusto et sunt quia rerum explicabo quia.
Ipsa consequuntur ad aut pariatur quae quaerat ipsam.",
                            Name = "Unbranded Rubber Mouse",
                            ShortDescription = "Nihil qui eius distinctio ipsam et qui est.",
                            Updated = new DateTime(2020, 4, 19, 14, 45, 22, 181, DateTimeKind.Local).AddTicks(8536),
                            Uri = "https://pamela.info",
                            UserId = 12
                        },
                        new
                        {
                            Id = 8,
                            Created = new DateTime(2020, 4, 17, 14, 45, 22, 185, DateTimeKind.Local).AddTicks(9186),
                            Description = @"Ipsam omnis consequatur consequuntur et et.
Sed repudiandae voluptate est ad.
Magnam ad vel.
Sequi quia et cum illum quas quia inventore molestiae.
Autem quo et qui laudantium et qui.
Quasi soluta dolores est quibusdam architecto sit nemo magnam.
Officia quasi ex officiis dignissimos voluptates vel.
Omnis dolor dolores enim dolore.
Velit ullam iste.
Deleniti ut enim velit magnam.",
                            Name = "Awesome Rubber Ball",
                            ShortDescription = "Sed dolores cumque laudantium velit molestiae.",
                            Updated = new DateTime(2020, 4, 19, 14, 45, 22, 185, DateTimeKind.Local).AddTicks(9230),
                            Uri = "http://desiree.net",
                            UserId = 3
                        },
                        new
                        {
                            Id = 9,
                            Created = new DateTime(2020, 4, 17, 14, 45, 22, 189, DateTimeKind.Local).AddTicks(8743),
                            Description = @"Et reprehenderit cupiditate voluptas.
Odit ipsa ullam.
Et veritatis corrupti dolores sint ab dolorem voluptatibus ut.
Qui ut tempore enim.
Repudiandae sapiente sit iusto.
Sit libero id voluptas dicta quidem necessitatibus a quas eius.
Quia sequi ea cumque quidem.
Repudiandae repudiandae nostrum est enim nisi quis sed nemo dolore.
Ipsam pariatur magni.
Id ipsam dolor voluptas praesentium est voluptate debitis neque.",
                            Name = "Awesome Granite Pants",
                            ShortDescription = "Deleniti perferendis officiis laborum maxime ut laborum sunt itaque.",
                            Updated = new DateTime(2020, 4, 19, 14, 45, 22, 189, DateTimeKind.Local).AddTicks(8792),
                            Uri = "http://johnson.biz",
                            UserId = 10
                        },
                        new
                        {
                            Id = 10,
                            Created = new DateTime(2020, 4, 17, 14, 45, 22, 193, DateTimeKind.Local).AddTicks(8895),
                            Description = @"Corporis omnis iure consequatur facilis.
Sunt provident id voluptas fuga itaque dolor voluptas.
Aperiam magni qui autem voluptas esse molestiae.
Voluptatibus totam quod voluptates vitae ex praesentium.
Eaque odio qui.
Et corrupti aliquid modi dolorem.
Nisi aut et facilis cum qui est ut iure perferendis.
Tenetur repellat eveniet vel numquam voluptate.
Et maxime aut dolor qui.
Qui dolores aperiam maiores debitis perspiciatis dolor animi delectus.",
                            Name = "Incredible Soft Gloves",
                            ShortDescription = "Architecto repudiandae distinctio suscipit temporibus ut.",
                            Updated = new DateTime(2020, 4, 19, 14, 45, 22, 193, DateTimeKind.Local).AddTicks(8953),
                            Uri = "http://heber.com",
                            UserId = 18
                        },
                        new
                        {
                            Id = 11,
                            Created = new DateTime(2020, 4, 17, 14, 45, 22, 197, DateTimeKind.Local).AddTicks(9390),
                            Description = @"Et delectus velit vitae consequatur voluptatem.
Sint dolorem accusamus.
Inventore dolor ea.
Nam voluptas incidunt officiis maiores deserunt dolorem.
Iste architecto iste iste dignissimos totam.
Eligendi quis et illo.
Voluptatem laudantium laudantium est veniam rerum corrupti et quae.
Ad est doloribus tempore debitis consequuntur numquam.
Aspernatur pariatur esse et vero consequatur qui omnis.
Ducimus a quia autem natus consequuntur similique id.",
                            Name = "Practical Granite Computer",
                            ShortDescription = "Autem blanditiis deserunt aut.",
                            Updated = new DateTime(2020, 4, 19, 14, 45, 22, 197, DateTimeKind.Local).AddTicks(9434),
                            Uri = "http://kamron.org",
                            UserId = 16
                        },
                        new
                        {
                            Id = 12,
                            Created = new DateTime(2020, 4, 17, 14, 45, 22, 202, DateTimeKind.Local).AddTicks(5311),
                            Description = @"Est deserunt vitae voluptatum dolorum ea quia.
Cupiditate est blanditiis quia cupiditate.
Eaque hic accusamus temporibus.
Atque nihil quasi tempore placeat possimus architecto asperiores.
Dolores beatae aut non molestias consectetur et vero.
Optio ipsum sequi et consectetur vitae mollitia sint dolores quasi.
Quasi aut unde sit beatae praesentium ratione cumque sint.
Quisquam unde velit laudantium debitis.
Est dolore vel sit eum dolor.
Quia dolorum error.",
                            Name = "Tasty Soft Sausages",
                            ShortDescription = "Incidunt doloribus beatae eum fuga alias eos.",
                            Updated = new DateTime(2020, 4, 19, 14, 45, 22, 202, DateTimeKind.Local).AddTicks(5370),
                            Uri = "http://thea.info",
                            UserId = 24
                        },
                        new
                        {
                            Id = 13,
                            Created = new DateTime(2020, 4, 17, 14, 45, 22, 207, DateTimeKind.Local).AddTicks(6145),
                            Description = @"Neque earum perspiciatis.
Fuga maxime blanditiis ipsam quidem accusamus tempore voluptatem id totam.
Eveniet autem error sint eveniet sint quo quo et explicabo.
Enim autem ex repudiandae accusantium fugit assumenda.
Modi ut provident adipisci asperiores.
Odit sint aliquid quia sequi corporis ut tempore omnis.
Sequi dolores et voluptatem consequuntur qui aut ipsa.
Vitae rem nam sapiente quisquam nulla natus omnis qui dolore.
Consequatur dolor similique optio temporibus alias ea et.
Autem minima animi perferendis qui.",
                            Name = "Handcrafted Wooden Car",
                            ShortDescription = "Saepe dolores et nesciunt assumenda magni corrupti enim repudiandae.",
                            Updated = new DateTime(2020, 4, 19, 14, 45, 22, 207, DateTimeKind.Local).AddTicks(6209),
                            Uri = "https://judd.name",
                            UserId = 7
                        },
                        new
                        {
                            Id = 14,
                            Created = new DateTime(2020, 4, 17, 14, 45, 22, 212, DateTimeKind.Local).AddTicks(5827),
                            Description = @"Vel nihil quia aliquam aut error et commodi consequuntur.
Voluptatum optio sunt.
Officiis et incidunt sapiente tenetur et itaque nostrum voluptatum.
Debitis et expedita ut aliquid ipsa qui.
Placeat ipsa laudantium quia saepe.
Temporibus voluptas sunt aliquam doloremque cum.
Autem modi aut voluptatum temporibus est libero velit.
Vel occaecati hic mollitia vel odit voluptates.
Aut vitae consequatur non rerum quae laboriosam.
Omnis possimus quia fuga quos soluta voluptatem et.",
                            Name = "Generic Cotton Soap",
                            ShortDescription = "Dicta facilis perspiciatis officiis error voluptatem inventore at eius.",
                            Updated = new DateTime(2020, 4, 19, 14, 45, 22, 212, DateTimeKind.Local).AddTicks(5890),
                            Uri = "http://idella.org",
                            UserId = 13
                        },
                        new
                        {
                            Id = 15,
                            Created = new DateTime(2020, 4, 17, 14, 45, 22, 217, DateTimeKind.Local).AddTicks(9081),
                            Description = @"Repellat et rerum nemo ducimus pariatur.
Assumenda est accusantium delectus.
Temporibus eaque magni quaerat voluptatem qui.
Laudantium commodi cumque ducimus voluptas.
Ea qui illum qui voluptatum.
Nam quos quia dolores odio ipsam.
Quam labore laudantium omnis aspernatur sed.
Natus veritatis dolor aspernatur nobis.
Error et eius.
Exercitationem autem sit.",
                            Name = "Incredible Wooden Chicken",
                            ShortDescription = "Dicta quia ea.",
                            Updated = new DateTime(2020, 4, 19, 14, 45, 22, 217, DateTimeKind.Local).AddTicks(9130),
                            Uri = "http://tyler.biz",
                            UserId = 16
                        },
                        new
                        {
                            Id = 16,
                            Created = new DateTime(2020, 4, 17, 14, 45, 22, 223, DateTimeKind.Local).AddTicks(3412),
                            Description = @"Eligendi rerum expedita nemo illo repellat officia.
Repudiandae velit placeat exercitationem unde porro quo.
Ut eos enim sequi velit facilis.
Quos suscipit fugit odit.
Et reiciendis ab iste atque quidem.
Id quam aliquam placeat modi laudantium.
Aut assumenda magnam autem sunt rerum distinctio eveniet.
Odio id nihil ut quae vel dolorem aut.
Saepe sit et itaque commodi adipisci consequatur voluptates enim aut.
Est fugit quae eligendi quas voluptas ea labore perspiciatis ut.",
                            Name = "Incredible Steel Towels",
                            ShortDescription = "Maxime ut voluptatem est illum veritatis.",
                            Updated = new DateTime(2020, 4, 19, 14, 45, 22, 223, DateTimeKind.Local).AddTicks(3490),
                            Uri = "http://eliezer.name",
                            UserId = 6
                        },
                        new
                        {
                            Id = 17,
                            Created = new DateTime(2020, 4, 17, 14, 45, 22, 228, DateTimeKind.Local).AddTicks(4212),
                            Description = @"Minima necessitatibus earum voluptate inventore.
Nam sit nobis sint aut voluptas est qui voluptas minima.
Molestiae et qui et odio ut.
Facere autem placeat dolorum hic ab qui.
Nemo porro velit et qui.
Dolor natus debitis magni veritatis maiores nemo veniam magni sit.
Vitae rem quia pariatur velit eveniet.
Doloribus quia et nobis incidunt ipsa vel harum amet.
Voluptatem ut voluptatem tempora blanditiis et placeat accusamus.
Ullam autem sint enim rem et quam.",
                            Name = "Gorgeous Plastic Bacon",
                            ShortDescription = "Et culpa ea sint.",
                            Updated = new DateTime(2020, 4, 19, 14, 45, 22, 228, DateTimeKind.Local).AddTicks(4280),
                            Uri = "http://francesca.org",
                            UserId = 8
                        },
                        new
                        {
                            Id = 18,
                            Created = new DateTime(2020, 4, 17, 14, 45, 22, 232, DateTimeKind.Local).AddTicks(9385),
                            Description = @"Sit quo placeat molestiae quibusdam nam.
Neque perferendis modi et ut.
Reiciendis saepe animi laudantium quasi perferendis dolor.
Vel accusamus excepturi illo dolor magni.
Voluptatem maxime mollitia a.
Magnam ut soluta unde.
Sed est numquam vitae voluptate rerum labore est eum sed.
Eius odit iste.
Quia illo sint delectus labore quis.
Provident dolores aut.",
                            Name = "Generic Granite Gloves",
                            ShortDescription = "Fuga libero est voluptas odio.",
                            Updated = new DateTime(2020, 4, 19, 14, 45, 22, 232, DateTimeKind.Local).AddTicks(9443),
                            Uri = "https://rebeka.name",
                            UserId = 7
                        },
                        new
                        {
                            Id = 19,
                            Created = new DateTime(2020, 4, 17, 14, 45, 22, 237, DateTimeKind.Local).AddTicks(7800),
                            Description = @"Voluptate molestiae ad ducimus tenetur.
Quia recusandae rerum ipsa rem architecto adipisci.
Porro enim in.
Fugit beatae quasi.
Voluptatem sunt quo quas.
Autem dolorem deserunt.
Sed nesciunt optio aut ipsa delectus molestiae.
Earum perferendis beatae.
Qui adipisci optio magni esse dolores quod earum.
Aliquam necessitatibus quis ut id cumque laborum qui dolores.",
                            Name = "Tasty Cotton Chips",
                            ShortDescription = "Assumenda quae dignissimos ex sint.",
                            Updated = new DateTime(2020, 4, 19, 14, 45, 22, 237, DateTimeKind.Local).AddTicks(7853),
                            Uri = "http://amie.name",
                            UserId = 8
                        },
                        new
                        {
                            Id = 20,
                            Created = new DateTime(2020, 4, 17, 14, 45, 22, 241, DateTimeKind.Local).AddTicks(9419),
                            Description = @"Veritatis asperiores excepturi id.
Eos quis soluta exercitationem nihil.
Maxime eos enim velit nulla odio voluptatem ipsam.
Dignissimos soluta enim culpa eos voluptas dolor.
Et qui qui nostrum qui vitae dolorem nostrum.
Et voluptas rem beatae vel aperiam nisi qui optio.
Est sunt quasi ut dicta suscipit.
Qui vel nobis non animi provident.
Quod sit voluptatum accusantium ea.
Dolor dignissimos sed sunt sunt recusandae voluptas sed harum est.",
                            Name = "Incredible Metal Chair",
                            ShortDescription = "Sit odio ut dolores ut et officia enim a in.",
                            Updated = new DateTime(2020, 4, 19, 14, 45, 22, 241, DateTimeKind.Local).AddTicks(9483),
                            Uri = "http://taryn.net",
                            UserId = 21
                        },
                        new
                        {
                            Id = 21,
                            Created = new DateTime(2020, 4, 17, 14, 45, 22, 246, DateTimeKind.Local).AddTicks(3414),
                            Description = @"Suscipit harum natus.
Aperiam est quo sed ut.
Distinctio sequi quos aut aspernatur minus porro maxime nesciunt amet.
Velit placeat rerum porro.
Cupiditate molestiae alias molestias ut nemo.
Est sed repellat dicta.
Ratione libero harum recusandae sunt blanditiis molestiae nesciunt.
Occaecati aliquam impedit necessitatibus beatae odit.
Eveniet dolores rerum tempore animi harum magnam.
Velit laudantium quo aliquid perferendis.",
                            Name = "Refined Concrete Bacon",
                            ShortDescription = "Cum aspernatur est quasi animi quos omnis quis et.",
                            Updated = new DateTime(2020, 4, 19, 14, 45, 22, 246, DateTimeKind.Local).AddTicks(3468),
                            Uri = "http://imelda.name",
                            UserId = 8
                        },
                        new
                        {
                            Id = 22,
                            Created = new DateTime(2020, 4, 17, 14, 45, 22, 250, DateTimeKind.Local).AddTicks(6015),
                            Description = @"Et consectetur sed non eum.
Fugit velit quae.
Quam aliquid minus odit quod sunt qui.
Voluptas nesciunt veritatis qui deleniti et illo est.
Deserunt quo eaque optio dolore fugit et.
Cupiditate voluptatem corrupti itaque laborum voluptatibus ut voluptatem vitae.
Sed iste cupiditate.
Iure quam labore neque aut incidunt quibusdam.
Qui rem modi natus cupiditate cumque consequatur qui.
Ut dolorem quaerat numquam.",
                            Name = "Unbranded Steel Mouse",
                            ShortDescription = "Expedita omnis incidunt quia dolorem quibusdam.",
                            Updated = new DateTime(2020, 4, 19, 14, 45, 22, 250, DateTimeKind.Local).AddTicks(6064),
                            Uri = "http://victoria.name",
                            UserId = 17
                        },
                        new
                        {
                            Id = 23,
                            Created = new DateTime(2020, 4, 17, 14, 45, 22, 254, DateTimeKind.Local).AddTicks(7063),
                            Description = @"Dolorum blanditiis dicta aut tempore.
Vel similique perferendis.
Ab praesentium sed perferendis voluptatem ut delectus qui.
Suscipit delectus voluptas voluptatum non.
Voluptate repellat ipsam ipsa dolorum ipsum in corrupti autem.
Commodi dicta dolores voluptatem non ea.
Rerum ipsa sit porro quis dolor magni facilis necessitatibus.
Quisquam cumque ea vero voluptatibus.
Ut ut ab dolores.
Qui unde rem aut neque et ut.",
                            Name = "Small Frozen Chair",
                            ShortDescription = "Eum in illo recusandae aut quia et placeat sed.",
                            Updated = new DateTime(2020, 4, 19, 14, 45, 22, 254, DateTimeKind.Local).AddTicks(7116),
                            Uri = "http://karianne.org",
                            UserId = 4
                        },
                        new
                        {
                            Id = 24,
                            Created = new DateTime(2020, 4, 17, 14, 45, 22, 258, DateTimeKind.Local).AddTicks(5240),
                            Description = @"Repellendus sit non vel non accusamus rerum nesciunt et.
Dolore dolores impedit maxime consequuntur.
Incidunt eum inventore maxime.
Voluptas dolore id unde voluptate voluptatem ratione quo.
Consequuntur nam cumque et amet.
Aut occaecati aut sapiente.
Eveniet accusantium dolor officiis itaque ipsa quis asperiores.
Hic similique tempore.
Consectetur sit est.
Fugiat cupiditate quisquam quod quia deserunt sed qui quibusdam.",
                            Name = "Fantastic Soft Pizza",
                            ShortDescription = "Natus voluptatibus illo.",
                            Updated = new DateTime(2020, 4, 19, 14, 45, 22, 258, DateTimeKind.Local).AddTicks(5284),
                            Uri = "http://crystel.biz",
                            UserId = 28
                        },
                        new
                        {
                            Id = 25,
                            Created = new DateTime(2020, 4, 17, 14, 45, 22, 262, DateTimeKind.Local).AddTicks(9470),
                            Description = @"Eos laborum consequatur omnis voluptatem est.
Natus doloribus deserunt molestiae dolorem.
Nemo est ex et hic.
Iusto in nostrum eos hic vel perferendis.
Labore dolorum in.
Quam veniam nemo.
Eius nesciunt earum deserunt unde incidunt facilis mollitia sed nam.
Est maxime accusantium deserunt at aut.
Corporis rerum sunt voluptatum.
Sapiente dolores voluptas quia itaque velit.",
                            Name = "Small Soft Fish",
                            ShortDescription = "Consequatur rerum et autem totam velit ullam.",
                            Updated = new DateTime(2020, 4, 19, 14, 45, 22, 262, DateTimeKind.Local).AddTicks(9533),
                            Uri = "https://uriah.com",
                            UserId = 15
                        },
                        new
                        {
                            Id = 26,
                            Created = new DateTime(2020, 4, 17, 14, 45, 22, 267, DateTimeKind.Local).AddTicks(5661),
                            Description = @"Quam voluptate voluptatem numquam accusantium.
Hic modi reiciendis quam ea maxime quod reiciendis.
Dolor odit nihil sit distinctio expedita.
Perspiciatis consequatur natus qui omnis maxime dolorem.
Tenetur debitis ut.
Ut qui quas voluptates.
Nobis deserunt repellendus et est sit quisquam blanditiis voluptatem ut.
Aspernatur tempora molestias enim.
Repudiandae et saepe expedita harum ipsum quia illo.
Laudantium atque sed est odio est minima velit autem et.",
                            Name = "Unbranded Metal Sausages",
                            ShortDescription = "Officiis animi saepe.",
                            Updated = new DateTime(2020, 4, 19, 14, 45, 22, 267, DateTimeKind.Local).AddTicks(5705),
                            Uri = "http://alena.biz",
                            UserId = 27
                        },
                        new
                        {
                            Id = 27,
                            Created = new DateTime(2020, 4, 17, 14, 45, 22, 271, DateTimeKind.Local).AddTicks(7206),
                            Description = @"Est consequatur ut quas fuga et est aliquam minima sint.
Qui voluptatem sit provident occaecati nulla.
Quia ut ut iusto aut velit possimus ipsam ut perspiciatis.
Optio itaque consequatur dolores rerum id sed recusandae odit.
Eos libero earum sint voluptatibus est qui in quo.
Ipsam sunt aliquid nam hic explicabo nostrum ex quasi.
Enim eveniet et iusto qui in sit deserunt.
Dignissimos esse qui quod.
Ipsam ullam a.
Doloremque excepturi laborum id aliquam est quas id qui cumque.",
                            Name = "Intelligent Fresh Sausages",
                            ShortDescription = "Autem dignissimos omnis et.",
                            Updated = new DateTime(2020, 4, 19, 14, 45, 22, 271, DateTimeKind.Local).AddTicks(7255),
                            Uri = "http://robyn.org",
                            UserId = 14
                        },
                        new
                        {
                            Id = 28,
                            Created = new DateTime(2020, 4, 17, 14, 45, 22, 275, DateTimeKind.Local).AddTicks(7715),
                            Description = @"Tempore omnis odio ut in minus.
Veniam aliquid est dolores quis.
Natus eos sunt facilis laboriosam.
Voluptatibus doloribus ipsam voluptate nisi repellat expedita porro iure similique.
Optio qui doloribus fuga quo.
Ullam maiores voluptas.
Magnam corporis aliquid provident expedita architecto iusto nemo numquam.
Voluptatem voluptatem in hic esse ex qui explicabo enim maxime.
Delectus quo repellat.
Nobis eum nihil quisquam vitae enim expedita perferendis neque qui.",
                            Name = "Generic Granite Sausages",
                            ShortDescription = "Delectus officiis est molestiae eius voluptate ipsum rerum.",
                            Updated = new DateTime(2020, 4, 19, 14, 45, 22, 275, DateTimeKind.Local).AddTicks(7764),
                            Uri = "http://jettie.org",
                            UserId = 27
                        },
                        new
                        {
                            Id = 29,
                            Created = new DateTime(2020, 4, 17, 14, 45, 22, 280, DateTimeKind.Local).AddTicks(273),
                            Description = @"Quia porro qui facere quis officia ex culpa aut est.
Officia dolores expedita distinctio magnam esse modi est.
Ut ea nisi cupiditate est autem.
Delectus sint vel.
Dolores ut dolorem et earum.
Velit dignissimos aut est nostrum porro.
Corrupti qui aperiam maiores.
Sit praesentium illum atque sunt.
Et quis inventore qui quos sint reprehenderit veritatis.
Laboriosam ut aliquid ut.",
                            Name = "Small Concrete Shoes",
                            ShortDescription = "Quisquam qui alias dolor fuga dolor reiciendis.",
                            Updated = new DateTime(2020, 4, 19, 14, 45, 22, 280, DateTimeKind.Local).AddTicks(317),
                            Uri = "http://hosea.org",
                            UserId = 9
                        },
                        new
                        {
                            Id = 30,
                            Created = new DateTime(2020, 4, 17, 14, 45, 22, 286, DateTimeKind.Local).AddTicks(2827),
                            Description = @"Suscipit aliquid provident aut ratione occaecati voluptatem.
Quis ut hic qui eius tempora iste.
Aliquam totam veritatis qui est ea blanditiis aperiam eos nemo.
Aut ut accusantium ex minus molestiae quibusdam qui.
Consequatur tempora quia qui quia voluptatem qui id eum.
Error placeat dolores.
Dolor voluptatem optio eligendi.
Aut eveniet dolores voluptatem quo pariatur sequi corporis nisi voluptates.
Nesciunt quam et placeat.
Accusantium quaerat laborum.",
                            Name = "Licensed Soft Computer",
                            ShortDescription = "Et voluptates quisquam.",
                            Updated = new DateTime(2020, 4, 19, 14, 45, 22, 286, DateTimeKind.Local).AddTicks(3213),
                            Uri = "https://benedict.com",
                            UserId = 6
                        });
                });

            modelBuilder.Entity("Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Rudy_Rohan@yahoo.com",
                            IdentityId = "2",
                            Name = "Annalise"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Abraham_Turcotte21@gmail.com",
                            IdentityId = "3",
                            Name = "Katharina"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Brant_Kassulke45@hotmail.com",
                            IdentityId = "4",
                            Name = "Justus"
                        },
                        new
                        {
                            Id = 4,
                            Email = "Mossie.Lesch@hotmail.com",
                            IdentityId = "5",
                            Name = "Luciano"
                        },
                        new
                        {
                            Id = 5,
                            Email = "Raleigh25@gmail.com",
                            IdentityId = "6",
                            Name = "Emely"
                        },
                        new
                        {
                            Id = 6,
                            Email = "Martina_Johnson16@yahoo.com",
                            IdentityId = "7",
                            Name = "Ross"
                        },
                        new
                        {
                            Id = 7,
                            Email = "Mohammed_Baumbach@hotmail.com",
                            IdentityId = "8",
                            Name = "Hyman"
                        },
                        new
                        {
                            Id = 8,
                            Email = "Yvonne.Little@yahoo.com",
                            IdentityId = "9",
                            Name = "Karelle"
                        },
                        new
                        {
                            Id = 9,
                            Email = "Ally_Farrell@gmail.com",
                            IdentityId = "10",
                            Name = "Laila"
                        },
                        new
                        {
                            Id = 10,
                            Email = "Eulah.Grimes@gmail.com",
                            IdentityId = "11",
                            Name = "Emmy"
                        },
                        new
                        {
                            Id = 11,
                            Email = "Jane_Schuster56@hotmail.com",
                            IdentityId = "12",
                            Name = "Jayne"
                        },
                        new
                        {
                            Id = 12,
                            Email = "Lucy_Kohler68@hotmail.com",
                            IdentityId = "13",
                            Name = "Hilda"
                        },
                        new
                        {
                            Id = 13,
                            Email = "Selina56@hotmail.com",
                            IdentityId = "14",
                            Name = "Enrique"
                        },
                        new
                        {
                            Id = 14,
                            Email = "Liam.Wehner35@gmail.com",
                            IdentityId = "15",
                            Name = "Cyril"
                        },
                        new
                        {
                            Id = 15,
                            Email = "Emanuel31@yahoo.com",
                            IdentityId = "16",
                            Name = "Lloyd"
                        },
                        new
                        {
                            Id = 16,
                            Email = "Michale_Dach14@yahoo.com",
                            IdentityId = "17",
                            Name = "Declan"
                        },
                        new
                        {
                            Id = 17,
                            Email = "Makenna.West31@gmail.com",
                            IdentityId = "18",
                            Name = "Weldon"
                        },
                        new
                        {
                            Id = 18,
                            Email = "Herminia_Kling@yahoo.com",
                            IdentityId = "19",
                            Name = "Mable"
                        },
                        new
                        {
                            Id = 19,
                            Email = "Guillermo.Blanda@gmail.com",
                            IdentityId = "20",
                            Name = "Shawn"
                        },
                        new
                        {
                            Id = 20,
                            Email = "Triston_Beatty@yahoo.com",
                            IdentityId = "21",
                            Name = "Herbert"
                        },
                        new
                        {
                            Id = 21,
                            Email = "Marcos_Cassin@yahoo.com",
                            IdentityId = "22",
                            Name = "Emmanuel"
                        },
                        new
                        {
                            Id = 22,
                            Email = "Chanel41@gmail.com",
                            IdentityId = "23",
                            Name = "Carlee"
                        },
                        new
                        {
                            Id = 23,
                            Email = "Jacklyn.Witting95@gmail.com",
                            IdentityId = "24",
                            Name = "Margaret"
                        },
                        new
                        {
                            Id = 24,
                            Email = "Celine.Kerluke63@yahoo.com",
                            IdentityId = "25",
                            Name = "Ryleigh"
                        },
                        new
                        {
                            Id = 25,
                            Email = "Delfina11@hotmail.com",
                            IdentityId = "26",
                            Name = "Lowell"
                        },
                        new
                        {
                            Id = 26,
                            Email = "Kadin_Wolff@gmail.com",
                            IdentityId = "27",
                            Name = "Clifton"
                        },
                        new
                        {
                            Id = 27,
                            Email = "Elijah.Ebert20@hotmail.com",
                            IdentityId = "28",
                            Name = "Russel"
                        },
                        new
                        {
                            Id = 28,
                            Email = "Isai_Macejkovic@yahoo.com",
                            IdentityId = "29",
                            Name = "Xzavier"
                        },
                        new
                        {
                            Id = 29,
                            Email = "Lemuel93@gmail.com",
                            IdentityId = "30",
                            Name = "Orion"
                        },
                        new
                        {
                            Id = 30,
                            Email = "Wade_Bogisich@hotmail.com",
                            IdentityId = "31",
                            Name = "Matilda"
                        });
                });

            modelBuilder.Entity("Models.Collaborator", b =>
                {
                    b.HasOne("Models.Project", null)
                        .WithMany("Collaborators")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.Highlight", b =>
                {
                    b.HasOne("Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.Project", b =>
                {
                    b.HasOne("Models.User", "User")
                        .WithMany("Projects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
