// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace _4_Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200327162155_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Contributors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Project");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Contributors = "[]",
                            Created = new DateTime(2020, 3, 25, 17, 21, 55, 402, DateTimeKind.Local).AddTicks(7546),
                            Description = "pteoiuaaeoauuuioadiueelmuqeecxtdptenoootreelstuuqioerqtsnateqoeieaxrduqmsaieoeulmlitmsnnatsmoeusceaniueseeadaudnepiqseadoqpiaumipoenoeaedttinusfsmprls",
                            Name = "Unbranded Plastic Fish",
                            ShortDescription = "nsqqsnitarllnmosnecmdqoeddmqaa",
                            Updated = new DateTime(2020, 3, 27, 17, 21, 55, 405, DateTimeKind.Local).AddTicks(6452),
                            Uri = "http://guiseppe.biz",
                            UserId = 11
                        },
                        new
                        {
                            Id = 2,
                            Contributors = "[]",
                            Created = new DateTime(2020, 3, 25, 17, 21, 55, 408, DateTimeKind.Local).AddTicks(5075),
                            Description = "ouadddaosluttstdatheettopioipiimtudsieeuqnauhtsuoaeeammmiamqtotneaenlomtrrnmoomqioopenqmseiainlinufoeemslittiscuatuaeteuauttxviceirutmaauoitqstarieinu",
                            Name = "Incredible Fresh Chips",
                            ShortDescription = "diiambnnsriuitgosainaxsioicfad",
                            Updated = new DateTime(2020, 3, 27, 17, 21, 55, 408, DateTimeKind.Local).AddTicks(5136),
                            Uri = "https://gabriella.biz",
                            UserId = 16
                        },
                        new
                        {
                            Id = 3,
                            Contributors = "[]",
                            Created = new DateTime(2020, 3, 25, 17, 21, 55, 411, DateTimeKind.Local).AddTicks(4290),
                            Description = "qondauvvvoumlmrceelqiqrdvrumrtsupteldiesetemntuootumxecaneuueosomtaequemdosstoatmirsomtnmusiguenudintnubiooiaaersstunssnrtttiigtqeusiateedainolqeovoic",
                            Name = "Unbranded Rubber Table",
                            ShortDescription = "pmetendmmfalmauadndimtnmeeaqqq",
                            Updated = new DateTime(2020, 3, 27, 17, 21, 55, 411, DateTimeKind.Local).AddTicks(4336),
                            Uri = "http://erling.info",
                            UserId = 23
                        },
                        new
                        {
                            Id = 4,
                            Contributors = "[]",
                            Created = new DateTime(2020, 3, 25, 17, 21, 55, 414, DateTimeKind.Local).AddTicks(2027),
                            Description = "taouoeeabeurserlmrvqrosmnqaulladmotuereludunungamesvtiteuiimrluanisltslgtaraldueouneftaumamsqrutsetcmmpqtivupteteuaafudaieuuvbmtaeudsluetdtunelnmaaaso",
                            Name = "Awesome Plastic Hat",
                            ShortDescription = "vomtoeiniuoutlosiiediixepunrtr",
                            Updated = new DateTime(2020, 3, 27, 17, 21, 55, 414, DateTimeKind.Local).AddTicks(2065),
                            Uri = "https://ransom.info",
                            UserId = 24
                        },
                        new
                        {
                            Id = 5,
                            Contributors = "[]",
                            Created = new DateTime(2020, 3, 25, 17, 21, 55, 416, DateTimeKind.Local).AddTicks(9439),
                            Description = "eseqcmtioeoilirtttasiturnleouuivonnitllnatitttdteartiuiotstaaaderiaaqetlilmcimtemiloeilclaiuotouxncsinemiiaibsptnolpdiriqgpudrusmepessiiniqumutetamrae",
                            Name = "Generic Concrete Tuna",
                            ShortDescription = "seqdvaaoitrdaampsasioinludeenb",
                            Updated = new DateTime(2020, 3, 27, 17, 21, 55, 416, DateTimeKind.Local).AddTicks(9476),
                            Uri = "http://dario.org",
                            UserId = 6
                        },
                        new
                        {
                            Id = 6,
                            Contributors = "[]",
                            Created = new DateTime(2020, 3, 25, 17, 21, 55, 419, DateTimeKind.Local).AddTicks(7062),
                            Description = "itiiiesqiuurtcoqtienremssutaoiudrndmletsneatttneqsueemttnnteettqsrireadmgondrrssvpateltlfiatmuiitudiqimeamundmrieitostaembutalartitenetllntamspiouedil",
                            Name = "Rustic Plastic Pants",
                            ShortDescription = "sssidsmvtdiuseoiifnppeofaeuptn",
                            Updated = new DateTime(2020, 3, 27, 17, 21, 55, 419, DateTimeKind.Local).AddTicks(7104),
                            Uri = "https://bryana.org",
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            Contributors = "[]",
                            Created = new DateTime(2020, 3, 25, 17, 21, 55, 422, DateTimeKind.Local).AddTicks(6219),
                            Description = "titaitmiuueeeinfbmtsmssmiuieieeuistvemenenxiaoetoeildatnetooisafustidainuaurtleatplamroeaitncfsssbnoacemeqeeeemoridltdtaeoqortlraiqbetclptmlmeagiraieu",
                            Name = "Small Wooden Soap",
                            ShortDescription = "mnnencpnetrtiaetoiuenlteuesbtr",
                            Updated = new DateTime(2020, 3, 27, 17, 21, 55, 422, DateTimeKind.Local).AddTicks(6266),
                            Uri = "http://clark.net",
                            UserId = 1
                        },
                        new
                        {
                            Id = 8,
                            Contributors = "[]",
                            Created = new DateTime(2020, 3, 25, 17, 21, 55, 425, DateTimeKind.Local).AddTicks(6486),
                            Description = "odesumnefgeeertistiariereqddueslpnineeraerrttrrvcimdremairlransplaouatnostidprcsustdiuuhtuantpirpssaotqdsleadqnuoremalldviiruuoqeiuumrdlsartndaamoiiau",
                            Name = "Rustic Rubber Mouse",
                            ShortDescription = "ceaelinlatuutnluertamsqcsoruit",
                            Updated = new DateTime(2020, 3, 27, 17, 21, 55, 425, DateTimeKind.Local).AddTicks(6540),
                            Uri = "http://raymond.name",
                            UserId = 12
                        },
                        new
                        {
                            Id = 9,
                            Contributors = "[]",
                            Created = new DateTime(2020, 3, 25, 17, 21, 55, 428, DateTimeKind.Local).AddTicks(5592),
                            Description = "qieiorqiieqmrtaoaittceaeoeotqqtuiettntbepaueslqeixluiuclseuroastqiraeoooiscsueiassttceoaupldocseulaueciutxireoqpimttstlanqiasdrsouistustrrairustemeuqe",
                            Name = "Sleek Cotton Table",
                            ShortDescription = "mqmeddslaiieqegmtitlesettvicsr",
                            Updated = new DateTime(2020, 3, 27, 17, 21, 55, 428, DateTimeKind.Local).AddTicks(5646),
                            Uri = "http://anais.info",
                            UserId = 26
                        },
                        new
                        {
                            Id = 10,
                            Contributors = "[]",
                            Created = new DateTime(2020, 3, 25, 17, 21, 55, 431, DateTimeKind.Local).AddTicks(4349),
                            Description = "audettueeiuauilsadlstmialciimaniomaeusadietndvaheeiucnlnodtrsqiuumrateaaucveioipadttsursnestauiodantcesiupensmltdisarauutettmolltatdoaeueoetnseucctals",
                            Name = "Refined Cotton Ball",
                            ShortDescription = "eeuqcoulurnuendleainoisneimneu",
                            Updated = new DateTime(2020, 3, 27, 17, 21, 55, 431, DateTimeKind.Local).AddTicks(4398),
                            Uri = "https://celia.com",
                            UserId = 15
                        },
                        new
                        {
                            Id = 11,
                            Contributors = "[]",
                            Created = new DateTime(2020, 3, 25, 17, 21, 55, 434, DateTimeKind.Local).AddTicks(2892),
                            Description = "seadmaedrailausuisudieepqiaouitutnicdeaasdlsuucfacutturiuheqmmrlaaaseeodtnuusoaemeisuuenfenaubtnhixcdseqraceieaaiieeuesupmteritaqnmoeseotstitetnutedmo",
                            Name = "Rustic Fresh Bike",
                            ShortDescription = "ttmitshlemaseraenamentuomqpgre",
                            Updated = new DateTime(2020, 3, 27, 17, 21, 55, 434, DateTimeKind.Local).AddTicks(2940),
                            Uri = "http://johathan.biz",
                            UserId = 6
                        },
                        new
                        {
                            Id = 12,
                            Contributors = "[]",
                            Created = new DateTime(2020, 3, 25, 17, 21, 55, 437, DateTimeKind.Local).AddTicks(2718),
                            Description = "uddsouselaromtuaptoetepaleaddslanqgtttotaumetrienltruulusumuemetnedeooivinuittotoectdomoeuoeouasiitsouiaeaiooasiotieqnqupctoutiutlqpuoceuutuuposeoansc",
                            Name = "Refined Soft Computer",
                            ShortDescription = "iaqtavuelimfsmsapteobaqeuratue",
                            Updated = new DateTime(2020, 3, 27, 17, 21, 55, 437, DateTimeKind.Local).AddTicks(2763),
                            Uri = "https://fabian.org",
                            UserId = 6
                        },
                        new
                        {
                            Id = 13,
                            Contributors = "[]",
                            Created = new DateTime(2020, 3, 25, 17, 21, 55, 440, DateTimeKind.Local).AddTicks(1939),
                            Description = "embixudqiueitalsmlntreinimtimnstienpuacuisqdsitcteeplsnisterttscvudnimuiersxtnaeranpsxtnmettcaqnuieaiblbtesddlcmtseaauquefuatsfmutooeottbimloeucnsvevo",
                            Name = "Rustic Cotton Mouse",
                            ShortDescription = "ttctvipderaatsrumesipeisiuivlq",
                            Updated = new DateTime(2020, 3, 27, 17, 21, 55, 440, DateTimeKind.Local).AddTicks(1988),
                            Uri = "http://velda.org",
                            UserId = 9
                        },
                        new
                        {
                            Id = 14,
                            Contributors = "[]",
                            Created = new DateTime(2020, 3, 25, 17, 21, 55, 443, DateTimeKind.Local).AddTicks(448),
                            Description = "tiuermetutuovgvqdstrrmteuosnseqeidtouambaneiolmuuinnmiociesommotufohrlelueuieuiddlatecsoittnosisissvaensopmvareucttuqelltprsoopitlmuasuqseacudanimamum",
                            Name = "Small Frozen Pants",
                            ShortDescription = "iluuquvneartiutieaevspeantipsu",
                            Updated = new DateTime(2020, 3, 27, 17, 21, 55, 443, DateTimeKind.Local).AddTicks(485),
                            Uri = "http://marcelino.info",
                            UserId = 14
                        },
                        new
                        {
                            Id = 15,
                            Contributors = "[]",
                            Created = new DateTime(2020, 3, 25, 17, 21, 55, 445, DateTimeKind.Local).AddTicks(9658),
                            Description = "tmeinmnotmauuaeimoaauaspstrsdcatdmsrrtaeienuemltvsuuqertoeertmtscttqlnaflhseeupqueuaafaresqtusamisuctgiauudqtvmaloailuienmoemaoeaeqieloraoaaaadaseiums",
                            Name = "Generic Soft Table",
                            ShortDescription = "tustpirmuaerlotupseraiaeusttti",
                            Updated = new DateTime(2020, 3, 27, 17, 21, 55, 445, DateTimeKind.Local).AddTicks(9704),
                            Uri = "https://solon.org",
                            UserId = 12
                        },
                        new
                        {
                            Id = 16,
                            Contributors = "[]",
                            Created = new DateTime(2020, 3, 25, 17, 21, 55, 448, DateTimeKind.Local).AddTicks(8438),
                            Description = "uatosaptuucsplurtepmutstqdtttiootbmtoummsioiamuirntuueuustaluncvppnatemeuhtlstecttiloaiaxmuaspppiianiseurqelgsaatoonterittatourqospsnnudnlenoenmomsnae",
                            Name = "Tasty Plastic Sausages",
                            ShortDescription = "itaueaodfitirnueoqmcanquqdeaai",
                            Updated = new DateTime(2020, 3, 27, 17, 21, 55, 448, DateTimeKind.Local).AddTicks(8485),
                            Uri = "http://victoria.com",
                            UserId = 15
                        },
                        new
                        {
                            Id = 17,
                            Contributors = "[]",
                            Created = new DateTime(2020, 3, 25, 17, 21, 55, 451, DateTimeKind.Local).AddTicks(6497),
                            Description = "ereuppsnucuuirtiqtoeiiarrtousuiucsaaaqenoeqiaesqoaavpsaiepiunanmisuoumtsuunuieoeaueitauruooitaincteiuedrueouslummisioiieooeteetuguiostoieeriguiemtbesl",
                            Name = "Fantastic Plastic Ball",
                            ShortDescription = "tsteualtitiltemrnemiutdppeqeoe",
                            Updated = new DateTime(2020, 3, 27, 17, 21, 55, 451, DateTimeKind.Local).AddTicks(6531),
                            Uri = "https://gilberto.org",
                            UserId = 10
                        },
                        new
                        {
                            Id = 18,
                            Contributors = "[]",
                            Created = new DateTime(2020, 3, 25, 17, 21, 55, 454, DateTimeKind.Local).AddTicks(5340),
                            Description = "eaaooetsrtiaiemietooeaurltpeuunemmnmsaiaaroplrrmialsrtaersslrotuunnvmamlttatuvrnehetieceibtapiuaosuchspoeeitapfuruaaagoaaeeeoenleeiteureuauuileasiuumi",
                            Name = "Tasty Frozen Fish",
                            ShortDescription = "vguueeesppseatadcudattpsreadan",
                            Updated = new DateTime(2020, 3, 27, 17, 21, 55, 454, DateTimeKind.Local).AddTicks(5383),
                            Uri = "http://jettie.name",
                            UserId = 7
                        },
                        new
                        {
                            Id = 19,
                            Contributors = "[]",
                            Created = new DateTime(2020, 3, 25, 17, 21, 55, 457, DateTimeKind.Local).AddTicks(2996),
                            Description = "osqqaevdagrisubiihlusivoesetpolutaeutiocnusetoeeiiniercsdvleoaamtsleemtbuenctipluouludeiiirssltueteugmaqensidqtdtttmserdaasuuetcxeeiictiemvhrnvqmireiu",
                            Name = "Licensed Rubber Shirt",
                            ShortDescription = "laatorsnupauiualuatlvehtednnqv",
                            Updated = new DateTime(2020, 3, 27, 17, 21, 55, 457, DateTimeKind.Local).AddTicks(3033),
                            Uri = "https://lenna.net",
                            UserId = 4
                        },
                        new
                        {
                            Id = 20,
                            Contributors = "[]",
                            Created = new DateTime(2020, 3, 25, 17, 21, 55, 460, DateTimeKind.Local).AddTicks(739),
                            Description = "tlnasdttulauepqaumetmnispiacdxnetmstiiomsotaqsaieoseoxuauspauaiadsauoamenintmemruneiiuecnrumnieiibltanlueiecdbteimatsqutuorliqurearmiautmeotraiuvneiic",
                            Name = "Licensed Wooden Tuna",
                            ShortDescription = "erooitaeoimctiitouiuleesulsfea",
                            Updated = new DateTime(2020, 3, 27, 17, 21, 55, 460, DateTimeKind.Local).AddTicks(778),
                            Uri = "http://maya.biz",
                            UserId = 20
                        },
                        new
                        {
                            Id = 21,
                            Contributors = "[]",
                            Created = new DateTime(2020, 3, 25, 17, 21, 55, 462, DateTimeKind.Local).AddTicks(6628),
                            Description = "sdsosumoeieimosascaegumtcneaitaeforasctrinvtiatstsoalavimousuinlatsurnnuistuepaldutitluatattiassimiivdoeqstarofmtrdsitptstimediqistleelocieisiuereucee",
                            Name = "Ergonomic Frozen Shoes",
                            ShortDescription = "tsteuntlbouitsqudeemeupeniamue",
                            Updated = new DateTime(2020, 3, 27, 17, 21, 55, 462, DateTimeKind.Local).AddTicks(6678),
                            Uri = "http://john.name",
                            UserId = 9
                        },
                        new
                        {
                            Id = 22,
                            Contributors = "[]",
                            Created = new DateTime(2020, 3, 25, 17, 21, 55, 465, DateTimeKind.Local).AddTicks(6597),
                            Description = "dqlroaaplauueicfuittimamrltembsieilroaveteonentssotunmppiuiineluemtannoudbmeuiusnmittueuimiendgrfevemrduiuspleeelcsisqaerhqoesirtetanliteostmnutioeaio",
                            Name = "Handmade Soft Chair",
                            ShortDescription = "mteeqnotemdmatrrtarqtuulliseaq",
                            Updated = new DateTime(2020, 3, 27, 17, 21, 55, 465, DateTimeKind.Local).AddTicks(6653),
                            Uri = "http://herminio.org",
                            UserId = 11
                        },
                        new
                        {
                            Id = 23,
                            Contributors = "[]",
                            Created = new DateTime(2020, 3, 25, 17, 21, 55, 468, DateTimeKind.Local).AddTicks(5732),
                            Description = "nmietaoadqasoeitttsaqteoadceteetsacreoieimodiernuruasrxueqedltuitdmxouleotsndulnsgnoecuustqtrneltelaolgqrioloqioenmlamnsopimpttldstberresnaattuuetutqa",
                            Name = "Ergonomic Cotton Bike",
                            ShortDescription = "tauutliqluctrdpdaasuueipnueeio",
                            Updated = new DateTime(2020, 3, 27, 17, 21, 55, 468, DateTimeKind.Local).AddTicks(5784),
                            Uri = "http://vincent.name",
                            UserId = 29
                        },
                        new
                        {
                            Id = 24,
                            Contributors = "[]",
                            Created = new DateTime(2020, 3, 25, 17, 21, 55, 471, DateTimeKind.Local).AddTicks(2555),
                            Description = "tutemmrriilaatioliopttciaetutdpuvlnouqqootpmmrtirumpeupuololtetoaetrotuoonudfmtouiosrmdpamiuiitqlniaeomstelalrmiuiucriiinuodaeuiasurniitfmeaunaetsosut",
                            Name = "Ergonomic Concrete Table",
                            ShortDescription = "noadiniiaiooanrldqtoueiusgtett",
                            Updated = new DateTime(2020, 3, 27, 17, 21, 55, 471, DateTimeKind.Local).AddTicks(2602),
                            Uri = "http://garett.org",
                            UserId = 13
                        },
                        new
                        {
                            Id = 25,
                            Contributors = "[]",
                            Created = new DateTime(2020, 3, 25, 17, 21, 55, 474, DateTimeKind.Local).AddTicks(1587),
                            Description = "oeuuteelslbddodutimcottusieoltdatqqmlotednsxcuqniltoqseiscreitltuotiutouueatoeunanietsluilutievdmiaucmxassotouptotsuuabaoeeeoufarslattleptiemieiittrrv",
                            Name = "Refined Concrete Ball",
                            ShortDescription = "ruseteqeudeoxqdieoaleaotesaups",
                            Updated = new DateTime(2020, 3, 27, 17, 21, 55, 474, DateTimeKind.Local).AddTicks(1630),
                            Uri = "https://john.info",
                            UserId = 15
                        },
                        new
                        {
                            Id = 26,
                            Contributors = "[]",
                            Created = new DateTime(2020, 3, 25, 17, 21, 55, 476, DateTimeKind.Local).AddTicks(9514),
                            Description = "ddsnlmbsbtnesurusqtqoomltoeiicdetsatnasrsptassqnarqursneannsiodededieecevusemeutemiatimlqeonselnusmteisuaieeaiamasqduteaeteulubttqicpttnsadpusonuqmaop",
                            Name = "Handcrafted Fresh Hat",
                            ShortDescription = "luadtiauceqemqqlaceadeseupemea",
                            Updated = new DateTime(2020, 3, 27, 17, 21, 55, 476, DateTimeKind.Local).AddTicks(9553),
                            Uri = "http://isabelle.info",
                            UserId = 15
                        },
                        new
                        {
                            Id = 27,
                            Contributors = "[]",
                            Created = new DateTime(2020, 3, 25, 17, 21, 55, 479, DateTimeKind.Local).AddTicks(7144),
                            Description = "sctemaattetusqanseteieoatraaileruimutuasstouetisteousioeeesmauocepopuervuutuiposaodaitntodiunstmioemroautainuqtuetivalduisaenueqtsqelohstpeteieiuvbuic",
                            Name = "Unbranded Steel Pants",
                            ShortDescription = "eielontottsiresiauutotsnteufmm",
                            Updated = new DateTime(2020, 3, 27, 17, 21, 55, 479, DateTimeKind.Local).AddTicks(7197),
                            Uri = "https://skyla.info",
                            UserId = 8
                        },
                        new
                        {
                            Id = 28,
                            Contributors = "[]",
                            Created = new DateTime(2020, 3, 25, 17, 21, 55, 482, DateTimeKind.Local).AddTicks(5882),
                            Description = "ahxoeeuloetuhbinmimteralnpecatriqotatiadtaosdiaouonarestimqeuesamlfsimetiieisactnsdtqeroanilnsqquoonltutivsresttetoauasmassdaieigtsanlnmmaurtlmtuelrst",
                            Name = "Refined Cotton Mouse",
                            ShortDescription = "uoiulteuirtoreuiqteqriintqqqoa",
                            Updated = new DateTime(2020, 3, 27, 17, 21, 55, 482, DateTimeKind.Local).AddTicks(5940),
                            Uri = "http://diego.org",
                            UserId = 4
                        },
                        new
                        {
                            Id = 29,
                            Contributors = "[]",
                            Created = new DateTime(2020, 3, 25, 17, 21, 55, 485, DateTimeKind.Local).AddTicks(3224),
                            Description = "cvsmotsioimtioutstmuqmaiqftaxeuustteeluudrtdoelmuiirvaelgteaiisliratmuietiouiedvnibuosanaqluqmhtuovexeettrlnlamstxaatcduoutuddbotumtuaeittluoieusasati",
                            Name = "Awesome Concrete Pants",
                            ShortDescription = "rheersteqeutaauouuormtutearaqi",
                            Updated = new DateTime(2020, 3, 27, 17, 21, 55, 485, DateTimeKind.Local).AddTicks(3270),
                            Uri = "http://wendy.name",
                            UserId = 10
                        },
                        new
                        {
                            Id = 30,
                            Contributors = "[]",
                            Created = new DateTime(2020, 3, 25, 17, 21, 55, 488, DateTimeKind.Local).AddTicks(3435),
                            Description = "uoeluqrsuutmrumisdseuouoeateeoueuausuaenqltidbnisaexvmiurtasuiiauaarsundbpsteesmtbtaeiuunudeiidadaiunsdeemmaegieemvmeeqssuuepehiqlialoucutdolseeetsotn",
                            Name = "Practical Granite Pants",
                            ShortDescription = "stptaptpoteiaieifrttcrebnpopns",
                            Updated = new DateTime(2020, 3, 27, 17, 21, 55, 488, DateTimeKind.Local).AddTicks(3488),
                            Uri = "http://eli.info",
                            UserId = 29
                        });
                });

            modelBuilder.Entity("Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Donna1@yahoo.com",
                            IdentityId = "2",
                            Name = "Bernadine"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Asia.Conroy@yahoo.com",
                            IdentityId = "3",
                            Name = "Fermin"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Lincoln_Veum75@yahoo.com",
                            IdentityId = "4",
                            Name = "Lempi"
                        },
                        new
                        {
                            Id = 4,
                            Email = "Michael98@hotmail.com",
                            IdentityId = "5",
                            Name = "Crawford"
                        },
                        new
                        {
                            Id = 5,
                            Email = "Letha30@yahoo.com",
                            IdentityId = "6",
                            Name = "Kariane"
                        },
                        new
                        {
                            Id = 6,
                            Email = "Rickie74@yahoo.com",
                            IdentityId = "7",
                            Name = "Allene"
                        },
                        new
                        {
                            Id = 7,
                            Email = "Kamron.Runolfsson@hotmail.com",
                            IdentityId = "8",
                            Name = "Toby"
                        },
                        new
                        {
                            Id = 8,
                            Email = "Andy_Reichel@hotmail.com",
                            IdentityId = "9",
                            Name = "Gay"
                        },
                        new
                        {
                            Id = 9,
                            Email = "Gracie_Herzog@hotmail.com",
                            IdentityId = "10",
                            Name = "Danyka"
                        },
                        new
                        {
                            Id = 10,
                            Email = "Adelia.Prosacco@hotmail.com",
                            IdentityId = "11",
                            Name = "Glenna"
                        },
                        new
                        {
                            Id = 11,
                            Email = "Wyman.Smith@yahoo.com",
                            IdentityId = "12",
                            Name = "Myriam"
                        },
                        new
                        {
                            Id = 12,
                            Email = "Glen_Cummings21@hotmail.com",
                            IdentityId = "13",
                            Name = "Onie"
                        },
                        new
                        {
                            Id = 13,
                            Email = "Maude_Howe@yahoo.com",
                            IdentityId = "14",
                            Name = "Isabell"
                        },
                        new
                        {
                            Id = 14,
                            Email = "Lolita90@gmail.com",
                            IdentityId = "15",
                            Name = "Renee"
                        },
                        new
                        {
                            Id = 15,
                            Email = "Wendy_Bins@hotmail.com",
                            IdentityId = "16",
                            Name = "Marjolaine"
                        },
                        new
                        {
                            Id = 16,
                            Email = "Casandra.Barrows54@gmail.com",
                            IdentityId = "17",
                            Name = "Daniella"
                        },
                        new
                        {
                            Id = 17,
                            Email = "Tyrese.Lang@yahoo.com",
                            IdentityId = "18",
                            Name = "Kasey"
                        },
                        new
                        {
                            Id = 18,
                            Email = "Burdette69@yahoo.com",
                            IdentityId = "19",
                            Name = "Abby"
                        },
                        new
                        {
                            Id = 19,
                            Email = "Orville10@yahoo.com",
                            IdentityId = "20",
                            Name = "German"
                        },
                        new
                        {
                            Id = 20,
                            Email = "Timmy_OKeefe@hotmail.com",
                            IdentityId = "21",
                            Name = "Zelda"
                        },
                        new
                        {
                            Id = 21,
                            Email = "Horace.Olson@hotmail.com",
                            IdentityId = "22",
                            Name = "Talon"
                        },
                        new
                        {
                            Id = 22,
                            Email = "Major.Stamm87@hotmail.com",
                            IdentityId = "23",
                            Name = "Hayden"
                        },
                        new
                        {
                            Id = 23,
                            Email = "Lamont_Ebert@gmail.com",
                            IdentityId = "24",
                            Name = "Luciano"
                        },
                        new
                        {
                            Id = 24,
                            Email = "Garett44@hotmail.com",
                            IdentityId = "25",
                            Name = "Maximillia"
                        },
                        new
                        {
                            Id = 25,
                            Email = "Theodora61@hotmail.com",
                            IdentityId = "26",
                            Name = "Johnathon"
                        },
                        new
                        {
                            Id = 26,
                            Email = "Cade_Miller@hotmail.com",
                            IdentityId = "27",
                            Name = "Skyla"
                        },
                        new
                        {
                            Id = 27,
                            Email = "Aurelio.Rutherford@hotmail.com",
                            IdentityId = "28",
                            Name = "Evalyn"
                        },
                        new
                        {
                            Id = 28,
                            Email = "Ila.Stamm@hotmail.com",
                            IdentityId = "29",
                            Name = "Kameron"
                        },
                        new
                        {
                            Id = 29,
                            Email = "Kyle.Buckridge53@yahoo.com",
                            IdentityId = "30",
                            Name = "Gunner"
                        },
                        new
                        {
                            Id = 30,
                            Email = "Cristobal49@gmail.com",
                            IdentityId = "31",
                            Name = "Salvador"
                        });
                });

            modelBuilder.Entity("Models.Project", b =>
                {
                    b.HasOne("Models.User", "User")
                        .WithMany("Projects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
