// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace _4_Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200422143139_addUserToEmbedLink")]
    partial class addUserToEmbedLink
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.Collaborator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Collaborators");

                    b.HasData(
                        new
                        {
                            Id = 5139,
                            FullName = "Jamey Keebler",
                            ProjectId = 1,
                            Role = "Dynamic Mobility Director"
                        },
                        new
                        {
                            Id = 9116,
                            FullName = "Laura Walter",
                            ProjectId = 1,
                            Role = "Dynamic Paradigm Specialist"
                        },
                        new
                        {
                            Id = 8424,
                            FullName = "Linnea Connelly",
                            ProjectId = 2,
                            Role = "Dynamic Marketing Director"
                        },
                        new
                        {
                            Id = 7450,
                            FullName = "Osborne Goyette",
                            ProjectId = 2,
                            Role = "Regional Web Agent"
                        },
                        new
                        {
                            Id = 822,
                            FullName = "Brent Carroll",
                            ProjectId = 3,
                            Role = "Product Branding Architect"
                        },
                        new
                        {
                            Id = 3641,
                            FullName = "Monroe Borer",
                            ProjectId = 3,
                            Role = "Senior Implementation Engineer"
                        },
                        new
                        {
                            Id = 2420,
                            FullName = "Cesar Schaden",
                            ProjectId = 4,
                            Role = "Central Intranet Administrator"
                        },
                        new
                        {
                            Id = 2982,
                            FullName = "Judd Pfannerstill",
                            ProjectId = 4,
                            Role = "Dynamic Functionality Agent"
                        },
                        new
                        {
                            Id = 2232,
                            FullName = "Heath Turner",
                            ProjectId = 5,
                            Role = "Principal Optimization Designer"
                        },
                        new
                        {
                            Id = 2334,
                            FullName = "Brooks Spencer",
                            ProjectId = 5,
                            Role = "Global Infrastructure Orchestrator"
                        },
                        new
                        {
                            Id = 2294,
                            FullName = "Lavern Waelchi",
                            ProjectId = 6,
                            Role = "Central Configuration Planner"
                        },
                        new
                        {
                            Id = 1918,
                            FullName = "Nya Kautzer",
                            ProjectId = 6,
                            Role = "Human Usability Strategist"
                        },
                        new
                        {
                            Id = 5740,
                            FullName = "Destin Ebert",
                            ProjectId = 7,
                            Role = "Human Brand Executive"
                        },
                        new
                        {
                            Id = 1968,
                            FullName = "Irwin Stracke",
                            ProjectId = 7,
                            Role = "Dynamic Security Engineer"
                        },
                        new
                        {
                            Id = 5565,
                            FullName = "Gaetano Feeney",
                            ProjectId = 8,
                            Role = "Customer Configuration Associate"
                        },
                        new
                        {
                            Id = 4206,
                            FullName = "Mavis Moore",
                            ProjectId = 8,
                            Role = "Corporate Functionality Strategist"
                        },
                        new
                        {
                            Id = 4895,
                            FullName = "Rico Olson",
                            ProjectId = 9,
                            Role = "Direct Division Analyst"
                        },
                        new
                        {
                            Id = 4658,
                            FullName = "Evert Kovacek",
                            ProjectId = 9,
                            Role = "Chief Group Manager"
                        },
                        new
                        {
                            Id = 3272,
                            FullName = "Francisca Bergstrom",
                            ProjectId = 10,
                            Role = "Legacy Tactics Executive"
                        },
                        new
                        {
                            Id = 7516,
                            FullName = "Abdul Lakin",
                            ProjectId = 10,
                            Role = "Dynamic Interactions Analyst"
                        },
                        new
                        {
                            Id = 3488,
                            FullName = "Lowell Walker",
                            ProjectId = 11,
                            Role = "Regional Division Engineer"
                        },
                        new
                        {
                            Id = 3558,
                            FullName = "Guiseppe Abbott",
                            ProjectId = 11,
                            Role = "Future Markets Engineer"
                        },
                        new
                        {
                            Id = 4408,
                            FullName = "Aubree Zulauf",
                            ProjectId = 12,
                            Role = "National Accounts Producer"
                        },
                        new
                        {
                            Id = 7838,
                            FullName = "Libby Wilkinson",
                            ProjectId = 12,
                            Role = "Principal Integration Analyst"
                        },
                        new
                        {
                            Id = 9931,
                            FullName = "Marisa Heller",
                            ProjectId = 13,
                            Role = "Central Group Engineer"
                        },
                        new
                        {
                            Id = 4667,
                            FullName = "Retha Walker",
                            ProjectId = 13,
                            Role = "Corporate Accounts Assistant"
                        },
                        new
                        {
                            Id = 5803,
                            FullName = "Baby Torp",
                            ProjectId = 14,
                            Role = "Dynamic Intranet Supervisor"
                        },
                        new
                        {
                            Id = 2374,
                            FullName = "Athena Wunsch",
                            ProjectId = 14,
                            Role = "Internal Paradigm Engineer"
                        },
                        new
                        {
                            Id = 1173,
                            FullName = "Giovanna Flatley",
                            ProjectId = 15,
                            Role = "Legacy Accountability Specialist"
                        },
                        new
                        {
                            Id = 5364,
                            FullName = "Flavie Jenkins",
                            ProjectId = 15,
                            Role = "District Identity Consultant"
                        },
                        new
                        {
                            Id = 9017,
                            FullName = "Sadie Yost",
                            ProjectId = 16,
                            Role = "Legacy Accounts Designer"
                        },
                        new
                        {
                            Id = 3207,
                            FullName = "Don Hartmann",
                            ProjectId = 16,
                            Role = "Dynamic Accounts Technician"
                        },
                        new
                        {
                            Id = 8611,
                            FullName = "Kelvin Bashirian",
                            ProjectId = 17,
                            Role = "Chief Mobility Liaison"
                        },
                        new
                        {
                            Id = 4991,
                            FullName = "Cecile Hoppe",
                            ProjectId = 17,
                            Role = "Direct Identity Supervisor"
                        },
                        new
                        {
                            Id = 121,
                            FullName = "Melany Weissnat",
                            ProjectId = 18,
                            Role = "Investor Web Administrator"
                        },
                        new
                        {
                            Id = 3959,
                            FullName = "Brisa Reinger",
                            ProjectId = 18,
                            Role = "Direct Paradigm Producer"
                        },
                        new
                        {
                            Id = 266,
                            FullName = "Jennings Hammes",
                            ProjectId = 19,
                            Role = "District Optimization Supervisor"
                        },
                        new
                        {
                            Id = 9246,
                            FullName = "Tia Monahan",
                            ProjectId = 19,
                            Role = "Customer Interactions Specialist"
                        },
                        new
                        {
                            Id = 2536,
                            FullName = "Laurianne Miller",
                            ProjectId = 20,
                            Role = "Product Factors Manager"
                        },
                        new
                        {
                            Id = 3922,
                            FullName = "Ramon Kuhic",
                            ProjectId = 20,
                            Role = "Principal Mobility Associate"
                        },
                        new
                        {
                            Id = 6142,
                            FullName = "Marty Nicolas",
                            ProjectId = 21,
                            Role = "Chief Data Technician"
                        },
                        new
                        {
                            Id = 9353,
                            FullName = "Newell Frami",
                            ProjectId = 21,
                            Role = "Product Interactions Engineer"
                        },
                        new
                        {
                            Id = 8157,
                            FullName = "Araceli Ortiz",
                            ProjectId = 22,
                            Role = "National Directives Architect"
                        },
                        new
                        {
                            Id = 4167,
                            FullName = "Hipolito Schowalter",
                            ProjectId = 22,
                            Role = "Investor Identity Supervisor"
                        },
                        new
                        {
                            Id = 8021,
                            FullName = "Blaze Dietrich",
                            ProjectId = 23,
                            Role = "Global Assurance Analyst"
                        },
                        new
                        {
                            Id = 2355,
                            FullName = "Annalise Roob",
                            ProjectId = 23,
                            Role = "Future Data Assistant"
                        },
                        new
                        {
                            Id = 3914,
                            FullName = "Zackery Champlin",
                            ProjectId = 24,
                            Role = "Principal Web Liaison"
                        },
                        new
                        {
                            Id = 729,
                            FullName = "Trent Parker",
                            ProjectId = 24,
                            Role = "National Applications Facilitator"
                        },
                        new
                        {
                            Id = 5340,
                            FullName = "Alfonzo Nolan",
                            ProjectId = 25,
                            Role = "Lead Infrastructure Specialist"
                        },
                        new
                        {
                            Id = 2540,
                            FullName = "Yazmin Hahn",
                            ProjectId = 25,
                            Role = "Investor Research Technician"
                        },
                        new
                        {
                            Id = 4478,
                            FullName = "Hans Barton",
                            ProjectId = 26,
                            Role = "Legacy Security Facilitator"
                        },
                        new
                        {
                            Id = 5085,
                            FullName = "Keara Gleason",
                            ProjectId = 26,
                            Role = "Internal Usability Officer"
                        },
                        new
                        {
                            Id = 3237,
                            FullName = "Ismael Schaden",
                            ProjectId = 27,
                            Role = "Dynamic Infrastructure Architect"
                        },
                        new
                        {
                            Id = 3571,
                            FullName = "Jamir Olson",
                            ProjectId = 27,
                            Role = "National Metrics Developer"
                        },
                        new
                        {
                            Id = 8641,
                            FullName = "Colton Ledner",
                            ProjectId = 28,
                            Role = "District Solutions Assistant"
                        },
                        new
                        {
                            Id = 5017,
                            FullName = "Pedro Stracke",
                            ProjectId = 28,
                            Role = "District Operations Manager"
                        },
                        new
                        {
                            Id = 1119,
                            FullName = "Ethan Steuber",
                            ProjectId = 29,
                            Role = "Internal Creative Agent"
                        },
                        new
                        {
                            Id = 6040,
                            FullName = "Mariano Bernier",
                            ProjectId = 29,
                            Role = "Central Assurance Executive"
                        },
                        new
                        {
                            Id = 5183,
                            FullName = "Laney Kertzmann",
                            ProjectId = 30,
                            Role = "Human Integration Technician"
                        },
                        new
                        {
                            Id = 148,
                            FullName = "Bobby Kassulke",
                            ProjectId = 30,
                            Role = "National Accountability Facilitator"
                        });
                });

            modelBuilder.Entity("Models.EmbeddedProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("EmbeddedProject");
                });

            modelBuilder.Entity("Models.Highlight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Highlight");
                });

            modelBuilder.Entity("Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Project");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2020, 4, 20, 16, 31, 38, 365, DateTimeKind.Local).AddTicks(1487),
                            Description = @"Sit quo quo possimus sint quas.
Excepturi dolorem aut minima officia.
Perspiciatis ullam dolorem omnis sunt tempore veritatis asperiores.
Reprehenderit quidem quia omnis voluptatem voluptatem.
Eius consequatur hic enim.
Voluptatum modi consequatur sunt dignissimos laborum voluptas asperiores aut sint.
Aut rem rerum dolorem hic quidem est ab.
Praesentium sed quia.
Iusto delectus et.
Nisi hic architecto voluptas.",
                            Name = "Licensed Metal Keyboard",
                            ShortDescription = "Dolorem et architecto ex tempore.",
                            Updated = new DateTime(2020, 4, 22, 16, 31, 38, 374, DateTimeKind.Local).AddTicks(6754),
                            Uri = "http://bette.info",
                            UserId = 4
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2020, 4, 20, 16, 31, 38, 381, DateTimeKind.Local).AddTicks(4144),
                            Description = @"Odio beatae ipsam voluptas eius culpa dicta ut dolorem et.
Ut minus expedita deleniti consequatur tempore et vero voluptas vel.
Est debitis placeat mollitia sapiente beatae maiores.
Laudantium eos nulla voluptatem asperiores rerum non voluptas quia consequatur.
Nihil ratione reprehenderit consequuntur ipsum dolorum sit neque eligendi unde.
Illum harum perspiciatis officiis et.
Culpa fuga et consequatur repudiandae veniam.
Vitae inventore qui distinctio mollitia odio fugiat non corrupti at.
Quam aliquam facere in reiciendis rerum repudiandae exercitationem suscipit fugit.
Non id quia.",
                            Name = "Tasty Metal Shoes",
                            ShortDescription = "Quos voluptatem et placeat voluptatibus molestias.",
                            Updated = new DateTime(2020, 4, 22, 16, 31, 38, 381, DateTimeKind.Local).AddTicks(4239),
                            Uri = "https://angelina.biz",
                            UserId = 8
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2020, 4, 20, 16, 31, 38, 389, DateTimeKind.Local).AddTicks(3553),
                            Description = @"Magnam porro illum sit dolor officia qui.
Soluta alias est tempore.
Dolorum hic at.
Nulla voluptatibus ut.
Rerum similique doloremque id.
Ducimus iste fugiat impedit praesentium earum officia ut ipsa.
Ullam impedit et perferendis libero ad consequatur.
Pariatur beatae necessitatibus necessitatibus repudiandae.
Consequatur enim illo illum quam corporis ratione.
Deserunt voluptates qui eveniet nisi aut ut nihil vitae.",
                            Name = "Ergonomic Steel Pants",
                            ShortDescription = "In suscipit iste sit velit delectus officiis officiis.",
                            Updated = new DateTime(2020, 4, 22, 16, 31, 38, 389, DateTimeKind.Local).AddTicks(3629),
                            Uri = "https://hellen.com",
                            UserId = 16
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2020, 4, 20, 16, 31, 38, 395, DateTimeKind.Local).AddTicks(6131),
                            Description = @"Ut nihil consectetur necessitatibus est molestiae quod totam.
Sed cupiditate officiis assumenda non quo quisquam.
Asperiores ratione ipsam culpa.
Cum vero dicta.
Unde dolorem quo est recusandae non qui aliquam beatae enim.
Illum enim illum quo et.
Non necessitatibus explicabo.
Earum ullam deserunt.
Nam eum et.
Magnam doloremque sit.",
                            Name = "Handcrafted Frozen Towels",
                            ShortDescription = "Dolorem autem sunt et ut amet deserunt nostrum sint.",
                            Updated = new DateTime(2020, 4, 22, 16, 31, 38, 395, DateTimeKind.Local).AddTicks(6205),
                            Uri = "http://elta.biz",
                            UserId = 3
                        },
                        new
                        {
                            Id = 5,
                            Created = new DateTime(2020, 4, 20, 16, 31, 38, 405, DateTimeKind.Local).AddTicks(7294),
                            Description = @"Quo delectus laudantium ut asperiores nulla.
Et dolore in ut aspernatur laboriosam consectetur.
Labore voluptatem perferendis corrupti odio voluptatem ut qui accusantium.
Aut qui sunt minus modi.
Reiciendis et voluptas aliquid veniam error commodi consequatur.
Assumenda impedit eum voluptas sint quos hic voluptas accusantium voluptas.
Enim velit necessitatibus numquam deleniti.
Odio libero consectetur voluptatem occaecati magni voluptatem accusamus nostrum.
Sunt quo ut cum distinctio quia quas.
Iste pariatur illum odit aut at aliquam et.",
                            Name = "Incredible Metal Gloves",
                            ShortDescription = "Debitis qui dolor est unde accusamus.",
                            Updated = new DateTime(2020, 4, 22, 16, 31, 38, 405, DateTimeKind.Local).AddTicks(7376),
                            Uri = "https://kennith.info",
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            Created = new DateTime(2020, 4, 20, 16, 31, 38, 415, DateTimeKind.Local).AddTicks(7628),
                            Description = @"Ea blanditiis et saepe autem corrupti atque.
Est odit eligendi eius distinctio et consequatur sit.
Suscipit consequatur qui quisquam ratione voluptatum molestias asperiores accusantium.
Vitae unde delectus officia repellendus nihil reiciendis quos ea deleniti.
Deleniti voluptas culpa possimus amet quis sunt iure necessitatibus labore.
Quibusdam eum veniam quo quibusdam at.
Voluptatibus sed ut aliquid.
Ea aut quisquam occaecati et quibusdam soluta.
Est pariatur hic vero.
Accusamus delectus a amet.",
                            Name = "Generic Metal Bike",
                            ShortDescription = "Id dolores qui et facere eos.",
                            Updated = new DateTime(2020, 4, 22, 16, 31, 38, 415, DateTimeKind.Local).AddTicks(7697),
                            Uri = "http://brandon.net",
                            UserId = 26
                        },
                        new
                        {
                            Id = 7,
                            Created = new DateTime(2020, 4, 20, 16, 31, 38, 425, DateTimeKind.Local).AddTicks(1468),
                            Description = @"Perferendis consequuntur et dolor expedita.
Assumenda sit deserunt quia aut aut.
Debitis nihil rem molestiae necessitatibus magnam quibusdam cumque ullam numquam.
Est ut culpa numquam fugiat ipsum iste vero enim.
Recusandae minus repellat eligendi nemo quos.
Labore aut non fuga qui aut.
Debitis id cumque labore accusantium.
Distinctio porro voluptates qui ea nemo rerum.
Aliquid nihil est dolore sed praesentium earum.
Rem ut culpa omnis vel laudantium quis quis.",
                            Name = "Rustic Plastic Shirt",
                            ShortDescription = "Hic perspiciatis voluptatem suscipit.",
                            Updated = new DateTime(2020, 4, 22, 16, 31, 38, 425, DateTimeKind.Local).AddTicks(1549),
                            Uri = "http://ara.name",
                            UserId = 27
                        },
                        new
                        {
                            Id = 8,
                            Created = new DateTime(2020, 4, 20, 16, 31, 38, 430, DateTimeKind.Local).AddTicks(2907),
                            Description = @"Qui perspiciatis quis repellat.
Eos rerum qui minima vel quis ut.
Amet magni totam expedita ut.
Velit molestiae dolorum quis.
Voluptas similique eius quia tenetur sit.
Nulla harum est officiis non hic.
Voluptatem occaecati in nihil aut repellendus nam.
Repellat voluptatem explicabo alias.
Error corrupti et temporibus velit quaerat fugiat incidunt.
Rerum voluptas et.",
                            Name = "Refined Metal Bacon",
                            ShortDescription = "Delectus odio porro mollitia ipsam sed sint architecto fugit soluta.",
                            Updated = new DateTime(2020, 4, 22, 16, 31, 38, 430, DateTimeKind.Local).AddTicks(2960),
                            Uri = "http://jane.biz",
                            UserId = 24
                        },
                        new
                        {
                            Id = 9,
                            Created = new DateTime(2020, 4, 20, 16, 31, 38, 433, DateTimeKind.Local).AddTicks(4553),
                            Description = @"Quasi accusantium tenetur libero pariatur ex alias.
Tempore tempore sed aliquid fugit aut vel architecto veritatis qui.
Deleniti in quo saepe.
Officia ducimus consequatur consequatur et officia.
Ipsa distinctio totam sunt id cum minima fugit dicta.
Nam rerum provident in quisquam alias et consequatur.
Unde soluta similique explicabo ipsum ut dolores totam.
Ea perspiciatis asperiores.
Dicta repudiandae architecto est facilis enim architecto qui repellendus.
Dolores voluptas minus adipisci ea vitae accusamus ducimus.",
                            Name = "Sleek Soft Towels",
                            ShortDescription = "Velit velit eaque.",
                            Updated = new DateTime(2020, 4, 22, 16, 31, 38, 433, DateTimeKind.Local).AddTicks(4600),
                            Uri = "https://mohamed.name",
                            UserId = 4
                        },
                        new
                        {
                            Id = 10,
                            Created = new DateTime(2020, 4, 20, 16, 31, 38, 439, DateTimeKind.Local).AddTicks(3547),
                            Description = @"Velit quo ut porro.
Iste et voluptas doloremque ea quos minus aliquam voluptas.
Et sit iusto ipsa est eum non a sed quibusdam.
Quae quo id quia nisi aut.
Amet qui asperiores mollitia quae itaque.
Maxime possimus quo dicta occaecati laudantium nesciunt ad.
Ipsa labore eos.
Eum dolorem doloribus possimus consequatur.
Nisi excepturi omnis quisquam voluptates perferendis sint quaerat quasi dolor.
Fugiat veniam et ea doloremque fuga autem accusamus perferendis suscipit.",
                            Name = "Incredible Plastic Soap",
                            ShortDescription = "Est quod natus rerum deleniti.",
                            Updated = new DateTime(2020, 4, 22, 16, 31, 38, 439, DateTimeKind.Local).AddTicks(3605),
                            Uri = "http://jaquan.name",
                            UserId = 14
                        },
                        new
                        {
                            Id = 11,
                            Created = new DateTime(2020, 4, 20, 16, 31, 38, 445, DateTimeKind.Local).AddTicks(895),
                            Description = @"Mollitia consequuntur delectus aperiam.
Architecto alias sed dicta explicabo fugit quia tenetur commodi saepe.
Sed et rerum doloribus qui quae id eaque neque.
Provident voluptas et.
Qui placeat et nesciunt et minima et officia.
Quibusdam perferendis magni non cum et.
Recusandae fugit repellendus voluptas nesciunt.
Ut animi ut unde iure molestiae officiis et ut neque.
Autem excepturi commodi sapiente autem praesentium et.
Laborum ipsum sunt reiciendis blanditiis quo veritatis velit.",
                            Name = "Generic Concrete Soap",
                            ShortDescription = "Sunt esse illo omnis omnis id in rerum dolorum.",
                            Updated = new DateTime(2020, 4, 22, 16, 31, 38, 445, DateTimeKind.Local).AddTicks(952),
                            Uri = "https://lucius.info",
                            UserId = 17
                        },
                        new
                        {
                            Id = 12,
                            Created = new DateTime(2020, 4, 20, 16, 31, 38, 448, DateTimeKind.Local).AddTicks(5513),
                            Description = @"Perspiciatis fugiat neque voluptatem reprehenderit eos expedita ipsum aut.
Consequatur quaerat fuga vitae quo voluptas sint.
Vel quia aut.
Qui voluptates delectus voluptatem quia odit est mollitia eveniet.
Fugiat magni repudiandae alias eveniet ratione velit tenetur.
Rerum tempore aut autem qui sit sed rerum natus.
Facilis est dolores quod minus aut aliquam.
Architecto sapiente unde dignissimos quas.
Sit molestiae dolores ipsum quo molestiae consequatur expedita.
Ea tempora dolores vel sed dolorem corporis rerum totam.",
                            Name = "Handmade Granite Ball",
                            ShortDescription = "Aut magnam ut optio.",
                            Updated = new DateTime(2020, 4, 22, 16, 31, 38, 448, DateTimeKind.Local).AddTicks(5563),
                            Uri = "http://sibyl.com",
                            UserId = 14
                        },
                        new
                        {
                            Id = 13,
                            Created = new DateTime(2020, 4, 20, 16, 31, 38, 454, DateTimeKind.Local).AddTicks(2188),
                            Description = @"Numquam odio dolorem commodi laborum quo occaecati commodi non magni.
Doloribus et omnis excepturi animi.
Eos rem assumenda voluptatem.
Minima non qui.
Qui odit asperiores quisquam repellendus.
Voluptatem accusamus ratione repellendus delectus qui quas.
Dolor ad ut.
Quisquam voluptatem eaque.
Debitis culpa autem molestias autem similique tempore dolores neque quidem.
Suscipit maiores velit quis quia ut minus libero asperiores harum.",
                            Name = "Generic Fresh Pants",
                            ShortDescription = "Harum maxime harum commodi maiores ipsa ut dolore.",
                            Updated = new DateTime(2020, 4, 22, 16, 31, 38, 454, DateTimeKind.Local).AddTicks(2260),
                            Uri = "http://chauncey.org",
                            UserId = 5
                        },
                        new
                        {
                            Id = 14,
                            Created = new DateTime(2020, 4, 20, 16, 31, 38, 463, DateTimeKind.Local).AddTicks(7871),
                            Description = @"Minima qui placeat adipisci perferendis fuga sit corrupti ipsum quia.
Et sit nobis doloribus deserunt.
Nostrum ratione hic.
Officiis aut qui.
Deserunt repudiandae eum fugiat explicabo dolor sit a.
Et officia et et et.
Corporis quaerat praesentium.
Et eos non natus.
Ut velit sint dicta laudantium debitis voluptate dolores dolorem.
Quam impedit et et beatae rerum amet.",
                            Name = "Licensed Concrete Shirt",
                            ShortDescription = "Ab dolorum in tempore et tempore ipsa facilis temporibus velit.",
                            Updated = new DateTime(2020, 4, 22, 16, 31, 38, 463, DateTimeKind.Local).AddTicks(7949),
                            Uri = "https://brenna.biz",
                            UserId = 23
                        },
                        new
                        {
                            Id = 15,
                            Created = new DateTime(2020, 4, 20, 16, 31, 38, 471, DateTimeKind.Local).AddTicks(453),
                            Description = @"Eveniet distinctio aspernatur dolores ea.
Blanditiis facere ut velit qui aut est eum.
Molestiae adipisci nesciunt earum quam.
Tenetur nulla ipsa illum sunt asperiores commodi velit architecto.
Ea corrupti ea.
Veniam sunt qui est.
Earum sint aut voluptatum est voluptas sit accusantium voluptatum sed.
Tempora velit deserunt molestiae earum.
Illo cum ipsam nam explicabo iste nesciunt nesciunt aperiam.
Dolore quia perferendis laboriosam maxime.",
                            Name = "Fantastic Plastic Chair",
                            ShortDescription = "Reiciendis voluptatum rerum rerum quis reprehenderit reiciendis.",
                            Updated = new DateTime(2020, 4, 22, 16, 31, 38, 471, DateTimeKind.Local).AddTicks(512),
                            Uri = "https://vita.info",
                            UserId = 17
                        },
                        new
                        {
                            Id = 16,
                            Created = new DateTime(2020, 4, 20, 16, 31, 38, 475, DateTimeKind.Local).AddTicks(1727),
                            Description = @"Saepe non labore laudantium aperiam est suscipit ullam pariatur commodi.
Ipsam laborum non recusandae qui praesentium velit omnis porro.
Sed atque repellat ducimus nam cumque.
Optio sed saepe vel ut sunt.
Voluptatem delectus unde nemo ut ipsum.
Fuga qui explicabo illo dolor qui aut ratione.
Laudantium tempora explicabo excepturi omnis dignissimos.
Sit quis architecto non.
Est totam rem delectus cupiditate aut laborum.
Repudiandae necessitatibus culpa perspiciatis facere quos eveniet ut reprehenderit.",
                            Name = "Handcrafted Soft Bacon",
                            ShortDescription = "Magnam iusto unde omnis molestiae voluptatem aliquam culpa facilis officiis.",
                            Updated = new DateTime(2020, 4, 22, 16, 31, 38, 475, DateTimeKind.Local).AddTicks(1778),
                            Uri = "https://viviane.org",
                            UserId = 5
                        },
                        new
                        {
                            Id = 17,
                            Created = new DateTime(2020, 4, 20, 16, 31, 38, 478, DateTimeKind.Local).AddTicks(9608),
                            Description = @"Fugit dolorum sunt quaerat ut ea nostrum excepturi sunt facilis.
Possimus quis unde laboriosam fuga corrupti dolorem.
Ab accusamus eaque quia quo earum.
Id magni eum tenetur nobis ullam.
Sint repellendus veniam corporis et et architecto quaerat.
Vero molestias nihil dolorem ea.
Iure et ducimus quasi facere.
Odit architecto ullam.
Ipsam rerum dolorum neque consequuntur et.
Dolore vitae est omnis illo quia eos et quam autem.",
                            Name = "Unbranded Concrete Car",
                            ShortDescription = "Sit vel consequatur fugit aut voluptate quod.",
                            Updated = new DateTime(2020, 4, 22, 16, 31, 38, 478, DateTimeKind.Local).AddTicks(9673),
                            Uri = "https://justice.org",
                            UserId = 22
                        },
                        new
                        {
                            Id = 18,
                            Created = new DateTime(2020, 4, 20, 16, 31, 38, 488, DateTimeKind.Local).AddTicks(586),
                            Description = @"Maiores molestiae enim sit qui explicabo dolores labore.
Blanditiis maxime qui similique sit qui officia.
Suscipit ut quas saepe.
Quis velit repellendus numquam quam est.
Nisi cumque iusto.
Illo quasi qui unde ut.
Cumque totam rerum ut omnis quis sint voluptas velit saepe.
Laudantium numquam velit et illum et iste aut ut labore.
Corrupti consequuntur sed possimus nemo eius excepturi quaerat.
Eaque magnam consequatur sed.",
                            Name = "Awesome Metal Shirt",
                            ShortDescription = "Hic numquam illum.",
                            Updated = new DateTime(2020, 4, 22, 16, 31, 38, 488, DateTimeKind.Local).AddTicks(653),
                            Uri = "http://jodie.name",
                            UserId = 17
                        },
                        new
                        {
                            Id = 19,
                            Created = new DateTime(2020, 4, 20, 16, 31, 38, 495, DateTimeKind.Local).AddTicks(4133),
                            Description = @"Atque accusantium praesentium labore similique voluptas odio nam est accusantium.
Illum veritatis quibusdam et exercitationem sit voluptatem impedit debitis numquam.
Officiis accusamus accusamus veniam id veniam delectus accusamus distinctio.
Recusandae quia enim minima omnis ad est ut.
Qui facilis excepturi ab magni sequi voluptatem.
Aut ipsa vero quae voluptatem nam rerum sequi deserunt.
Quis aut sequi cumque vero.
Magnam aut id cupiditate repellendus.
Illo praesentium ea ad harum sed commodi.
Id magni quo cupiditate asperiores eum et nobis et.",
                            Name = "Small Soft Mouse",
                            ShortDescription = "Harum consequuntur dolorem et ea dolore ducimus rerum.",
                            Updated = new DateTime(2020, 4, 22, 16, 31, 38, 495, DateTimeKind.Local).AddTicks(4202),
                            Uri = "https://domenic.info",
                            UserId = 29
                        },
                        new
                        {
                            Id = 20,
                            Created = new DateTime(2020, 4, 20, 16, 31, 38, 506, DateTimeKind.Local).AddTicks(7421),
                            Description = @"Iusto maiores in est ipsa aperiam iusto temporibus est harum.
Iure et nihil accusantium.
Error ut beatae saepe distinctio consequatur ratione.
Fugit eum placeat.
Numquam sit atque porro numquam unde.
Voluptas ea repellat sunt fuga adipisci suscipit.
Ad dolore vero illum dolor omnis.
Ut maiores suscipit id ipsam quasi quo.
In numquam quis sit in.
Ratione odio quia vitae ratione amet sequi similique eligendi.",
                            Name = "Gorgeous Cotton Shoes",
                            ShortDescription = "Cumque quia aut officiis consequatur aliquam.",
                            Updated = new DateTime(2020, 4, 22, 16, 31, 38, 506, DateTimeKind.Local).AddTicks(7499),
                            Uri = "https://caden.net",
                            UserId = 16
                        },
                        new
                        {
                            Id = 21,
                            Created = new DateTime(2020, 4, 20, 16, 31, 38, 515, DateTimeKind.Local).AddTicks(5754),
                            Description = @"Laborum ut corrupti alias et quam.
Laboriosam quia omnis rerum consequuntur.
Soluta id aperiam in molestiae libero nostrum aut et.
Explicabo delectus provident voluptatem sed porro commodi rerum ut facilis.
Natus nulla expedita.
Sunt ratione sit fugit.
Error sit placeat repellat sunt ad sed.
Sed fugit non.
Impedit dolore reprehenderit eaque sed aut.
Fuga vel illum tempore.",
                            Name = "Generic Soft Hat",
                            ShortDescription = "Placeat quia necessitatibus autem reprehenderit laboriosam.",
                            Updated = new DateTime(2020, 4, 22, 16, 31, 38, 515, DateTimeKind.Local).AddTicks(5805),
                            Uri = "http://keon.name",
                            UserId = 8
                        },
                        new
                        {
                            Id = 22,
                            Created = new DateTime(2020, 4, 20, 16, 31, 38, 524, DateTimeKind.Local).AddTicks(4635),
                            Description = @"Provident maxime non sit.
Quod at iusto error at.
Ut qui iste ipsa dolor quos quo.
Distinctio enim magnam qui eum neque est eos.
Magnam est voluptas illum et qui alias.
Modi odio provident architecto illum.
Sit ut nostrum.
Dolore dolor voluptatum.
Minima libero soluta odit rerum minima nostrum unde sit.
Debitis quaerat amet voluptas cupiditate dolor rerum.",
                            Name = "Fantastic Cotton Cheese",
                            ShortDescription = "Omnis nobis a ab sit.",
                            Updated = new DateTime(2020, 4, 22, 16, 31, 38, 524, DateTimeKind.Local).AddTicks(4719),
                            Uri = "https://verona.net",
                            UserId = 6
                        },
                        new
                        {
                            Id = 23,
                            Created = new DateTime(2020, 4, 20, 16, 31, 38, 543, DateTimeKind.Local).AddTicks(8850),
                            Description = @"Dignissimos beatae sed.
Dignissimos distinctio eos occaecati debitis quisquam.
Tempore nihil earum.
Iste vero nisi quod.
Totam molestiae incidunt autem dolorem incidunt atque.
Voluptatem quisquam numquam.
Blanditiis delectus ratione.
Eos quo qui eos rerum sed dignissimos eum et.
Et et voluptatum quis consequatur.
Dignissimos qui qui sint pariatur voluptas est numquam.",
                            Name = "Ergonomic Concrete Computer",
                            ShortDescription = "Dolores quaerat sequi molestias.",
                            Updated = new DateTime(2020, 4, 22, 16, 31, 38, 543, DateTimeKind.Local).AddTicks(9379),
                            Uri = "https://rosalia.biz",
                            UserId = 29
                        },
                        new
                        {
                            Id = 24,
                            Created = new DateTime(2020, 4, 20, 16, 31, 38, 556, DateTimeKind.Local).AddTicks(8695),
                            Description = @"Hic debitis et aliquid.
In quia perspiciatis id et non.
Ex quos distinctio officiis vel harum hic vel et dolor.
Molestias vero nostrum quia et et ipsum ducimus.
Accusamus modi est.
Porro ut aperiam ducimus sequi odit est.
Id veniam et perferendis corporis nisi beatae nesciunt ducimus id.
Assumenda consectetur ex.
Consectetur beatae cupiditate voluptatum iusto autem.
Odit magni quisquam sunt nesciunt ratione.",
                            Name = "Licensed Cotton Table",
                            ShortDescription = "Et expedita sapiente sunt facere et in.",
                            Updated = new DateTime(2020, 4, 22, 16, 31, 38, 556, DateTimeKind.Local).AddTicks(9218),
                            Uri = "https://curtis.info",
                            UserId = 7
                        },
                        new
                        {
                            Id = 25,
                            Created = new DateTime(2020, 4, 20, 16, 31, 38, 563, DateTimeKind.Local).AddTicks(7719),
                            Description = @"Voluptatem ratione alias autem ea quod nulla consequatur.
Et quia eos nesciunt dolor tempore exercitationem non.
Non natus rerum rerum.
Velit iusto qui.
Cumque est quia possimus nisi quas vel voluptas maiores porro.
Et ea facere dolores accusantium suscipit qui et.
Qui illum aut dolores ut neque qui est.
Doloremque et itaque et dolorem.
Mollitia blanditiis officiis fugiat.
Nisi laboriosam est in dolores eum non consequatur.",
                            Name = "Handmade Wooden Ball",
                            ShortDescription = "Et dolor aut qui nihil occaecati aut omnis ipsa.",
                            Updated = new DateTime(2020, 4, 22, 16, 31, 38, 563, DateTimeKind.Local).AddTicks(7775),
                            Uri = "http://elmore.info",
                            UserId = 22
                        },
                        new
                        {
                            Id = 26,
                            Created = new DateTime(2020, 4, 20, 16, 31, 38, 568, DateTimeKind.Local).AddTicks(509),
                            Description = @"Dolor saepe culpa est sed sunt laudantium error voluptatibus ea.
Magni iusto rerum.
Harum sint debitis qui.
Repellat fugit sed corporis.
Fugiat esse et et eos.
Vel minus distinctio quo.
Hic sed ad ut voluptatem et.
Ullam laudantium facere voluptas in veritatis unde at dolore.
Nihil sint nam est.
Nisi nihil sequi consequatur voluptates.",
                            Name = "Rustic Granite Sausages",
                            ShortDescription = "Sit et in.",
                            Updated = new DateTime(2020, 4, 22, 16, 31, 38, 568, DateTimeKind.Local).AddTicks(591),
                            Uri = "http://chester.net",
                            UserId = 19
                        },
                        new
                        {
                            Id = 27,
                            Created = new DateTime(2020, 4, 20, 16, 31, 38, 578, DateTimeKind.Local).AddTicks(4666),
                            Description = @"Non possimus minima.
Quo excepturi quas perferendis deserunt odit consequatur aut est accusantium.
Ab et tempore vero sunt consectetur excepturi sit.
Fugit modi ex omnis voluptatum in et eos.
Beatae omnis nesciunt iure dolor odio fugiat velit.
Numquam aut sed quia.
Quis doloremque officiis eos aut vero aperiam.
Quam molestiae natus autem et nesciunt tenetur ut adipisci.
Et suscipit est magnam.
Nam voluptatem ut accusantium quis ab exercitationem.",
                            Name = "Handcrafted Metal Soap",
                            ShortDescription = "Mollitia et nam voluptatibus cupiditate animi sed.",
                            Updated = new DateTime(2020, 4, 22, 16, 31, 38, 578, DateTimeKind.Local).AddTicks(4731),
                            Uri = "https://thurman.name",
                            UserId = 7
                        },
                        new
                        {
                            Id = 28,
                            Created = new DateTime(2020, 4, 20, 16, 31, 38, 582, DateTimeKind.Local).AddTicks(6376),
                            Description = @"Doloribus qui tempore dolore animi voluptatem error magnam officiis.
Quia dignissimos non voluptas est eum distinctio aut quia ut.
Rerum hic quia et itaque expedita iure qui est iure.
At quo doloremque esse aliquid consequuntur ducimus enim a ut.
Porro eos beatae.
Optio vitae ducimus hic esse ut.
Eos odit officiis et vel nam consequatur dolor nam.
Natus incidunt officia quis.
Ea deleniti provident ea at earum et at incidunt.
Aliquid perspiciatis a corporis dolores.",
                            Name = "Intelligent Plastic Fish",
                            ShortDescription = "Aut et accusantium reiciendis molestiae perspiciatis at enim repellendus.",
                            Updated = new DateTime(2020, 4, 22, 16, 31, 38, 582, DateTimeKind.Local).AddTicks(6467),
                            Uri = "https://dylan.name",
                            UserId = 2
                        },
                        new
                        {
                            Id = 29,
                            Created = new DateTime(2020, 4, 20, 16, 31, 38, 590, DateTimeKind.Local).AddTicks(8578),
                            Description = @"Sit rerum quisquam ut esse illo.
Rerum dolore magnam rerum amet praesentium.
Velit officiis non.
Qui in natus qui rerum illum.
Modi in hic neque recusandae ut quasi soluta.
Cupiditate quasi qui dolorem ea sint enim qui qui.
Ut nam at nam quos et voluptatem quas.
Illo molestiae fuga alias et ut adipisci.
Iusto quisquam enim minima similique quas.
Deserunt laboriosam nostrum commodi sit libero corporis.",
                            Name = "Refined Wooden Tuna",
                            ShortDescription = "Nam non repudiandae a consequatur voluptates.",
                            Updated = new DateTime(2020, 4, 22, 16, 31, 38, 590, DateTimeKind.Local).AddTicks(8642),
                            Uri = "https://orrin.net",
                            UserId = 7
                        },
                        new
                        {
                            Id = 30,
                            Created = new DateTime(2020, 4, 20, 16, 31, 38, 597, DateTimeKind.Local).AddTicks(3309),
                            Description = @"Ut et soluta qui neque iusto quo quam quam reprehenderit.
Neque aliquam quasi voluptatem laborum.
Corrupti voluptates placeat quas a temporibus doloribus iure dolorem.
Reiciendis laudantium non vel quasi debitis expedita.
Enim laborum perspiciatis at incidunt totam alias et.
Culpa quibusdam fugit voluptas nemo facilis asperiores voluptatibus officia.
Et earum minima eligendi et laboriosam et eos a saepe.
Voluptatem veniam animi autem debitis alias et.
Cum veniam quas porro ut voluptate officia quo.
Libero illum provident fugiat atque alias tempora placeat.",
                            Name = "Practical Granite Tuna",
                            ShortDescription = "Et aut sint commodi est quae aliquid et voluptatem excepturi.",
                            Updated = new DateTime(2020, 4, 22, 16, 31, 38, 597, DateTimeKind.Local).AddTicks(3370),
                            Uri = "http://destini.net",
                            UserId = 25
                        });
                });

            modelBuilder.Entity("Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Nat.Bailey83@hotmail.com",
                            IdentityId = "2",
                            Name = "Nestor"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Jessica.Stamm29@yahoo.com",
                            IdentityId = "3",
                            Name = "Johanna"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Easton.Grimes@yahoo.com",
                            IdentityId = "4",
                            Name = "Marilyne"
                        },
                        new
                        {
                            Id = 4,
                            Email = "Gabrielle76@gmail.com",
                            IdentityId = "5",
                            Name = "Stephany"
                        },
                        new
                        {
                            Id = 5,
                            Email = "Sidney76@gmail.com",
                            IdentityId = "6",
                            Name = "Lue"
                        },
                        new
                        {
                            Id = 6,
                            Email = "Karianne.Koelpin30@gmail.com",
                            IdentityId = "7",
                            Name = "Angelina"
                        },
                        new
                        {
                            Id = 7,
                            Email = "Leon45@gmail.com",
                            IdentityId = "8",
                            Name = "Emmanuel"
                        },
                        new
                        {
                            Id = 8,
                            Email = "Elenor.Emmerich95@gmail.com",
                            IdentityId = "9",
                            Name = "Makayla"
                        },
                        new
                        {
                            Id = 9,
                            Email = "Pamela_OConnell@yahoo.com",
                            IdentityId = "10",
                            Name = "Zoie"
                        },
                        new
                        {
                            Id = 10,
                            Email = "Houston_Mraz@gmail.com",
                            IdentityId = "11",
                            Name = "Renee"
                        },
                        new
                        {
                            Id = 11,
                            Email = "Madelyn.Flatley48@gmail.com",
                            IdentityId = "12",
                            Name = "Chet"
                        },
                        new
                        {
                            Id = 12,
                            Email = "Clare8@hotmail.com",
                            IdentityId = "13",
                            Name = "Terrence"
                        },
                        new
                        {
                            Id = 13,
                            Email = "Kallie_Kihn@yahoo.com",
                            IdentityId = "14",
                            Name = "Evelyn"
                        },
                        new
                        {
                            Id = 14,
                            Email = "Florine.Runte89@hotmail.com",
                            IdentityId = "15",
                            Name = "Brianne"
                        },
                        new
                        {
                            Id = 15,
                            Email = "Kareem.Feeney98@gmail.com",
                            IdentityId = "16",
                            Name = "Rickie"
                        },
                        new
                        {
                            Id = 16,
                            Email = "Genoveva54@hotmail.com",
                            IdentityId = "17",
                            Name = "Buddy"
                        },
                        new
                        {
                            Id = 17,
                            Email = "Cathy.Wiza49@gmail.com",
                            IdentityId = "18",
                            Name = "Zella"
                        },
                        new
                        {
                            Id = 18,
                            Email = "Abdul.Graham@gmail.com",
                            IdentityId = "19",
                            Name = "Kelsie"
                        },
                        new
                        {
                            Id = 19,
                            Email = "Clarissa96@yahoo.com",
                            IdentityId = "20",
                            Name = "Liliana"
                        },
                        new
                        {
                            Id = 20,
                            Email = "Gina_Ernser@hotmail.com",
                            IdentityId = "21",
                            Name = "Rosa"
                        },
                        new
                        {
                            Id = 21,
                            Email = "Ellen.Weimann@hotmail.com",
                            IdentityId = "22",
                            Name = "Elmer"
                        },
                        new
                        {
                            Id = 22,
                            Email = "Prudence_Abernathy38@yahoo.com",
                            IdentityId = "23",
                            Name = "Juston"
                        },
                        new
                        {
                            Id = 23,
                            Email = "Susan.Hartmann@yahoo.com",
                            IdentityId = "24",
                            Name = "Vicente"
                        },
                        new
                        {
                            Id = 24,
                            Email = "Philip_Sawayn@yahoo.com",
                            IdentityId = "25",
                            Name = "Destany"
                        },
                        new
                        {
                            Id = 25,
                            Email = "Aliyah_Ferry5@gmail.com",
                            IdentityId = "26",
                            Name = "Alda"
                        },
                        new
                        {
                            Id = 26,
                            Email = "Joan62@gmail.com",
                            IdentityId = "27",
                            Name = "Pearl"
                        },
                        new
                        {
                            Id = 27,
                            Email = "Nicholas61@hotmail.com",
                            IdentityId = "28",
                            Name = "Pattie"
                        },
                        new
                        {
                            Id = 28,
                            Email = "Hunter_Heller@hotmail.com",
                            IdentityId = "29",
                            Name = "Lilliana"
                        },
                        new
                        {
                            Id = 29,
                            Email = "Vida50@hotmail.com",
                            IdentityId = "30",
                            Name = "Joyce"
                        },
                        new
                        {
                            Id = 30,
                            Email = "Xander49@hotmail.com",
                            IdentityId = "31",
                            Name = "Wayne"
                        });
                });

            modelBuilder.Entity("Models.Collaborator", b =>
                {
                    b.HasOne("Models.Project", null)
                        .WithMany("Collaborators")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.EmbeddedProject", b =>
                {
                    b.HasOne("Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.Highlight", b =>
                {
                    b.HasOne("Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.Project", b =>
                {
                    b.HasOne("Models.User", "User")
                        .WithMany("Projects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
