// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace _4_Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200505233305_DefaultRoles")]
    partial class DefaultRoles
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.Collaborator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Collaborators");

                    b.HasData(
                        new
                        {
                            Id = 4674,
                            FullName = "Karson Mertz",
                            ProjectId = 1,
                            Role = "International Branding Representative"
                        },
                        new
                        {
                            Id = 801,
                            FullName = "Janis Crist",
                            ProjectId = 1,
                            Role = "Human Functionality Producer"
                        },
                        new
                        {
                            Id = 3607,
                            FullName = "Vivien Strosin",
                            ProjectId = 2,
                            Role = "District Implementation Liaison"
                        },
                        new
                        {
                            Id = 3476,
                            FullName = "Kamron Padberg",
                            ProjectId = 2,
                            Role = "Corporate Program Planner"
                        },
                        new
                        {
                            Id = 8124,
                            FullName = "Meda Hane",
                            ProjectId = 3,
                            Role = "Investor Research Developer"
                        },
                        new
                        {
                            Id = 329,
                            FullName = "Mabel Koelpin",
                            ProjectId = 3,
                            Role = "Investor Web Strategist"
                        },
                        new
                        {
                            Id = 6226,
                            FullName = "Arielle Watsica",
                            ProjectId = 4,
                            Role = "Human Branding Planner"
                        },
                        new
                        {
                            Id = 7182,
                            FullName = "Delta Hirthe",
                            ProjectId = 4,
                            Role = "Lead Accountability Assistant"
                        },
                        new
                        {
                            Id = 8216,
                            FullName = "Raina McLaughlin",
                            ProjectId = 5,
                            Role = "Product Infrastructure Planner"
                        },
                        new
                        {
                            Id = 4760,
                            FullName = "Elenor Kunde",
                            ProjectId = 5,
                            Role = "Lead Interactions Representative"
                        },
                        new
                        {
                            Id = 6062,
                            FullName = "Jailyn Heaney",
                            ProjectId = 6,
                            Role = "District Accountability Planner"
                        },
                        new
                        {
                            Id = 2834,
                            FullName = "Nakia Hegmann",
                            ProjectId = 6,
                            Role = "Human Data Executive"
                        },
                        new
                        {
                            Id = 1920,
                            FullName = "Jamison Thompson",
                            ProjectId = 7,
                            Role = "Senior Division Assistant"
                        },
                        new
                        {
                            Id = 2088,
                            FullName = "Paris Schultz",
                            ProjectId = 7,
                            Role = "Global Data Director"
                        },
                        new
                        {
                            Id = 1191,
                            FullName = "Myrtis Brekke",
                            ProjectId = 8,
                            Role = "Internal Marketing Director"
                        },
                        new
                        {
                            Id = 5004,
                            FullName = "Lera Cummings",
                            ProjectId = 8,
                            Role = "Principal Response Officer"
                        },
                        new
                        {
                            Id = 2468,
                            FullName = "Dorcas Hoppe",
                            ProjectId = 9,
                            Role = "Forward Mobility Liaison"
                        },
                        new
                        {
                            Id = 4679,
                            FullName = "Tyree Ankunding",
                            ProjectId = 9,
                            Role = "Central Security Associate"
                        },
                        new
                        {
                            Id = 7167,
                            FullName = "Gia Spinka",
                            ProjectId = 10,
                            Role = "International Data Liaison"
                        },
                        new
                        {
                            Id = 1337,
                            FullName = "Aurore Ondricka",
                            ProjectId = 10,
                            Role = "Lead Tactics Liaison"
                        },
                        new
                        {
                            Id = 4907,
                            FullName = "Heidi Metz",
                            ProjectId = 11,
                            Role = "Lead Identity Officer"
                        },
                        new
                        {
                            Id = 9455,
                            FullName = "Corbin Dickinson",
                            ProjectId = 11,
                            Role = "Dynamic Configuration Officer"
                        },
                        new
                        {
                            Id = 4199,
                            FullName = "Hollie Bayer",
                            ProjectId = 12,
                            Role = "Dynamic Program Facilitator"
                        },
                        new
                        {
                            Id = 3074,
                            FullName = "Lucius Nienow",
                            ProjectId = 12,
                            Role = "Lead Marketing Producer"
                        },
                        new
                        {
                            Id = 4833,
                            FullName = "Randi Schroeder",
                            ProjectId = 13,
                            Role = "Lead Configuration Officer"
                        },
                        new
                        {
                            Id = 5367,
                            FullName = "Danika West",
                            ProjectId = 13,
                            Role = "Future Response Director"
                        },
                        new
                        {
                            Id = 5535,
                            FullName = "Isai Mante",
                            ProjectId = 14,
                            Role = "Internal Operations Agent"
                        },
                        new
                        {
                            Id = 8812,
                            FullName = "Alfred Little",
                            ProjectId = 14,
                            Role = "Dynamic Functionality Coordinator"
                        },
                        new
                        {
                            Id = 772,
                            FullName = "Janae Bechtelar",
                            ProjectId = 15,
                            Role = "Forward Assurance Developer"
                        },
                        new
                        {
                            Id = 4878,
                            FullName = "Jacquelyn Goodwin",
                            ProjectId = 15,
                            Role = "Internal Operations Planner"
                        },
                        new
                        {
                            Id = 3709,
                            FullName = "Stephania Hermiston",
                            ProjectId = 16,
                            Role = "Lead Marketing Orchestrator"
                        },
                        new
                        {
                            Id = 2333,
                            FullName = "Carolyne Corkery",
                            ProjectId = 16,
                            Role = "International Research Planner"
                        },
                        new
                        {
                            Id = 2867,
                            FullName = "Jarrett Brown",
                            ProjectId = 17,
                            Role = "Legacy Marketing Executive"
                        },
                        new
                        {
                            Id = 2119,
                            FullName = "Reggie Littel",
                            ProjectId = 17,
                            Role = "District Usability Coordinator"
                        },
                        new
                        {
                            Id = 1274,
                            FullName = "Monica Larkin",
                            ProjectId = 18,
                            Role = "Future Accounts Assistant"
                        },
                        new
                        {
                            Id = 465,
                            FullName = "Micaela Vandervort",
                            ProjectId = 18,
                            Role = "Lead Applications Orchestrator"
                        },
                        new
                        {
                            Id = 5373,
                            FullName = "Samson Toy",
                            ProjectId = 19,
                            Role = "Chief Group Executive"
                        },
                        new
                        {
                            Id = 2231,
                            FullName = "Felix Herzog",
                            ProjectId = 19,
                            Role = "Central Operations Manager"
                        },
                        new
                        {
                            Id = 5739,
                            FullName = "Nat Haag",
                            ProjectId = 20,
                            Role = "Corporate Web Developer"
                        },
                        new
                        {
                            Id = 222,
                            FullName = "Tina Watsica",
                            ProjectId = 20,
                            Role = "Principal Accountability Administrator"
                        },
                        new
                        {
                            Id = 1000,
                            FullName = "Walker Huel",
                            ProjectId = 21,
                            Role = "Product Quality Coordinator"
                        },
                        new
                        {
                            Id = 6845,
                            FullName = "Eden Armstrong",
                            ProjectId = 21,
                            Role = "Central Implementation Specialist"
                        },
                        new
                        {
                            Id = 2180,
                            FullName = "Earnest Hudson",
                            ProjectId = 22,
                            Role = "District Integration Orchestrator"
                        },
                        new
                        {
                            Id = 248,
                            FullName = "Marcus Doyle",
                            ProjectId = 22,
                            Role = "Product Quality Supervisor"
                        },
                        new
                        {
                            Id = 5243,
                            FullName = "Shanny Bogan",
                            ProjectId = 23,
                            Role = "Dynamic Metrics Designer"
                        },
                        new
                        {
                            Id = 6977,
                            FullName = "Kelsie Wuckert",
                            ProjectId = 23,
                            Role = "Central Creative Architect"
                        },
                        new
                        {
                            Id = 7154,
                            FullName = "Susie Pacocha",
                            ProjectId = 24,
                            Role = "Principal Accounts Manager"
                        },
                        new
                        {
                            Id = 2203,
                            FullName = "Aurelie Leuschke",
                            ProjectId = 24,
                            Role = "Lead Usability Director"
                        },
                        new
                        {
                            Id = 3253,
                            FullName = "Kyle Quitzon",
                            ProjectId = 25,
                            Role = "Product Usability Manager"
                        },
                        new
                        {
                            Id = 2116,
                            FullName = "Reginald Grady",
                            ProjectId = 25,
                            Role = "Regional Data Consultant"
                        },
                        new
                        {
                            Id = 3112,
                            FullName = "Jena Haag",
                            ProjectId = 26,
                            Role = "Central Accounts Technician"
                        },
                        new
                        {
                            Id = 3053,
                            FullName = "Narciso Klein",
                            ProjectId = 26,
                            Role = "Chief Assurance Specialist"
                        },
                        new
                        {
                            Id = 9426,
                            FullName = "Aniyah Tromp",
                            ProjectId = 27,
                            Role = "Principal Brand Planner"
                        },
                        new
                        {
                            Id = 4906,
                            FullName = "Joanny Weber",
                            ProjectId = 27,
                            Role = "Legacy Accountability Coordinator"
                        },
                        new
                        {
                            Id = 8235,
                            FullName = "Genoveva Morar",
                            ProjectId = 28,
                            Role = "Legacy Functionality Supervisor"
                        },
                        new
                        {
                            Id = 1771,
                            FullName = "Felicity Bruen",
                            ProjectId = 28,
                            Role = "Human Branding Specialist"
                        },
                        new
                        {
                            Id = 9320,
                            FullName = "Mylene Hahn",
                            ProjectId = 29,
                            Role = "Human Assurance Manager"
                        },
                        new
                        {
                            Id = 8943,
                            FullName = "Glen Streich",
                            ProjectId = 29,
                            Role = "Regional Identity Agent"
                        },
                        new
                        {
                            Id = 3157,
                            FullName = "Deion Ruecker",
                            ProjectId = 30,
                            Role = "International Accountability Specialist"
                        },
                        new
                        {
                            Id = 8611,
                            FullName = "Keyshawn Mraz",
                            ProjectId = 30,
                            Role = "Chief Branding Administrator"
                        });
                });

            modelBuilder.Entity("Models.Highlight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Highlight");
                });

            modelBuilder.Entity("Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Project");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2020, 5, 4, 1, 33, 3, 923, DateTimeKind.Local).AddTicks(7696),
                            Description = @"Et tempore laboriosam quia officiis voluptatem autem modi sit.
Enim ut velit totam aut odit cum.
Fugiat dolorem ut inventore ea occaecati qui dignissimos sit.
Consequuntur in tenetur sint et itaque rerum rerum impedit debitis.
Quia eius maiores qui.
Minima harum ut quis in voluptatum est dolorum.
Deleniti tempora odio enim illum et molestiae non voluptates explicabo.
Deserunt facere ea quaerat culpa eius qui quibusdam et.
Rerum omnis voluptatum cum et molestias dolor.
Atque et cum.",
                            Name = "Practical Fresh Tuna",
                            ShortDescription = "Cupiditate eum impedit dignissimos et.",
                            Updated = new DateTime(2020, 5, 6, 1, 33, 3, 932, DateTimeKind.Local).AddTicks(9124),
                            Uri = "https://korbin.info",
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2020, 5, 4, 1, 33, 3, 940, DateTimeKind.Local).AddTicks(8489),
                            Description = @"Magni cupiditate incidunt aut impedit sit beatae molestiae asperiores.
Sed tempore delectus deserunt in iste.
Rerum molestiae odio odit quaerat.
Sit unde dolores id.
Doloribus quo sed harum nam tempore perspiciatis.
Ad dolorem laboriosam ullam in placeat nisi ipsa.
Aperiam deleniti voluptatem enim magnam ut molestias rerum ducimus.
Officiis exercitationem non praesentium sunt culpa similique itaque.
Commodi ut aut nostrum.
Vero veniam vitae.",
                            Name = "Fantastic Plastic Salad",
                            ShortDescription = "Consequuntur et ea repudiandae consectetur quia excepturi.",
                            Updated = new DateTime(2020, 5, 6, 1, 33, 3, 940, DateTimeKind.Local).AddTicks(8573),
                            Uri = "https://ramiro.net",
                            UserId = 15
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2020, 5, 4, 1, 33, 3, 946, DateTimeKind.Local).AddTicks(3726),
                            Description = @"Numquam reiciendis tempore nihil et impedit voluptas quisquam.
Consequatur consectetur cum.
Accusantium consectetur aut blanditiis ut blanditiis delectus omnis qui suscipit.
Odit eaque rerum sint repellat quis sed vero possimus sequi.
Enim autem iusto numquam quis omnis ea vero omnis.
Excepturi incidunt corrupti laudantium id quod voluptas voluptas.
Doloribus harum facilis porro voluptatem accusantium voluptas nulla.
Quidem id sit et temporibus incidunt debitis animi.
Facere dicta amet.
Est repellendus incidunt deserunt aut.",
                            Name = "Handmade Plastic Soap",
                            ShortDescription = "Blanditiis reprehenderit harum odio sit aut.",
                            Updated = new DateTime(2020, 5, 6, 1, 33, 3, 946, DateTimeKind.Local).AddTicks(3791),
                            Uri = "https://krista.biz",
                            UserId = 17
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2020, 5, 4, 1, 33, 3, 952, DateTimeKind.Local).AddTicks(7336),
                            Description = @"Recusandae cum modi rerum qui deserunt odio.
Qui consequatur quisquam aut facere.
Harum et vero atque qui eius.
Reprehenderit suscipit consequatur dolorem ipsam.
Et et non earum et error deleniti aliquam soluta.
Voluptas quo repellat consequatur velit accusamus eum.
Molestiae voluptatem est non quaerat consequatur ipsum iure ut ullam.
Nisi eius omnis beatae dolor vel consectetur.
Veritatis illum dignissimos ad quia.
Ea sit est qui at aut occaecati hic explicabo id.",
                            Name = "Handcrafted Wooden Mouse",
                            ShortDescription = "Nesciunt aspernatur aut.",
                            Updated = new DateTime(2020, 5, 6, 1, 33, 3, 952, DateTimeKind.Local).AddTicks(7439),
                            Uri = "http://casimir.name",
                            UserId = 12
                        },
                        new
                        {
                            Id = 5,
                            Created = new DateTime(2020, 5, 4, 1, 33, 3, 961, DateTimeKind.Local).AddTicks(2207),
                            Description = @"Veniam veritatis possimus eius omnis.
Et quia explicabo.
Maiores dignissimos sunt vero temporibus cupiditate distinctio fugit amet sit.
Consequuntur eaque voluptatem dolorum porro iure.
Nostrum ullam pariatur explicabo quos dolorum sed tenetur necessitatibus excepturi.
Aut voluptatem et repellat facere.
Porro cupiditate hic.
Dolore vero atque asperiores eligendi earum nesciunt.
Id mollitia quo.
Provident doloremque quibusdam eos necessitatibus hic tenetur.",
                            Name = "Generic Wooden Fish",
                            ShortDescription = "Fugiat harum voluptatem vel vitae repellat voluptas consequuntur.",
                            Updated = new DateTime(2020, 5, 6, 1, 33, 3, 961, DateTimeKind.Local).AddTicks(2274),
                            Uri = "http://ole.name",
                            UserId = 29
                        },
                        new
                        {
                            Id = 6,
                            Created = new DateTime(2020, 5, 4, 1, 33, 3, 965, DateTimeKind.Local).AddTicks(5939),
                            Description = @"Dignissimos consequatur aut.
Cum a non sequi repudiandae totam atque quos mollitia.
Et dolor assumenda similique.
Dolor et nihil tempore.
Optio dolor aperiam quod dolor eligendi facilis sit dolor maiores.
Est temporibus voluptatem minima dolor.
Voluptatum ut nisi mollitia quas dolorem et libero est eos.
Incidunt sunt molestiae id eligendi consectetur aut.
Molestiae amet quis modi qui corporis.
Est pariatur nulla reprehenderit et.",
                            Name = "Intelligent Cotton Pants",
                            ShortDescription = "Molestiae officiis eos rem voluptas.",
                            Updated = new DateTime(2020, 5, 6, 1, 33, 3, 965, DateTimeKind.Local).AddTicks(5983),
                            Uri = "http://vella.org",
                            UserId = 8
                        },
                        new
                        {
                            Id = 7,
                            Created = new DateTime(2020, 5, 4, 1, 33, 3, 973, DateTimeKind.Local).AddTicks(760),
                            Description = @"Accusantium hic id natus laborum beatae mollitia.
Repellendus vero porro.
Aut cupiditate exercitationem.
Natus architecto dolorem eum.
Sit aut cumque quis ut consequatur debitis.
Corrupti vel fugit consequatur libero quibusdam aliquid nihil ab ut.
Autem similique molestias similique sequi eaque praesentium et sit.
Qui eaque magnam fuga aperiam eligendi ratione et ad ut.
Porro dolores exercitationem ipsa id id nisi qui.
Corrupti excepturi quo illo deserunt hic dolorem ut perspiciatis magnam.",
                            Name = "Ergonomic Steel Chair",
                            ShortDescription = "Similique eos repudiandae eaque omnis et quod harum aut.",
                            Updated = new DateTime(2020, 5, 6, 1, 33, 3, 973, DateTimeKind.Local).AddTicks(821),
                            Uri = "http://claude.com",
                            UserId = 6
                        },
                        new
                        {
                            Id = 8,
                            Created = new DateTime(2020, 5, 4, 1, 33, 3, 977, DateTimeKind.Local).AddTicks(2755),
                            Description = @"Non non omnis ullam sed architecto.
Molestias earum sed.
Aperiam dicta accusamus repudiandae.
Voluptatem perspiciatis qui vero modi.
Ut id asperiores impedit fuga.
Est id hic repellat sint sint et impedit.
Hic nobis quos repellendus ea aspernatur in tempore impedit unde.
Exercitationem iusto facere nisi.
Eius non hic quaerat illum corporis velit ducimus nisi qui.
Aliquam velit sint sunt.",
                            Name = "Unbranded Steel Car",
                            ShortDescription = "Sed autem quasi vero est.",
                            Updated = new DateTime(2020, 5, 6, 1, 33, 3, 977, DateTimeKind.Local).AddTicks(2813),
                            Uri = "http://pierre.net",
                            UserId = 10
                        },
                        new
                        {
                            Id = 9,
                            Created = new DateTime(2020, 5, 4, 1, 33, 3, 980, DateTimeKind.Local).AddTicks(2433),
                            Description = @"Reprehenderit odio aliquam maiores.
Beatae ullam corporis nam ducimus quia est.
Ipsa odio qui saepe quia.
Adipisci aut voluptatibus sunt inventore soluta.
Ut qui reprehenderit repellendus sunt facere.
Dolore inventore ut.
Eius et sed numquam ut officia facere.
Nihil culpa id harum.
Enim consequatur officia sunt.
Voluptate ut adipisci corporis.",
                            Name = "Handcrafted Steel Ball",
                            ShortDescription = "Consequatur sequi repudiandae.",
                            Updated = new DateTime(2020, 5, 6, 1, 33, 3, 980, DateTimeKind.Local).AddTicks(2476),
                            Uri = "http://reed.com",
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            Created = new DateTime(2020, 5, 4, 1, 33, 3, 983, DateTimeKind.Local).AddTicks(5969),
                            Description = @"Sit tempore tempore ea reiciendis impedit qui.
Vero aliquam et nam excepturi.
Sint quia neque non.
Et omnis consequatur.
Sed nemo veritatis aliquid impedit debitis dolor quibusdam iste dolorum.
Eius mollitia eligendi.
Fugit deleniti perferendis aut.
Quae quia ratione facilis omnis.
Libero quaerat optio delectus suscipit.
Est omnis dolores ab sint ex est praesentium beatae praesentium.",
                            Name = "Generic Steel Chips",
                            ShortDescription = "Ipsa quam itaque sint excepturi.",
                            Updated = new DateTime(2020, 5, 6, 1, 33, 3, 983, DateTimeKind.Local).AddTicks(6023),
                            Uri = "https://sedrick.info",
                            UserId = 2
                        },
                        new
                        {
                            Id = 11,
                            Created = new DateTime(2020, 5, 4, 1, 33, 3, 990, DateTimeKind.Local).AddTicks(4907),
                            Description = @"Sit neque esse deserunt nisi non cupiditate aut officia.
Odit similique quo iste sit.
Quia voluptas omnis quaerat.
At aut tempora dolorem dignissimos sequi voluptas.
Eum optio dignissimos dolorum saepe aut necessitatibus et voluptas nisi.
Iste ea voluptas possimus.
Consequatur vitae tenetur placeat dolorum.
Ipsam doloribus assumenda minima voluptatum inventore.
Assumenda eveniet illo velit.
Quia deserunt nam hic.",
                            Name = "Generic Granite Chair",
                            ShortDescription = "Facere nostrum optio ex voluptatibus corporis nihil incidunt sunt nisi.",
                            Updated = new DateTime(2020, 5, 6, 1, 33, 3, 990, DateTimeKind.Local).AddTicks(4963),
                            Uri = "https://reanna.name",
                            UserId = 12
                        },
                        new
                        {
                            Id = 12,
                            Created = new DateTime(2020, 5, 4, 1, 33, 3, 995, DateTimeKind.Local).AddTicks(7028),
                            Description = @"Eum qui pariatur laborum sit eum enim asperiores dignissimos adipisci.
Dolores iste dolorem facilis esse.
Sed blanditiis molestiae odit.
Nobis et quae eum quo.
Enim sed at dolorum delectus.
Non numquam aut sit quam.
Eum commodi sed aut ut explicabo.
Dolor enim eaque tempora repellat sed sit.
Ab assumenda repellendus similique rerum fugit ipsa soluta voluptates.
Id ipsum enim a et.",
                            Name = "Intelligent Rubber Ball",
                            ShortDescription = "Aut repellendus asperiores perspiciatis maxime.",
                            Updated = new DateTime(2020, 5, 6, 1, 33, 3, 995, DateTimeKind.Local).AddTicks(7099),
                            Uri = "https://jacky.info",
                            UserId = 21
                        },
                        new
                        {
                            Id = 13,
                            Created = new DateTime(2020, 5, 4, 1, 33, 4, 1, DateTimeKind.Local).AddTicks(2173),
                            Description = @"Enim nemo vero.
Harum rem nesciunt ducimus ipsam voluptas voluptatum.
Nisi soluta et voluptas laborum.
Voluptatem modi voluptas est nihil numquam quia temporibus quasi aliquam.
Et laborum explicabo in.
Velit id corrupti.
Ut quibusdam quibusdam maiores.
Ipsa nemo facilis sed veritatis dolorem consequatur odit doloremque officia.
Nesciunt unde aut rerum vel.
In ut aliquam magnam voluptatem vel est corporis enim.",
                            Name = "Tasty Fresh Hat",
                            ShortDescription = "Minima vel eum.",
                            Updated = new DateTime(2020, 5, 6, 1, 33, 4, 1, DateTimeKind.Local).AddTicks(2235),
                            Uri = "https://kira.net",
                            UserId = 11
                        },
                        new
                        {
                            Id = 14,
                            Created = new DateTime(2020, 5, 4, 1, 33, 4, 7, DateTimeKind.Local).AddTicks(3519),
                            Description = @"Officia consequatur sunt vel sapiente qui.
Voluptatem aut eos quisquam nulla pariatur optio.
Saepe minus placeat necessitatibus non accusamus.
Autem qui provident qui facilis quia necessitatibus corporis qui et.
Ut aliquam reprehenderit vel officiis quis error accusamus.
Nihil voluptate corporis et non est et.
Quia reiciendis quos aut est est non.
Pariatur ut earum iure autem in ipsa eius odit hic.
Consequatur vitae vero praesentium quia inventore.
Voluptatum iure quo aut velit.",
                            Name = "Handmade Cotton Salad",
                            ShortDescription = "Illo ex sit voluptas aut voluptas nostrum similique sit eos.",
                            Updated = new DateTime(2020, 5, 6, 1, 33, 4, 7, DateTimeKind.Local).AddTicks(3571),
                            Uri = "http://hermina.org",
                            UserId = 4
                        },
                        new
                        {
                            Id = 15,
                            Created = new DateTime(2020, 5, 4, 1, 33, 4, 10, DateTimeKind.Local).AddTicks(8324),
                            Description = @"Vitae quia culpa dolore veritatis.
Ut sint dolorem sint dolore non.
Aut maxime eaque voluptatibus sit sit qui velit non.
Expedita officiis dolorem eius fugiat.
Cumque sunt incidunt harum accusantium facere.
Et quo doloribus voluptates repudiandae quia voluptas nulla quae.
Ex facere minima sit facilis.
Aut qui neque officiis.
Et quis labore tempora iusto aut totam nisi perferendis culpa.
Ex ut quam enim nisi aut deleniti debitis consequatur.",
                            Name = "Sleek Wooden Pizza",
                            ShortDescription = "Laborum occaecati totam totam omnis reprehenderit.",
                            Updated = new DateTime(2020, 5, 6, 1, 33, 4, 10, DateTimeKind.Local).AddTicks(8397),
                            Uri = "http://amira.name",
                            UserId = 19
                        },
                        new
                        {
                            Id = 16,
                            Created = new DateTime(2020, 5, 4, 1, 33, 4, 17, DateTimeKind.Local).AddTicks(3663),
                            Description = @"Optio laboriosam facere soluta deleniti numquam autem quas doloremque.
Iste in nemo animi quis consequatur alias ut quis.
Atque nemo at est omnis aut quisquam.
Et saepe in itaque voluptatum quia.
Non officia molestiae repellat distinctio asperiores asperiores qui.
Voluptates et dolore temporibus nobis laborum sed non.
Autem enim iure corrupti voluptatibus sint animi.
Sapiente culpa dolores quis dolorum molestiae.
Debitis dignissimos eius sunt.
Et molestias corrupti est odit eos eligendi quidem non qui.",
                            Name = "Intelligent Fresh Salad",
                            ShortDescription = "Omnis consectetur commodi aspernatur eos.",
                            Updated = new DateTime(2020, 5, 6, 1, 33, 4, 17, DateTimeKind.Local).AddTicks(3750),
                            Uri = "http://helga.com",
                            UserId = 18
                        },
                        new
                        {
                            Id = 17,
                            Created = new DateTime(2020, 5, 4, 1, 33, 4, 25, DateTimeKind.Local).AddTicks(8739),
                            Description = @"Velit ducimus autem.
Qui aut repudiandae labore reprehenderit.
Labore rerum accusamus qui nam eum sed.
Delectus error ut ad.
Sit aliquam dolorem enim perspiciatis.
Est veritatis sunt praesentium voluptatum beatae minima minus in omnis.
Sit corrupti repudiandae ut tenetur quam incidunt.
Libero inventore quos.
Et animi et eos sunt.
Aperiam ipsam quo consequatur.",
                            Name = "Sleek Cotton Mouse",
                            ShortDescription = "Repellendus deleniti nam corrupti.",
                            Updated = new DateTime(2020, 5, 6, 1, 33, 4, 25, DateTimeKind.Local).AddTicks(8812),
                            Uri = "http://ima.name",
                            UserId = 23
                        },
                        new
                        {
                            Id = 18,
                            Created = new DateTime(2020, 5, 4, 1, 33, 4, 31, DateTimeKind.Local).AddTicks(3578),
                            Description = @"Unde maxime ea quia incidunt quo.
Ut debitis earum sed omnis eos vero.
Earum amet ut perspiciatis ut nobis et dolore.
Facere quis recusandae quo.
Veniam voluptate hic laborum doloribus.
Illo dolor delectus.
Adipisci porro id corrupti ullam libero cumque non et porro.
Velit fugit repellat iusto possimus eveniet et tempora quis.
Et omnis earum mollitia provident dolorem dolorem ratione et dolorum.
Eius in ut sint.",
                            Name = "Handcrafted Granite Chicken",
                            ShortDescription = "Neque rerum laudantium.",
                            Updated = new DateTime(2020, 5, 6, 1, 33, 4, 31, DateTimeKind.Local).AddTicks(3645),
                            Uri = "http://natalie.info",
                            UserId = 27
                        },
                        new
                        {
                            Id = 19,
                            Created = new DateTime(2020, 5, 4, 1, 33, 4, 40, DateTimeKind.Local).AddTicks(518),
                            Description = @"Tenetur quia ut nesciunt omnis.
Mollitia voluptatem nostrum a nam saepe assumenda.
Provident vel dolorem explicabo rerum reiciendis sed.
Et tempore minus iste omnis ipsam sit animi.
Ducimus excepturi labore non asperiores repudiandae facilis quasi.
Fuga iste illo natus quam enim dolor.
Occaecati eum deleniti accusantium pariatur aut possimus ullam aliquam error.
Repellat autem minima quo est voluptatem.
Vel non quis ut.
Sit accusantium aperiam ex voluptatibus mollitia.",
                            Name = "Rustic Granite Car",
                            ShortDescription = "Magnam laudantium autem quibusdam quibusdam.",
                            Updated = new DateTime(2020, 5, 6, 1, 33, 4, 40, DateTimeKind.Local).AddTicks(593),
                            Uri = "http://noelia.biz",
                            UserId = 5
                        },
                        new
                        {
                            Id = 20,
                            Created = new DateTime(2020, 5, 4, 1, 33, 4, 48, DateTimeKind.Local).AddTicks(2698),
                            Description = @"Quod ut numquam quasi illum nisi porro consequatur et quia.
Est tempore reiciendis sint exercitationem repellat illum placeat est nihil.
Enim sapiente fuga asperiores deleniti eaque similique cumque et ut.
Autem et sed.
A eius aut ut incidunt quia quae in est quia.
Aut eum dolorum repellendus distinctio impedit quia pariatur eaque.
Ducimus qui eos cum quibusdam.
Deserunt et id ullam dolor et voluptas.
Mollitia id molestias.
Assumenda voluptatem iure eveniet accusamus distinctio.",
                            Name = "Generic Cotton Shoes",
                            ShortDescription = "Quod vitae eum nemo.",
                            Updated = new DateTime(2020, 5, 6, 1, 33, 4, 48, DateTimeKind.Local).AddTicks(2752),
                            Uri = "https://boyd.name",
                            UserId = 14
                        },
                        new
                        {
                            Id = 21,
                            Created = new DateTime(2020, 5, 4, 1, 33, 4, 57, DateTimeKind.Local).AddTicks(4322),
                            Description = @"Voluptatem officia et culpa blanditiis et.
Dolorem rerum vitae.
Culpa amet molestiae velit minus beatae est.
Unde hic velit occaecati inventore blanditiis omnis laborum ut.
Tempora quisquam et non.
Officia et ipsa amet.
Minus omnis ipsa sit architecto labore quas facilis eum.
Et officiis corporis nulla.
Dignissimos hic quasi quis quia optio ipsa pariatur optio esse.
Rerum ab doloribus suscipit minima.",
                            Name = "Ergonomic Metal Hat",
                            ShortDescription = "Necessitatibus delectus dolores est voluptates sit dignissimos qui.",
                            Updated = new DateTime(2020, 5, 6, 1, 33, 4, 57, DateTimeKind.Local).AddTicks(4397),
                            Uri = "http://catherine.org",
                            UserId = 18
                        },
                        new
                        {
                            Id = 22,
                            Created = new DateTime(2020, 5, 4, 1, 33, 4, 63, DateTimeKind.Local).AddTicks(485),
                            Description = @"Est similique facere rerum pariatur tempore.
Aut eligendi molestiae.
Id quo ex blanditiis et.
Vero quod voluptatibus.
Impedit consectetur sed assumenda et.
Ipsum culpa vel quisquam alias veritatis rerum.
Atque ut eligendi.
Sit dolorem at dignissimos pariatur error.
Qui totam et laudantium dolor ad tenetur.
Beatae veritatis autem numquam officiis.",
                            Name = "Rustic Metal Pants",
                            ShortDescription = "Quia saepe provident aut.",
                            Updated = new DateTime(2020, 5, 6, 1, 33, 4, 63, DateTimeKind.Local).AddTicks(542),
                            Uri = "https://beverly.biz",
                            UserId = 3
                        },
                        new
                        {
                            Id = 23,
                            Created = new DateTime(2020, 5, 4, 1, 33, 4, 68, DateTimeKind.Local).AddTicks(7164),
                            Description = @"Ex molestiae est sequi atque ut.
Aut consectetur eveniet vitae tempore.
Harum ducimus quae.
Et ab odit sit qui quia saepe recusandae.
Natus rerum eius aperiam sapiente.
Non ipsa dolorem nulla.
Numquam deserunt autem aperiam.
Nobis quia eaque modi.
Magnam possimus ullam at ut consectetur.
In provident eius eum modi neque nihil cumque possimus.",
                            Name = "Licensed Concrete Chips",
                            ShortDescription = "Itaque vero ratione architecto.",
                            Updated = new DateTime(2020, 5, 6, 1, 33, 4, 68, DateTimeKind.Local).AddTicks(7244),
                            Uri = "http://ezequiel.name",
                            UserId = 10
                        },
                        new
                        {
                            Id = 24,
                            Created = new DateTime(2020, 5, 4, 1, 33, 4, 79, DateTimeKind.Local).AddTicks(284),
                            Description = @"Omnis eos rerum.
Impedit voluptates enim aut sint sit inventore aperiam distinctio.
Exercitationem fuga in asperiores et sunt suscipit corrupti.
Iure sit architecto laboriosam dignissimos nesciunt atque.
Et recusandae autem fuga qui suscipit.
Excepturi aliquam reprehenderit illum quo aut debitis dolorem atque et.
Aut quam deleniti voluptas dolorem id quis.
Dolores tempore harum similique et est iusto.
Et aspernatur accusamus sit eveniet nostrum quam deleniti dolor.
Sint est iste excepturi ex deserunt voluptates recusandae.",
                            Name = "Sleek Plastic Ball",
                            ShortDescription = "Veritatis ut repellendus assumenda.",
                            Updated = new DateTime(2020, 5, 6, 1, 33, 4, 79, DateTimeKind.Local).AddTicks(339),
                            Uri = "https://lea.net",
                            UserId = 7
                        },
                        new
                        {
                            Id = 25,
                            Created = new DateTime(2020, 5, 4, 1, 33, 4, 83, DateTimeKind.Local).AddTicks(6251),
                            Description = @"Non sunt in ipsum dignissimos qui et esse.
Nobis repellat alias nam rem eius rerum.
Maiores ipsam ipsa.
Recusandae perspiciatis autem ut facilis voluptas vel cum.
Qui fugit animi.
Ipsum molestiae dolore iure et et.
Quos quia dolores veritatis ut quia ullam quo cumque minus.
Maiores quo accusantium deserunt perspiciatis accusantium ut et in.
Id et incidunt aut in quia ullam autem reprehenderit.
Sint est et dolorem est quae enim repellat.",
                            Name = "Refined Plastic Salad",
                            ShortDescription = "Doloremque aut reiciendis vel animi magni omnis.",
                            Updated = new DateTime(2020, 5, 6, 1, 33, 4, 83, DateTimeKind.Local).AddTicks(6307),
                            Uri = "http://eugene.net",
                            UserId = 2
                        },
                        new
                        {
                            Id = 26,
                            Created = new DateTime(2020, 5, 4, 1, 33, 4, 95, DateTimeKind.Local).AddTicks(5362),
                            Description = @"Quia facere dolorem ut.
Et hic repellat quae.
Quasi recusandae ullam est eos.
Et porro ut ad consequatur eum possimus quia harum facere.
Impedit est voluptates ipsum unde et praesentium necessitatibus.
Repellendus dolor magni et in aperiam.
Tempore enim nam eum doloribus id deserunt eum quas pariatur.
Eos ut asperiores cumque harum molestiae et labore enim dolores.
Occaecati minima quo aut.
Velit porro officia assumenda cumque suscipit.",
                            Name = "Intelligent Wooden Ball",
                            ShortDescription = "Dicta consequatur delectus et est odit dolores non libero optio.",
                            Updated = new DateTime(2020, 5, 6, 1, 33, 4, 95, DateTimeKind.Local).AddTicks(5416),
                            Uri = "http://king.org",
                            UserId = 3
                        },
                        new
                        {
                            Id = 27,
                            Created = new DateTime(2020, 5, 4, 1, 33, 4, 101, DateTimeKind.Local).AddTicks(6438),
                            Description = @"Quidem suscipit omnis quibusdam provident temporibus eum asperiores.
Sequi qui libero.
Beatae quis cupiditate ducimus voluptates saepe libero quas numquam magni.
Est totam dolorem et.
Laboriosam doloremque fugit similique.
Dolores commodi sunt aut omnis voluptatem culpa non ut hic.
Eos facere dolorum autem architecto explicabo excepturi consectetur.
Velit quam sed fuga amet et.
Assumenda facere est consequuntur minima aspernatur doloremque earum molestiae hic.
Ex accusamus dicta sunt cum.",
                            Name = "Practical Steel Keyboard",
                            ShortDescription = "In placeat porro sed.",
                            Updated = new DateTime(2020, 5, 6, 1, 33, 4, 101, DateTimeKind.Local).AddTicks(6485),
                            Uri = "https://layla.name",
                            UserId = 27
                        },
                        new
                        {
                            Id = 28,
                            Created = new DateTime(2020, 5, 4, 1, 33, 4, 110, DateTimeKind.Local).AddTicks(1509),
                            Description = @"Porro neque hic repudiandae corrupti inventore vel quia.
Qui praesentium omnis quisquam cum qui consequuntur maxime sequi.
Reprehenderit fuga quod voluptatem tempora.
Ut omnis cupiditate deserunt non est.
Aut nisi tempora omnis alias.
Et consequatur ad in voluptates ea.
Maiores asperiores non autem aperiam dolores commodi mollitia optio veritatis.
Eos est voluptatum qui ullam quis qui labore numquam aspernatur.
Vel ducimus est consequuntur enim quis sint sed tempora.
Nam quis qui aliquid incidunt qui iste aperiam dolore.",
                            Name = "Sleek Frozen Computer",
                            ShortDescription = "Ipsam minima dolore fuga ad sapiente est molestias maiores.",
                            Updated = new DateTime(2020, 5, 6, 1, 33, 4, 110, DateTimeKind.Local).AddTicks(1576),
                            Uri = "http://carolyn.biz",
                            UserId = 12
                        },
                        new
                        {
                            Id = 29,
                            Created = new DateTime(2020, 5, 4, 1, 33, 4, 113, DateTimeKind.Local).AddTicks(9711),
                            Description = @"Odit voluptates sit.
Vitae culpa quo.
Rem iusto voluptatem temporibus.
Iste accusantium quia.
Laboriosam iusto aspernatur velit veritatis pariatur aliquid error consequatur magni.
Sequi occaecati ducimus numquam id voluptatem.
Est pariatur ipsum soluta id dignissimos aspernatur voluptatem.
Itaque itaque odio et temporibus totam dolor et et.
Debitis ipsa inventore fugiat excepturi beatae ducimus.
Asperiores tenetur doloribus aut ab sint.",
                            Name = "Refined Concrete Soap",
                            ShortDescription = "Autem ex autem distinctio optio et aut voluptates aut velit.",
                            Updated = new DateTime(2020, 5, 6, 1, 33, 4, 113, DateTimeKind.Local).AddTicks(9761),
                            Uri = "https://margaretta.com",
                            UserId = 11
                        },
                        new
                        {
                            Id = 30,
                            Created = new DateTime(2020, 5, 4, 1, 33, 4, 119, DateTimeKind.Local).AddTicks(4551),
                            Description = @"Esse eius enim qui officia sit distinctio animi quis sit.
Velit pariatur magni.
Occaecati dolores velit aut eum voluptas aut eos omnis magni.
Quam necessitatibus excepturi.
Et corporis laborum eaque reprehenderit eum est aliquid.
Laboriosam dolores inventore velit quidem asperiores quo nesciunt minima.
Quae sed quia culpa a odit enim ea.
Qui ut mollitia est sunt ut.
Et officia vel quod.
Officiis ratione fuga.",
                            Name = "Generic Metal Pants",
                            ShortDescription = "Magnam dolor eligendi tempora repellendus quam necessitatibus eos voluptatem.",
                            Updated = new DateTime(2020, 5, 6, 1, 33, 4, 119, DateTimeKind.Local).AddTicks(4626),
                            Uri = "https://kennedi.net",
                            UserId = 28
                        });
                });

            modelBuilder.Entity("Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "RegisteredUser"
                        },
                        new
                        {
                            Id = 2,
                            Name = "PR"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Administrator"
                        });
                });

            modelBuilder.Entity("Models.RoleScope", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Scope")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleScope");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleId = 1,
                            Scope = "ProjectWrite"
                        },
                        new
                        {
                            Id = 2,
                            RoleId = 1,
                            Scope = "UserWrite"
                        },
                        new
                        {
                            Id = 3,
                            RoleId = 2,
                            Scope = "HighlightWrite"
                        },
                        new
                        {
                            Id = 4,
                            RoleId = 3,
                            Scope = "ProjectWrite"
                        },
                        new
                        {
                            Id = 5,
                            RoleId = 3,
                            Scope = "UserWrite"
                        },
                        new
                        {
                            Id = 6,
                            RoleId = 3,
                            Scope = "UserRead"
                        },
                        new
                        {
                            Id = 7,
                            RoleId = 3,
                            Scope = "RoleRead"
                        },
                        new
                        {
                            Id = 8,
                            RoleId = 3,
                            Scope = "RoleWrite"
                        },
                        new
                        {
                            Id = 9,
                            RoleId = 3,
                            Scope = "HighlightWrite"
                        });
                });

            modelBuilder.Entity("Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Dalton_Rohan94@hotmail.com",
                            IdentityId = "2",
                            Name = "Triston"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Frederick.Schmeler@gmail.com",
                            IdentityId = "3",
                            Name = "Brown"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Serena_Wehner@hotmail.com",
                            IdentityId = "4",
                            Name = "Novella"
                        },
                        new
                        {
                            Id = 4,
                            Email = "Horacio.Dickinson@hotmail.com",
                            IdentityId = "5",
                            Name = "Roman"
                        },
                        new
                        {
                            Id = 5,
                            Email = "Tod_Wehner@yahoo.com",
                            IdentityId = "6",
                            Name = "Aric"
                        },
                        new
                        {
                            Id = 6,
                            Email = "Donna_Kozey1@gmail.com",
                            IdentityId = "7",
                            Name = "Chesley"
                        },
                        new
                        {
                            Id = 7,
                            Email = "Rafaela_Johnson@gmail.com",
                            IdentityId = "8",
                            Name = "Carmel"
                        },
                        new
                        {
                            Id = 8,
                            Email = "Monserrate.Homenick29@hotmail.com",
                            IdentityId = "9",
                            Name = "Christina"
                        },
                        new
                        {
                            Id = 9,
                            Email = "Verdie_Mraz@gmail.com",
                            IdentityId = "10",
                            Name = "Gayle"
                        },
                        new
                        {
                            Id = 10,
                            Email = "Patricia20@gmail.com",
                            IdentityId = "11",
                            Name = "Salvatore"
                        },
                        new
                        {
                            Id = 11,
                            Email = "Lexie29@yahoo.com",
                            IdentityId = "12",
                            Name = "Justina"
                        },
                        new
                        {
                            Id = 12,
                            Email = "Thora.Kutch38@hotmail.com",
                            IdentityId = "13",
                            Name = "Tia"
                        },
                        new
                        {
                            Id = 13,
                            Email = "Chad.Rempel@yahoo.com",
                            IdentityId = "14",
                            Name = "Patrick"
                        },
                        new
                        {
                            Id = 14,
                            Email = "Cleo.Howell65@yahoo.com",
                            IdentityId = "15",
                            Name = "Colleen"
                        },
                        new
                        {
                            Id = 15,
                            Email = "Alison_Reynolds@gmail.com",
                            IdentityId = "16",
                            Name = "Violet"
                        },
                        new
                        {
                            Id = 16,
                            Email = "Beryl_Bruen@gmail.com",
                            IdentityId = "17",
                            Name = "Parker"
                        },
                        new
                        {
                            Id = 17,
                            Email = "Prudence_Hermiston@gmail.com",
                            IdentityId = "18",
                            Name = "Levi"
                        },
                        new
                        {
                            Id = 18,
                            Email = "Davonte69@hotmail.com",
                            IdentityId = "19",
                            Name = "Kirstin"
                        },
                        new
                        {
                            Id = 19,
                            Email = "Vidal.Schuppe@yahoo.com",
                            IdentityId = "20",
                            Name = "Katlynn"
                        },
                        new
                        {
                            Id = 20,
                            Email = "Sunny86@hotmail.com",
                            IdentityId = "21",
                            Name = "Cristal"
                        },
                        new
                        {
                            Id = 21,
                            Email = "Brent16@gmail.com",
                            IdentityId = "22",
                            Name = "Tracy"
                        },
                        new
                        {
                            Id = 22,
                            Email = "Lempi.Cruickshank39@yahoo.com",
                            IdentityId = "23",
                            Name = "Mariane"
                        },
                        new
                        {
                            Id = 23,
                            Email = "Johnathan.Hansen@hotmail.com",
                            IdentityId = "24",
                            Name = "Demarcus"
                        },
                        new
                        {
                            Id = 24,
                            Email = "Fatima_Davis96@hotmail.com",
                            IdentityId = "25",
                            Name = "Delilah"
                        },
                        new
                        {
                            Id = 25,
                            Email = "Stephan.Stehr@hotmail.com",
                            IdentityId = "26",
                            Name = "Lexus"
                        },
                        new
                        {
                            Id = 26,
                            Email = "Helga_Daugherty67@hotmail.com",
                            IdentityId = "27",
                            Name = "Nikko"
                        },
                        new
                        {
                            Id = 27,
                            Email = "Sylvia_Bogan@gmail.com",
                            IdentityId = "28",
                            Name = "Antonia"
                        },
                        new
                        {
                            Id = 28,
                            Email = "Fabian.Langosh55@yahoo.com",
                            IdentityId = "29",
                            Name = "Providenci"
                        },
                        new
                        {
                            Id = 29,
                            Email = "Ashtyn20@gmail.com",
                            IdentityId = "30",
                            Name = "Amani"
                        },
                        new
                        {
                            Id = 30,
                            Email = "Katheryn_Tromp@gmail.com",
                            IdentityId = "31",
                            Name = "Nya"
                        },
                        new
                        {
                            Id = 31,
                            Email = "a@b.c",
                            IdentityId = "1",
                            Name = "Regular User",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 32,
                            Email = "a@b.c",
                            IdentityId = "2",
                            Name = "PR User",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 33,
                            Email = "a@b.c",
                            IdentityId = "3",
                            Name = "Administrator",
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("Models.Collaborator", b =>
                {
                    b.HasOne("Models.Project", null)
                        .WithMany("Collaborators")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.Highlight", b =>
                {
                    b.HasOne("Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.Project", b =>
                {
                    b.HasOne("Models.User", "User")
                        .WithMany("Projects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.RoleScope", b =>
                {
                    b.HasOne("Models.Role", null)
                        .WithMany("Scopes")
                        .HasForeignKey("RoleId");
                });

            modelBuilder.Entity("Models.User", b =>
                {
                    b.HasOne("Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");
                });
#pragma warning restore 612, 618
        }
    }
}
