// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace _4_Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200415133909_AddHighLights")]
    partial class AddHighLights
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.Collaborator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Collaborators");

                    b.HasData(
                        new
                        {
                            Id = 2746,
                            FullName = "Eduardo Macejkovic",
                            ProjectId = 1,
                            Role = "Senior Usability Administrator"
                        },
                        new
                        {
                            Id = 6512,
                            FullName = "Hailey Pacocha",
                            ProjectId = 1,
                            Role = "Regional Assurance Consultant"
                        },
                        new
                        {
                            Id = 8672,
                            FullName = "Ebony Simonis",
                            ProjectId = 2,
                            Role = "Future Division Consultant"
                        },
                        new
                        {
                            Id = 8412,
                            FullName = "Keyshawn Johns",
                            ProjectId = 2,
                            Role = "Investor Accounts Producer"
                        },
                        new
                        {
                            Id = 7539,
                            FullName = "Rhea Rath",
                            ProjectId = 3,
                            Role = "Forward Identity Manager"
                        },
                        new
                        {
                            Id = 334,
                            FullName = "Rachelle Mayert",
                            ProjectId = 3,
                            Role = "Chief Data Developer"
                        },
                        new
                        {
                            Id = 9685,
                            FullName = "Alberta Fay",
                            ProjectId = 4,
                            Role = "Regional Metrics Developer"
                        },
                        new
                        {
                            Id = 7869,
                            FullName = "Reyna Donnelly",
                            ProjectId = 4,
                            Role = "Direct Marketing Assistant"
                        },
                        new
                        {
                            Id = 3375,
                            FullName = "Brad Doyle",
                            ProjectId = 5,
                            Role = "Dynamic Program Agent"
                        },
                        new
                        {
                            Id = 6970,
                            FullName = "Magnolia Leffler",
                            ProjectId = 5,
                            Role = "Forward Paradigm Liaison"
                        },
                        new
                        {
                            Id = 7104,
                            FullName = "Rodrick Barton",
                            ProjectId = 6,
                            Role = "Central Identity Representative"
                        },
                        new
                        {
                            Id = 2177,
                            FullName = "Vernie Kreiger",
                            ProjectId = 6,
                            Role = "Direct Paradigm Administrator"
                        },
                        new
                        {
                            Id = 5308,
                            FullName = "Issac Marvin",
                            ProjectId = 7,
                            Role = "International Creative Representative"
                        },
                        new
                        {
                            Id = 5559,
                            FullName = "Magdalen Parker",
                            ProjectId = 7,
                            Role = "Human Applications Engineer"
                        },
                        new
                        {
                            Id = 80,
                            FullName = "Rosario Ryan",
                            ProjectId = 8,
                            Role = "Dynamic Implementation Liaison"
                        },
                        new
                        {
                            Id = 1857,
                            FullName = "Carson Reichert",
                            ProjectId = 8,
                            Role = "Senior Quality Liaison"
                        },
                        new
                        {
                            Id = 6533,
                            FullName = "Erica Kohler",
                            ProjectId = 9,
                            Role = "Product Accountability Officer"
                        },
                        new
                        {
                            Id = 3281,
                            FullName = "Daisha Senger",
                            ProjectId = 9,
                            Role = "Forward Branding Planner"
                        },
                        new
                        {
                            Id = 3327,
                            FullName = "Walker Skiles",
                            ProjectId = 10,
                            Role = "Customer Functionality Technician"
                        },
                        new
                        {
                            Id = 4578,
                            FullName = "Queenie Hettinger",
                            ProjectId = 10,
                            Role = "Forward Division Analyst"
                        },
                        new
                        {
                            Id = 1445,
                            FullName = "Karolann Rodriguez",
                            ProjectId = 11,
                            Role = "National Factors Liaison"
                        },
                        new
                        {
                            Id = 6921,
                            FullName = "Ignacio Russel",
                            ProjectId = 11,
                            Role = "District Brand Analyst"
                        },
                        new
                        {
                            Id = 4709,
                            FullName = "Dudley Sawayn",
                            ProjectId = 12,
                            Role = "Central Intranet Engineer"
                        },
                        new
                        {
                            Id = 4266,
                            FullName = "Cyrus Dickens",
                            ProjectId = 12,
                            Role = "Dynamic Tactics Engineer"
                        },
                        new
                        {
                            Id = 3130,
                            FullName = "Laurianne Veum",
                            ProjectId = 13,
                            Role = "Senior Web Facilitator"
                        },
                        new
                        {
                            Id = 7959,
                            FullName = "Samson Swaniawski",
                            ProjectId = 13,
                            Role = "Chief Research Director"
                        },
                        new
                        {
                            Id = 4416,
                            FullName = "Zoila Grant",
                            ProjectId = 14,
                            Role = "International Security Manager"
                        },
                        new
                        {
                            Id = 8096,
                            FullName = "Ted Treutel",
                            ProjectId = 14,
                            Role = "National Research Strategist"
                        },
                        new
                        {
                            Id = 8585,
                            FullName = "Vincenza Fahey",
                            ProjectId = 15,
                            Role = "Direct Identity Manager"
                        },
                        new
                        {
                            Id = 3277,
                            FullName = "Uriah Durgan",
                            ProjectId = 15,
                            Role = "Global Solutions Director"
                        },
                        new
                        {
                            Id = 2245,
                            FullName = "Leopold Schowalter",
                            ProjectId = 16,
                            Role = "Human Communications Manager"
                        },
                        new
                        {
                            Id = 6290,
                            FullName = "Judah Considine",
                            ProjectId = 16,
                            Role = "District Program Planner"
                        },
                        new
                        {
                            Id = 9691,
                            FullName = "Nannie Cartwright",
                            ProjectId = 17,
                            Role = "Principal Markets Administrator"
                        },
                        new
                        {
                            Id = 3441,
                            FullName = "Will Kreiger",
                            ProjectId = 17,
                            Role = "Chief Integration Technician"
                        },
                        new
                        {
                            Id = 6506,
                            FullName = "Maryam Lakin",
                            ProjectId = 18,
                            Role = "Dynamic Communications Officer"
                        },
                        new
                        {
                            Id = 1224,
                            FullName = "Tressa Wunsch",
                            ProjectId = 18,
                            Role = "Chief Applications Analyst"
                        },
                        new
                        {
                            Id = 4083,
                            FullName = "Taylor Grimes",
                            ProjectId = 19,
                            Role = "International Assurance Planner"
                        },
                        new
                        {
                            Id = 8267,
                            FullName = "Gus Vandervort",
                            ProjectId = 19,
                            Role = "Dynamic Marketing Orchestrator"
                        },
                        new
                        {
                            Id = 1146,
                            FullName = "Filomena Maggio",
                            ProjectId = 20,
                            Role = "Forward Marketing Supervisor"
                        },
                        new
                        {
                            Id = 8611,
                            FullName = "Ebba Hudson",
                            ProjectId = 20,
                            Role = "Corporate Functionality Representative"
                        },
                        new
                        {
                            Id = 6993,
                            FullName = "Zachariah Turner",
                            ProjectId = 21,
                            Role = "Principal Tactics Executive"
                        },
                        new
                        {
                            Id = 5969,
                            FullName = "Aileen Goyette",
                            ProjectId = 21,
                            Role = "Investor Infrastructure Architect"
                        },
                        new
                        {
                            Id = 1276,
                            FullName = "Macy Gorczany",
                            ProjectId = 22,
                            Role = "Human Research Assistant"
                        },
                        new
                        {
                            Id = 7585,
                            FullName = "Abigail Lueilwitz",
                            ProjectId = 22,
                            Role = "Human Operations Engineer"
                        },
                        new
                        {
                            Id = 6219,
                            FullName = "Eudora Sanford",
                            ProjectId = 23,
                            Role = "Chief Security Officer"
                        },
                        new
                        {
                            Id = 963,
                            FullName = "Dominic Osinski",
                            ProjectId = 23,
                            Role = "Regional Metrics Developer"
                        },
                        new
                        {
                            Id = 6919,
                            FullName = "Sammy Blanda",
                            ProjectId = 24,
                            Role = "Forward Program Executive"
                        },
                        new
                        {
                            Id = 3386,
                            FullName = "Jay Schamberger",
                            ProjectId = 24,
                            Role = "Direct Branding Analyst"
                        },
                        new
                        {
                            Id = 7590,
                            FullName = "Willard Cummings",
                            ProjectId = 25,
                            Role = "Customer Markets Manager"
                        },
                        new
                        {
                            Id = 3773,
                            FullName = "Ramona Kovacek",
                            ProjectId = 25,
                            Role = "Dynamic Tactics Strategist"
                        },
                        new
                        {
                            Id = 3385,
                            FullName = "Mabelle Ward",
                            ProjectId = 26,
                            Role = "Direct Operations Specialist"
                        },
                        new
                        {
                            Id = 7987,
                            FullName = "Norberto Olson",
                            ProjectId = 26,
                            Role = "Customer Directives Engineer"
                        },
                        new
                        {
                            Id = 7417,
                            FullName = "Vincenzo Wilkinson",
                            ProjectId = 27,
                            Role = "District Infrastructure Associate"
                        },
                        new
                        {
                            Id = 4749,
                            FullName = "Justen Parisian",
                            ProjectId = 27,
                            Role = "Future Directives Executive"
                        },
                        new
                        {
                            Id = 93,
                            FullName = "Juana Towne",
                            ProjectId = 28,
                            Role = "District Metrics Officer"
                        },
                        new
                        {
                            Id = 2421,
                            FullName = "Amie Legros",
                            ProjectId = 28,
                            Role = "Senior Division Coordinator"
                        },
                        new
                        {
                            Id = 1878,
                            FullName = "Daryl Weissnat",
                            ProjectId = 29,
                            Role = "Central Response Agent"
                        },
                        new
                        {
                            Id = 8461,
                            FullName = "Clementina Schimmel",
                            ProjectId = 29,
                            Role = "Chief Creative Administrator"
                        },
                        new
                        {
                            Id = 2836,
                            FullName = "Trudie Gibson",
                            ProjectId = 30,
                            Role = "District Directives Assistant"
                        },
                        new
                        {
                            Id = 3136,
                            FullName = "Annette Koepp",
                            ProjectId = 30,
                            Role = "Internal Security Supervisor"
                        });
                });

            modelBuilder.Entity("Models.Highlight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsHighlighted")
                        .HasColumnType("bit");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Highlight");
                });

            modelBuilder.Entity("Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Project");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2020, 4, 13, 15, 39, 8, 751, DateTimeKind.Local).AddTicks(9377),
                            Description = @"Sint qui voluptate ea optio.
Sit dolorem et.
Asperiores voluptatem vero est in.
Nihil eos iusto ducimus ducimus sed voluptatem.
Ratione dolore ea hic quaerat atque molestiae quia est.
Doloremque hic similique.
Quia praesentium at ipsam.
Voluptas suscipit sint et quia vero assumenda rerum.
Itaque tenetur et eum et.
Aliquam ducimus quisquam vel similique eum eos.",
                            Name = "Sleek Cotton Shirt",
                            ShortDescription = "Velit fugiat maxime fuga a non sit aut.",
                            Updated = new DateTime(2020, 4, 15, 15, 39, 8, 756, DateTimeKind.Local).AddTicks(350),
                            Uri = "http://eldridge.name",
                            UserId = 11
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2020, 4, 13, 15, 39, 8, 759, DateTimeKind.Local).AddTicks(9373),
                            Description = @"Ut sunt quos.
Dicta eum expedita sed facilis occaecati asperiores.
Tempore quod voluptatum placeat nostrum ut nam molestias voluptate vel.
Consequatur ex quia delectus.
Assumenda occaecati ipsa architecto doloremque.
Atque nostrum architecto repellendus est quis.
Porro aspernatur odit sapiente laborum nisi incidunt sed eum.
Atque fugiat porro mollitia vero vero soluta.
Voluptas quam ullam ut.
Voluptatum et necessitatibus incidunt.",
                            Name = "Fantastic Granite Bike",
                            ShortDescription = "Sit tempore quas magni vel.",
                            Updated = new DateTime(2020, 4, 15, 15, 39, 8, 759, DateTimeKind.Local).AddTicks(9432),
                            Uri = "https://bret.org",
                            UserId = 7
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2020, 4, 13, 15, 39, 8, 763, DateTimeKind.Local).AddTicks(4646),
                            Description = @"Minus labore iure rerum iste labore enim nulla et et.
Perspiciatis consequatur et qui consequatur ut.
Ipsa quisquam aut aut recusandae quo quasi ex.
Sapiente et sunt minus fugiat dolores.
Est inventore sapiente sit sint nobis in eum harum.
Minima a consequuntur sint corporis quia enim quos aut.
Et possimus corporis.
Officiis sed repellendus aliquid itaque illo cumque natus.
Eius quia qui.
Repellendus quo ex ratione qui nisi.",
                            Name = "Rustic Fresh Fish",
                            ShortDescription = "Iusto aut tempora itaque.",
                            Updated = new DateTime(2020, 4, 15, 15, 39, 8, 763, DateTimeKind.Local).AddTicks(4690),
                            Uri = "https://mason.biz",
                            UserId = 25
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2020, 4, 13, 15, 39, 8, 767, DateTimeKind.Local).AddTicks(248),
                            Description = @"Non possimus nostrum enim porro eveniet tempora dignissimos in illo.
Repudiandae voluptates laboriosam voluptates et cupiditate dolor ducimus.
Eos esse quia labore omnis reiciendis pariatur est ex autem.
Provident in ullam dolore quidem fugit.
Repellat praesentium sint veniam voluptas consequuntur.
Velit ipsam animi facere distinctio id praesentium in.
Dolor sint harum illo unde id ab.
Dicta repellendus deserunt sit suscipit laborum explicabo.
Consequatur quae dolor doloribus a.
Est asperiores occaecati error distinctio dolore itaque optio illo.",
                            Name = "Gorgeous Steel Shoes",
                            ShortDescription = "Tenetur voluptatibus sint.",
                            Updated = new DateTime(2020, 4, 15, 15, 39, 8, 767, DateTimeKind.Local).AddTicks(292),
                            Uri = "https://kristina.biz",
                            UserId = 17
                        },
                        new
                        {
                            Id = 5,
                            Created = new DateTime(2020, 4, 13, 15, 39, 8, 770, DateTimeKind.Local).AddTicks(5839),
                            Description = @"Velit reiciendis sed sed eos nihil.
Atque pariatur est cum officia quidem molestiae.
Quidem provident maiores beatae et mollitia reprehenderit qui deserunt.
Ex explicabo ea voluptatem.
Sed cupiditate qui in expedita tempore praesentium voluptatibus.
Tenetur quod blanditiis nulla consequatur quia consequatur ut.
Accusamus consequatur non rerum dolor id repellendus.
Magnam earum nemo quas est ratione eius aut sunt.
Alias inventore enim adipisci.
Unde veniam consequuntur inventore.",
                            Name = "Unbranded Concrete Shirt",
                            ShortDescription = "Perspiciatis commodi ut eos.",
                            Updated = new DateTime(2020, 4, 15, 15, 39, 8, 770, DateTimeKind.Local).AddTicks(5892),
                            Uri = "https://abraham.com",
                            UserId = 7
                        },
                        new
                        {
                            Id = 6,
                            Created = new DateTime(2020, 4, 13, 15, 39, 8, 774, DateTimeKind.Local).AddTicks(1274),
                            Description = @"Reiciendis autem pariatur nihil sint.
Adipisci nisi mollitia labore quod quibusdam quia consequatur.
Voluptatem cum amet reiciendis nam.
Perspiciatis facilis quaerat.
Tempore ducimus dolores odit et voluptatem aut in aut voluptatem.
Quam est distinctio officiis dicta.
Praesentium ut et similique explicabo dolores quisquam amet illum.
Dolore molestias nostrum iusto voluptatem officia sed nulla.
Cumque labore rerum sint.
Qui consequatur nisi voluptatem eveniet et non odit in.",
                            Name = "Unbranded Concrete Mouse",
                            ShortDescription = "Vitae quod praesentium voluptatem culpa.",
                            Updated = new DateTime(2020, 4, 15, 15, 39, 8, 774, DateTimeKind.Local).AddTicks(1318),
                            Uri = "http://jocelyn.info",
                            UserId = 19
                        },
                        new
                        {
                            Id = 7,
                            Created = new DateTime(2020, 4, 13, 15, 39, 8, 777, DateTimeKind.Local).AddTicks(6532),
                            Description = @"Sint officia fugit eum ut illum rerum iure ut sint.
Itaque quia qui voluptatem optio quis repudiandae sit eos non.
Aliquid velit magni.
Voluptatem minima molestiae quia.
Nemo tempora et.
Facere voluptates quasi libero impedit laudantium amet minus similique.
Occaecati ratione at et beatae harum sint et dolores.
Et ut nihil optio sit iste commodi laudantium eius in.
Quo tempore debitis qui temporibus eius dolore rem.
Maxime veniam repellendus expedita laborum architecto velit voluptatum.",
                            Name = "Refined Rubber Tuna",
                            ShortDescription = "Eligendi velit debitis minus ut ut occaecati quia quis.",
                            Updated = new DateTime(2020, 4, 15, 15, 39, 8, 777, DateTimeKind.Local).AddTicks(6576),
                            Uri = "https://ona.org",
                            UserId = 12
                        },
                        new
                        {
                            Id = 8,
                            Created = new DateTime(2020, 4, 13, 15, 39, 8, 781, DateTimeKind.Local).AddTicks(2030),
                            Description = @"Aut rem aut.
Quis velit libero a illum eius.
Qui quae dicta rerum.
Rerum laborum non sed.
Reiciendis dolores provident debitis qui nulla mollitia voluptatem culpa.
Assumenda et qui.
Animi iusto quasi natus minima non sint sint voluptatem.
Et nesciunt veniam nihil.
Non aut maiores.
Enim eum laboriosam dignissimos non nihil similique architecto rerum labore.",
                            Name = "Handmade Granite Mouse",
                            ShortDescription = "Ducimus quo laudantium minima.",
                            Updated = new DateTime(2020, 4, 15, 15, 39, 8, 781, DateTimeKind.Local).AddTicks(2074),
                            Uri = "https://carey.com",
                            UserId = 16
                        },
                        new
                        {
                            Id = 9,
                            Created = new DateTime(2020, 4, 13, 15, 39, 8, 784, DateTimeKind.Local).AddTicks(7284),
                            Description = @"Veritatis vel ea vel molestiae natus saepe nemo consequatur voluptates.
Est ipsam reiciendis quaerat doloribus perspiciatis vero quo blanditiis.
Cum sed soluta tempora eligendi.
Ea ullam qui.
Minus nostrum eum.
Cupiditate ipsa quo minima consequatur sit sit accusamus nostrum.
Consectetur voluptatem corporis dicta quisquam enim velit ut.
Est eum eligendi quisquam.
Minus natus provident consequatur aut at illo.
Non numquam id rerum eum.",
                            Name = "Small Concrete Chicken",
                            ShortDescription = "Impedit enim hic consequatur eum sit eaque.",
                            Updated = new DateTime(2020, 4, 15, 15, 39, 8, 784, DateTimeKind.Local).AddTicks(7328),
                            Uri = "http://melvina.net",
                            UserId = 1
                        },
                        new
                        {
                            Id = 10,
                            Created = new DateTime(2020, 4, 13, 15, 39, 8, 788, DateTimeKind.Local).AddTicks(2758),
                            Description = @"Quasi omnis vel eum.
Magni unde ducimus est quia.
Odio est eum eius sunt aliquid est odio et fugiat.
Expedita in et nihil unde amet vero quaerat molestiae pariatur.
Vero quis sequi fugiat et fuga cumque aperiam voluptatem fuga.
Repudiandae reprehenderit voluptate quia quia est et consequatur.
Et commodi quia sed aut delectus et culpa.
Officia iure eveniet quae ducimus.
Perspiciatis et aliquam dignissimos voluptatem quod qui similique quia.
Distinctio voluptatum exercitationem.",
                            Name = "Awesome Wooden Pizza",
                            ShortDescription = "Et dolore laboriosam dolorum dolorem.",
                            Updated = new DateTime(2020, 4, 15, 15, 39, 8, 788, DateTimeKind.Local).AddTicks(2802),
                            Uri = "https://maxine.biz",
                            UserId = 26
                        },
                        new
                        {
                            Id = 11,
                            Created = new DateTime(2020, 4, 13, 15, 39, 8, 791, DateTimeKind.Local).AddTicks(9160),
                            Description = @"Sed tempore tempore.
Qui et rerum expedita.
Quaerat aliquid deleniti distinctio earum expedita autem quibusdam.
Qui quos voluptatem.
Dolores laboriosam ab minima.
Eligendi quaerat autem doloremque tempora molestias qui dolorum repudiandae eveniet.
Ullam quibusdam non.
Cum id saepe vero a modi aspernatur cumque.
Rerum rerum ducimus nobis debitis.
Suscipit consectetur qui voluptatibus.",
                            Name = "Small Steel Sausages",
                            ShortDescription = "Qui quis tempora consequuntur.",
                            Updated = new DateTime(2020, 4, 15, 15, 39, 8, 791, DateTimeKind.Local).AddTicks(9204),
                            Uri = "https://jeremy.com",
                            UserId = 24
                        },
                        new
                        {
                            Id = 12,
                            Created = new DateTime(2020, 4, 13, 15, 39, 8, 795, DateTimeKind.Local).AddTicks(4679),
                            Description = @"Nisi sapiente soluta error necessitatibus dignissimos consectetur voluptatem expedita.
Iste aut vitae laboriosam inventore blanditiis quod.
Natus saepe pariatur vel minima et iure autem.
Rerum odio et ex aut et nesciunt perspiciatis atque.
Ipsam nostrum necessitatibus.
Dolores voluptas et.
Minima qui repellendus repudiandae veritatis in aut suscipit qui.
Provident soluta iusto quia excepturi tempore corporis debitis facere et.
Ex et quibusdam sunt ducimus molestiae dignissimos tempore saepe.
Corrupti et ea aut incidunt maiores aut vel.",
                            Name = "Handmade Fresh Fish",
                            ShortDescription = "Nisi totam eum eius aut.",
                            Updated = new DateTime(2020, 4, 15, 15, 39, 8, 795, DateTimeKind.Local).AddTicks(4718),
                            Uri = "https://joseph.biz",
                            UserId = 9
                        },
                        new
                        {
                            Id = 13,
                            Created = new DateTime(2020, 4, 13, 15, 39, 8, 799, DateTimeKind.Local).AddTicks(235),
                            Description = @"In voluptate dicta et modi.
Laboriosam laborum voluptatem error nam non tempora quae ab doloremque.
Minima nobis voluptas.
Nihil eveniet veniam non nihil temporibus.
Debitis veniam libero blanditiis adipisci blanditiis voluptates modi voluptatem.
Aut alias harum voluptas.
Dolor aut eveniet asperiores.
Facere ut beatae dolores provident quis omnis sequi molestias et.
Occaecati velit sunt minus accusamus eveniet.
Id est dolores eum.",
                            Name = "Licensed Concrete Chicken",
                            ShortDescription = "Debitis enim nobis eligendi qui et sed voluptatum.",
                            Updated = new DateTime(2020, 4, 15, 15, 39, 8, 799, DateTimeKind.Local).AddTicks(279),
                            Uri = "https://khalid.com",
                            UserId = 2
                        },
                        new
                        {
                            Id = 14,
                            Created = new DateTime(2020, 4, 13, 15, 39, 8, 802, DateTimeKind.Local).AddTicks(7102),
                            Description = @"Molestiae qui eligendi possimus.
Sint temporibus quos aut veritatis doloremque enim rerum.
Neque modi fugiat et eum sed tempora.
Cum doloremque voluptates reprehenderit voluptas assumenda consequatur autem omnis.
Nam est veniam repudiandae beatae vel.
Adipisci dicta omnis.
Harum optio recusandae ut debitis totam corrupti doloribus explicabo molestias.
Rerum beatae ratione distinctio nulla quia consectetur voluptatem nobis molestiae.
Harum facilis nesciunt ipsam dolore qui blanditiis.
Quidem sed ducimus delectus quae sit reiciendis sequi ducimus.",
                            Name = "Small Plastic Mouse",
                            ShortDescription = "Quia iure praesentium saepe libero.",
                            Updated = new DateTime(2020, 4, 15, 15, 39, 8, 802, DateTimeKind.Local).AddTicks(7146),
                            Uri = "https://melody.net",
                            UserId = 8
                        },
                        new
                        {
                            Id = 15,
                            Created = new DateTime(2020, 4, 13, 15, 39, 8, 806, DateTimeKind.Local).AddTicks(2884),
                            Description = @"Veritatis explicabo qui.
Et quis architecto.
Modi nisi provident quis accusamus aut dolores.
Aut voluptas accusamus.
Maxime quisquam ea eaque.
Quod reiciendis vel.
Voluptatum est et.
Harum illo ex.
Molestiae ut est vitae aut beatae reiciendis.
Ipsum voluptatem repellendus veniam sunt libero sunt nam fuga.",
                            Name = "Practical Granite Bacon",
                            ShortDescription = "Nisi minus velit quasi quia.",
                            Updated = new DateTime(2020, 4, 15, 15, 39, 8, 806, DateTimeKind.Local).AddTicks(2933),
                            Uri = "https://connor.net",
                            UserId = 27
                        },
                        new
                        {
                            Id = 16,
                            Created = new DateTime(2020, 4, 13, 15, 39, 8, 809, DateTimeKind.Local).AddTicks(8636),
                            Description = @"Labore eum eos id quia.
Dolor dicta eos.
Eum amet debitis quisquam consectetur aspernatur voluptatem aut.
Quaerat iure quis impedit fuga aspernatur at rerum.
Iure molestiae sit ea et eveniet.
Tenetur qui corrupti quos doloremque atque ut in optio.
Tempora consectetur animi sed mollitia.
Itaque maiores aliquid rerum et sed.
Quas quia fugit et cumque et enim.
Earum voluptatibus itaque.",
                            Name = "Handmade Rubber Soap",
                            ShortDescription = "Tenetur provident ipsam id.",
                            Updated = new DateTime(2020, 4, 15, 15, 39, 8, 809, DateTimeKind.Local).AddTicks(8685),
                            Uri = "http://maude.info",
                            UserId = 7
                        },
                        new
                        {
                            Id = 17,
                            Created = new DateTime(2020, 4, 13, 15, 39, 8, 813, DateTimeKind.Local).AddTicks(5352),
                            Description = @"Ut quaerat temporibus repellat reprehenderit quis necessitatibus aut.
Quo et voluptatibus ipsum sint nobis quo delectus iure quia.
Non distinctio aut rerum ut.
Vel in eaque necessitatibus odit labore harum.
Assumenda perspiciatis repudiandae iusto sint et illo ut.
In voluptas unde.
Est sunt aut aut.
Tenetur officia ducimus nobis autem ratione aspernatur assumenda.
Enim aut accusantium qui reprehenderit aliquid molestias voluptatem eos molestiae.
Totam libero incidunt et quidem atque ipsam.",
                            Name = "Small Plastic Pizza",
                            ShortDescription = "Deleniti eligendi atque accusantium aut.",
                            Updated = new DateTime(2020, 4, 15, 15, 39, 8, 813, DateTimeKind.Local).AddTicks(5396),
                            Uri = "https://rosetta.org",
                            UserId = 5
                        },
                        new
                        {
                            Id = 18,
                            Created = new DateTime(2020, 4, 13, 15, 39, 8, 817, DateTimeKind.Local).AddTicks(3236),
                            Description = @"Laboriosam voluptatem distinctio quod asperiores repellat tempore recusandae velit.
Sed tenetur dicta voluptatum nesciunt veniam ex sed.
Necessitatibus fugiat maxime.
Ullam dolorem rerum qui dolore.
Nemo exercitationem et.
Nesciunt adipisci ipsam consequatur quos dolore rerum consequatur vel voluptatem.
Sequi provident earum ea quia repellat est aut eaque.
Recusandae deserunt eos commodi repudiandae.
Vero nihil dolorem.
Nisi rem maiores molestiae veniam voluptas ad et a voluptate.",
                            Name = "Intelligent Steel Mouse",
                            ShortDescription = "Qui mollitia ducimus.",
                            Updated = new DateTime(2020, 4, 15, 15, 39, 8, 817, DateTimeKind.Local).AddTicks(3280),
                            Uri = "http://ebony.com",
                            UserId = 12
                        },
                        new
                        {
                            Id = 19,
                            Created = new DateTime(2020, 4, 13, 15, 39, 8, 821, DateTimeKind.Local).AddTicks(856),
                            Description = @"Quis doloremque est tempora animi blanditiis facilis.
Velit dolor iure omnis quaerat et nobis.
Perferendis sed deleniti quisquam dolorem illo et.
Atque repellat esse modi.
Ipsa quia dolores porro ad inventore dignissimos.
Cumque nobis iure harum veniam.
Et eligendi eveniet suscipit rerum praesentium placeat doloribus et.
Iure temporibus ut in corrupti quod.
Eaque nihil sapiente nesciunt expedita necessitatibus quo.
Odio et dolore ipsam iusto explicabo sunt ut exercitationem alias.",
                            Name = "Handmade Frozen Computer",
                            ShortDescription = "Officia distinctio totam voluptas accusamus illo molestias.",
                            Updated = new DateTime(2020, 4, 15, 15, 39, 8, 821, DateTimeKind.Local).AddTicks(919),
                            Uri = "http://eleazar.com",
                            UserId = 2
                        },
                        new
                        {
                            Id = 20,
                            Created = new DateTime(2020, 4, 13, 15, 39, 8, 824, DateTimeKind.Local).AddTicks(6882),
                            Description = @"Beatae ut non quia mollitia ut et veritatis aliquid molestias.
Quas cum dolor ut.
Dolore itaque qui reiciendis sequi.
Similique distinctio explicabo aut voluptatem quo quas dolores et velit.
Ex ea placeat debitis eius optio.
Impedit cupiditate enim.
Unde commodi vel voluptas nihil aperiam labore necessitatibus facilis quo.
Eos omnis omnis incidunt dolores illum sapiente iste vero.
Perferendis quasi voluptatem qui animi quam doloremque labore commodi enim.
Harum est aut qui est dolorem dolores totam.",
                            Name = "Refined Steel Bacon",
                            ShortDescription = "Qui iste mollitia omnis modi.",
                            Updated = new DateTime(2020, 4, 15, 15, 39, 8, 824, DateTimeKind.Local).AddTicks(6926),
                            Uri = "http://esta.info",
                            UserId = 17
                        },
                        new
                        {
                            Id = 21,
                            Created = new DateTime(2020, 4, 13, 15, 39, 8, 828, DateTimeKind.Local).AddTicks(3388),
                            Description = @"Qui architecto provident nostrum inventore molestias aut laborum non et.
Error quia quas ipsum dignissimos.
Assumenda doloribus eum dicta id neque praesentium.
Voluptas animi harum explicabo ipsa aperiam.
Non distinctio dolor sed.
Iusto libero voluptatem aperiam at quae beatae.
Doloremque vel porro quibusdam aut.
Iusto tempora repudiandae aut pariatur repudiandae.
Illum exercitationem voluptates.
Sint dolorem et eos eaque excepturi.",
                            Name = "Intelligent Concrete Fish",
                            ShortDescription = "Quidem eos et aspernatur tempore.",
                            Updated = new DateTime(2020, 4, 15, 15, 39, 8, 828, DateTimeKind.Local).AddTicks(3432),
                            Uri = "https://enrique.org",
                            UserId = 14
                        },
                        new
                        {
                            Id = 22,
                            Created = new DateTime(2020, 4, 13, 15, 39, 8, 832, DateTimeKind.Local).AddTicks(4020),
                            Description = @"Aut fugiat numquam natus mollitia sint.
Dolor voluptas dolorum molestias dolorum autem voluptate.
Laboriosam aut praesentium eos asperiores et iure.
Sit quam laboriosam omnis.
Est exercitationem eum.
Quis et accusantium harum corporis id voluptatem eius nihil minus.
Perferendis ex dignissimos est voluptatem incidunt saepe cum fuga ab.
Occaecati dolores tempore adipisci eos quaerat.
Dolores magni aperiam autem dolorum.
Totam eum non aperiam.",
                            Name = "Ergonomic Concrete Table",
                            ShortDescription = "Odio sint sunt magni reprehenderit.",
                            Updated = new DateTime(2020, 4, 15, 15, 39, 8, 832, DateTimeKind.Local).AddTicks(4068),
                            Uri = "https://daron.name",
                            UserId = 21
                        },
                        new
                        {
                            Id = 23,
                            Created = new DateTime(2020, 4, 13, 15, 39, 8, 836, DateTimeKind.Local).AddTicks(3873),
                            Description = @"Et quia quo et iure provident sapiente aut totam.
At molestiae animi sapiente modi id adipisci quaerat aut.
Eos ea amet magni debitis.
Aut cupiditate provident neque facilis beatae.
Vel quam officia dolor voluptas vitae at.
Molestiae consequatur tempore et facilis non molestiae molestiae molestiae dolor.
Voluptate qui necessitatibus non voluptatem.
Quae repellat molestiae iusto in corporis sed omnis.
Modi perspiciatis harum a accusamus.
Accusantium suscipit itaque mollitia.",
                            Name = "Generic Plastic Salad",
                            ShortDescription = "Et ut vero cum animi est eum.",
                            Updated = new DateTime(2020, 4, 15, 15, 39, 8, 836, DateTimeKind.Local).AddTicks(3917),
                            Uri = "http://major.org",
                            UserId = 22
                        },
                        new
                        {
                            Id = 24,
                            Created = new DateTime(2020, 4, 13, 15, 39, 8, 840, DateTimeKind.Local).AddTicks(3605),
                            Description = @"Minima vitae molestiae.
Aliquid molestias iste nostrum voluptas nemo rerum.
Delectus repudiandae dolor vel dolore.
Et molestias rerum vel eos facere quo delectus sint eum.
Quis minus suscipit.
Aut officia explicabo.
Et officia sunt a omnis et omnis.
Nemo rerum rem aut nostrum dolor sed officia inventore.
Totam earum cum eligendi eum officia.
Amet ipsa sunt unde tempora dicta quia vitae.",
                            Name = "Sleek Concrete Towels",
                            ShortDescription = "Ducimus consequatur non omnis et et officia sapiente provident.",
                            Updated = new DateTime(2020, 4, 15, 15, 39, 8, 840, DateTimeKind.Local).AddTicks(3654),
                            Uri = "http://marco.com",
                            UserId = 8
                        },
                        new
                        {
                            Id = 25,
                            Created = new DateTime(2020, 4, 13, 15, 39, 8, 844, DateTimeKind.Local).AddTicks(2110),
                            Description = @"Aut qui quia voluptatem et odit sed quas.
Deserunt et voluptatibus et.
Iste voluptatem accusantium.
Sit dolorem veritatis quas similique natus ex.
Neque inventore eos consequatur quis sed quis et.
Quidem sed recusandae eos.
Neque accusantium quia ad ipsa.
Porro qui assumenda ullam est nemo quia.
Nobis quas aut.
Quibusdam quia rerum ratione commodi modi eius.",
                            Name = "Licensed Granite Mouse",
                            ShortDescription = "Est odio eos et hic.",
                            Updated = new DateTime(2020, 4, 15, 15, 39, 8, 844, DateTimeKind.Local).AddTicks(2154),
                            Uri = "http://isaias.net",
                            UserId = 12
                        },
                        new
                        {
                            Id = 26,
                            Created = new DateTime(2020, 4, 13, 15, 39, 8, 848, DateTimeKind.Local).AddTicks(1520),
                            Description = @"Occaecati placeat repellat impedit quis.
Ipsam veritatis commodi laboriosam sed porro facere rerum dolores.
Reprehenderit perferendis distinctio aspernatur illo quo repellat ad.
Pariatur aliquid mollitia nam dolor accusantium est.
Deserunt eaque ab non labore.
Cupiditate et nesciunt delectus enim quia qui ipsum nemo.
Asperiores id doloribus autem dicta labore aut placeat quisquam fugit.
Corrupti quisquam in sit enim totam.
Neque animi dicta dignissimos voluptatem sequi.
Consectetur saepe placeat qui.",
                            Name = "Small Steel Mouse",
                            ShortDescription = "Ducimus cum quae quidem libero in eaque enim ut aliquid.",
                            Updated = new DateTime(2020, 4, 15, 15, 39, 8, 848, DateTimeKind.Local).AddTicks(1559),
                            Uri = "http://luna.org",
                            UserId = 5
                        },
                        new
                        {
                            Id = 27,
                            Created = new DateTime(2020, 4, 13, 15, 39, 8, 852, DateTimeKind.Local).AddTicks(1046),
                            Description = @"Omnis dolor a at.
Aut nihil officiis unde qui quo labore saepe.
Inventore voluptatem assumenda nam omnis.
Dicta qui est enim velit neque.
Consequatur temporibus a voluptatem minus explicabo consequatur magni delectus.
Aspernatur nihil libero nisi omnis quia quia sed aperiam.
Aut quia minima porro laudantium.
Animi aspernatur aperiam quia nobis expedita culpa velit.
Dicta deserunt molestiae aut qui.
Non sunt magnam tempore sapiente explicabo aspernatur quia id atque.",
                            Name = "Rustic Cotton Chair",
                            ShortDescription = "Dolorem dolorem et.",
                            Updated = new DateTime(2020, 4, 15, 15, 39, 8, 852, DateTimeKind.Local).AddTicks(1085),
                            Uri = "http://eliezer.info",
                            UserId = 16
                        },
                        new
                        {
                            Id = 28,
                            Created = new DateTime(2020, 4, 13, 15, 39, 8, 856, DateTimeKind.Local).AddTicks(1199),
                            Description = @"Aspernatur temporibus dicta odio quia totam consequatur cum non optio.
Necessitatibus blanditiis quibusdam.
Accusantium ipsa quas.
Et omnis molestiae eligendi et quos possimus.
Qui in aliquid et doloremque facilis.
Fugit corporis dolorem ut voluptas fuga sunt facilis architecto temporibus.
Ad consequatur consequatur aut atque velit inventore excepturi repellat dolores.
Aspernatur rem rerum commodi quasi et aut dolor.
Quasi et deleniti soluta dolor eos consequatur nam itaque.
Magni aliquid et rerum numquam reprehenderit.",
                            Name = "Awesome Steel Shoes",
                            ShortDescription = "Aperiam sunt voluptatem consequatur sint est.",
                            Updated = new DateTime(2020, 4, 15, 15, 39, 8, 856, DateTimeKind.Local).AddTicks(1253),
                            Uri = "http://john.biz",
                            UserId = 7
                        },
                        new
                        {
                            Id = 29,
                            Created = new DateTime(2020, 4, 13, 15, 39, 8, 860, DateTimeKind.Local).AddTicks(1948),
                            Description = @"Tempora ut eveniet a ut aperiam necessitatibus.
Voluptas dolorum reprehenderit qui sunt.
Alias ipsam consectetur eum minus aut tempore.
Aut accusantium voluptatem omnis mollitia quidem incidunt in dolorem.
Amet vel dolor deserunt blanditiis rerum quod.
Quas quasi nihil rem.
Velit rerum inventore voluptas magni perferendis accusamus iste quas.
Qui non accusamus itaque aliquid odio magnam explicabo facere blanditiis.
Non consectetur velit velit eos dolore sunt omnis rem.
Consequuntur ut ut est est sed quibusdam.",
                            Name = "Handcrafted Plastic Shoes",
                            ShortDescription = "Error exercitationem delectus.",
                            Updated = new DateTime(2020, 4, 15, 15, 39, 8, 860, DateTimeKind.Local).AddTicks(1992),
                            Uri = "https://isai.biz",
                            UserId = 8
                        },
                        new
                        {
                            Id = 30,
                            Created = new DateTime(2020, 4, 13, 15, 39, 8, 864, DateTimeKind.Local).AddTicks(1792),
                            Description = @"Quod magnam aut tenetur perferendis necessitatibus.
Facere est et enim.
Dolor consequatur doloremque minima enim maiores animi sit maxime.
Qui asperiores consectetur nesciunt et cupiditate optio fuga ut ad.
Cumque consequatur eius harum.
Non vel ea at.
Consequatur eum quibusdam sint a et eius excepturi architecto maiores.
Facilis voluptas quibusdam reiciendis voluptas at voluptatibus cum.
Voluptatem vitae repellat.
Beatae velit vel est aspernatur praesentium modi.",
                            Name = "Ergonomic Rubber Chair",
                            ShortDescription = "Necessitatibus perferendis dicta dolorem reprehenderit rerum hic officiis deleniti fugit.",
                            Updated = new DateTime(2020, 4, 15, 15, 39, 8, 864, DateTimeKind.Local).AddTicks(1831),
                            Uri = "https://jerrell.net",
                            UserId = 4
                        });
                });

            modelBuilder.Entity("Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Mervin_Stoltenberg@gmail.com",
                            IdentityId = "2",
                            Name = "Fletcher"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Florida.Flatley@yahoo.com",
                            IdentityId = "3",
                            Name = "Seth"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Willow87@hotmail.com",
                            IdentityId = "4",
                            Name = "Princess"
                        },
                        new
                        {
                            Id = 4,
                            Email = "Chandler_Keebler75@gmail.com",
                            IdentityId = "5",
                            Name = "Hilma"
                        },
                        new
                        {
                            Id = 5,
                            Email = "Vincent64@yahoo.com",
                            IdentityId = "6",
                            Name = "Reynold"
                        },
                        new
                        {
                            Id = 6,
                            Email = "Henri_Kuhic@yahoo.com",
                            IdentityId = "7",
                            Name = "Branson"
                        },
                        new
                        {
                            Id = 7,
                            Email = "Felix.Maggio12@gmail.com",
                            IdentityId = "8",
                            Name = "Magdalena"
                        },
                        new
                        {
                            Id = 8,
                            Email = "Travon.Cummerata96@hotmail.com",
                            IdentityId = "9",
                            Name = "Yadira"
                        },
                        new
                        {
                            Id = 9,
                            Email = "Arvid.Hickle95@hotmail.com",
                            IdentityId = "10",
                            Name = "Gracie"
                        },
                        new
                        {
                            Id = 10,
                            Email = "Caleigh17@yahoo.com",
                            IdentityId = "11",
                            Name = "Bert"
                        },
                        new
                        {
                            Id = 11,
                            Email = "Libbie_Hoeger@gmail.com",
                            IdentityId = "12",
                            Name = "Larry"
                        },
                        new
                        {
                            Id = 12,
                            Email = "Korey.Blick@yahoo.com",
                            IdentityId = "13",
                            Name = "Emilio"
                        },
                        new
                        {
                            Id = 13,
                            Email = "Novella.Bechtelar98@hotmail.com",
                            IdentityId = "14",
                            Name = "Friedrich"
                        },
                        new
                        {
                            Id = 14,
                            Email = "Deon.Dooley@gmail.com",
                            IdentityId = "15",
                            Name = "Rosalyn"
                        },
                        new
                        {
                            Id = 15,
                            Email = "Octavia.Lowe64@gmail.com",
                            IdentityId = "16",
                            Name = "Kayley"
                        },
                        new
                        {
                            Id = 16,
                            Email = "Junior55@hotmail.com",
                            IdentityId = "17",
                            Name = "Montana"
                        },
                        new
                        {
                            Id = 17,
                            Email = "Amber_Heller53@yahoo.com",
                            IdentityId = "18",
                            Name = "Malika"
                        },
                        new
                        {
                            Id = 18,
                            Email = "Ignacio68@yahoo.com",
                            IdentityId = "19",
                            Name = "Bessie"
                        },
                        new
                        {
                            Id = 19,
                            Email = "Fausto.West@hotmail.com",
                            IdentityId = "20",
                            Name = "Santino"
                        },
                        new
                        {
                            Id = 20,
                            Email = "Tyrel.Hand@gmail.com",
                            IdentityId = "21",
                            Name = "Alysha"
                        },
                        new
                        {
                            Id = 21,
                            Email = "Stephanie.Ledner@hotmail.com",
                            IdentityId = "22",
                            Name = "Ryder"
                        },
                        new
                        {
                            Id = 22,
                            Email = "Estrella_Morar@hotmail.com",
                            IdentityId = "23",
                            Name = "Albina"
                        },
                        new
                        {
                            Id = 23,
                            Email = "Faye_Barton78@yahoo.com",
                            IdentityId = "24",
                            Name = "Scarlett"
                        },
                        new
                        {
                            Id = 24,
                            Email = "Aliza.Harvey94@yahoo.com",
                            IdentityId = "25",
                            Name = "King"
                        },
                        new
                        {
                            Id = 25,
                            Email = "Alexandro.Feil50@hotmail.com",
                            IdentityId = "26",
                            Name = "Clara"
                        },
                        new
                        {
                            Id = 26,
                            Email = "Wendy.Nicolas@hotmail.com",
                            IdentityId = "27",
                            Name = "Easton"
                        },
                        new
                        {
                            Id = 27,
                            Email = "Asa38@gmail.com",
                            IdentityId = "28",
                            Name = "Collin"
                        },
                        new
                        {
                            Id = 28,
                            Email = "Stone37@gmail.com",
                            IdentityId = "29",
                            Name = "Kaya"
                        },
                        new
                        {
                            Id = 29,
                            Email = "Weldon_Mayert18@yahoo.com",
                            IdentityId = "30",
                            Name = "Una"
                        },
                        new
                        {
                            Id = 30,
                            Email = "Amani.Harris89@yahoo.com",
                            IdentityId = "31",
                            Name = "Bryce"
                        });
                });

            modelBuilder.Entity("Models.Collaborator", b =>
                {
                    b.HasOne("Models.Project", null)
                        .WithMany("Collaborators")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.Highlight", b =>
                {
                    b.HasOne("Models.Project", "Project")
                        .WithMany("HighlightedProjects")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.Project", b =>
                {
                    b.HasOne("Models.User", "User")
                        .WithMany("Projects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
