// <auto-generated />
<<<<<<< HEAD:Digital_Excellence/Data/Migrations/ApplicationDbContextModelSnapshot.cs
using System;
=======

>>>>>>> develop:Data/Migrations/ApplicationDbContextModelSnapshot.cs
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace _4_Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.Project", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy",
                        SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("Description")
                    .HasColumnType("nvarchar(max)");

<<<<<<< HEAD:Digital_Excellence/Data/Migrations/ApplicationDbContextModelSnapshot.cs
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uri")
                        .HasColumnType("nvarchar(max)");
=======
                b.Property<string>("Title")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Url")
                    .HasColumnType("nvarchar(max)");
>>>>>>> develop:Data/Migrations/ApplicationDbContextModelSnapshot.cs

                b.Property<int>("UserId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("UserId");

                b.ToTable("Project");
            });

            modelBuilder.Entity("Models.ProjectMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectMember");
                });

            modelBuilder.Entity("Models.User", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy",
                        SqlServerValueGenerationStrategy.IdentityColumn);

<<<<<<< HEAD:Digital_Excellence/Data/Migrations/ApplicationDbContextModelSnapshot.cs
                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileUrl")
                        .HasColumnType("nvarchar(max)");
=======
                b.Property<string>("ProfileUrl")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Username")
                    .HasColumnType("nvarchar(max)");
>>>>>>> develop:Data/Migrations/ApplicationDbContextModelSnapshot.cs

                b.HasKey("Id");

                b.ToTable("User");
            });

            modelBuilder.Entity("Models.Project", b =>
<<<<<<< HEAD:Digital_Excellence/Data/Migrations/ApplicationDbContextModelSnapshot.cs
                {
                    b.HasOne("Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.ProjectMember", b =>
                {
                    b.HasOne("Models.Project", null)
                        .WithMany("Contributors")
                        .HasForeignKey("ProjectId");
                });
=======
            {
                b.HasOne("Models.User", "User")
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });
>>>>>>> develop:Data/Migrations/ApplicationDbContextModelSnapshot.cs
#pragma warning restore 612, 618
        }
    }
}