FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build-env

ENV DOTNET_CLI_TELEMETRY_OPTOUT 1

ENV ConnectionStrings__DefaultConnection = ''

ARG BuildConfiguration=Debug

WORKDIR /app

COPY . ./

RUN dotnet dev-certs https --clean
RUN dotnet dev-certs https -ep ./dex-api.pfx -p xI90DrNea7M6UJFNDwip6t

RUN dotnet build

FROM mcr.microsoft.com/dotnet/aspnet:3.1

WORKDIR /app

COPY --from=build-env /app/API/bin/Debug/netcoreapp3.1 .
COPY --from=build-env /app/API/Uploads/Images ./Uploads/Images
COPY --from=build-env /app/dex-api.pfx .

ENTRYPOINT ["dotnet", "01_API.dll", "--environment=Development"]
