name: Codecov
on:
  push:
    branches: [ feature/unittest-pipeline ]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Tools
      run: dotnet tool install --global dotnet-reportgenerator-globaltool

    - name: Build
      run: dotnet build

    - name: Test
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=OpenCover /p:Exclude=\"[*]*Microsoft.NET.Test.*,[*]*Data.*,[*]*Models.*,[*]*Repositories.Tests.*,[*]*Services.Sources.Resources.*\"

    - name: Report
      run: ~/.dotnet/tools/reportgenerator "-reports:*Tests/coverage.opencover.xml" "-targetdir:coverage-reports" -reporttypes:Cobertura

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage-reports/Cobertura.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
