
name: Execute Performance tests

on:
  push:
    branches: [ develop, release/* ]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Navigate to performance test directory.
        run: cd PerformanceTests
      - name: Run docker compose up
        run:  docker-compose -f docker-compose.load-tests.yml up
