name: Run Backend Unit & Integration Tests

on:
  pull_request:
    branches: [ develop, master ]

jobs:
  Unit-Tests:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal --filter FullyQualifiedName!~API.Tests
      env:
        App__SendGrid__ApiKey: ${{secrets.STAGING_SENDGRID_APIKEY }}
        App__SendGrid__EmailFrom: test@dex.software


  XUnit-Postman-Integration-Tests:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2


    - name: Docker compose up
      run: docker-compose up --build -d


    - name: Sleep for 50 seconds
      uses: juliangruber/sleep-action@v1
      with:
        time: 50s
        
    - name: Run XUnit container
      run: |
        cd ./api.tests
        docker build .
        
    - name: Run XUnit container
      run: docker run -e "ApiAddress=https://api:5001/" -e "IdentityAddress=http://identity:5004/" --network  dex-backend_mssql-network dex-backend_xunit
    

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '10.15.3'

    - name: Postman tests
      run:  npm install -g newman && newman run Postman/dex.postman_collection.json -e Postman/local.postman_environment.json --insecure --reporter-cli-no-console --reporter-cli-no-success-assertions -n 3

    - name: Recommendation tests
      run: npm install -g newman && newman run Postman/ElasticSearch/DeX_Elastic.postman_collection.json -e Postman/ElasticSearch/DeX_Elastic.postman_environment.json --insecure --reporter-cli-no-console --reporter-cli-no-success-assertions -n 3
