name: Run Backend Unit & Integration Tests

on:
  pull_request:
    branches: [ develop, master ]

jobs:
  unit-test:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Docker Compose Build
      run: docker-compose build -d
      
    - name: Create Docker Containers
      run: docker-compose up --no-start
      
    - name: Run RabbitMQ Container
      run: docker-compose start rabbitmq
      
    - name: Run API
      run: |
        cd API
        dotnet run -d

    - name: Run Identity Server
      run: |
        cd IdentityServer
        dotnet run -d
      
    - name: Test
      run: dotnet test --environment 'test' --no-restore --verbosity normal
      env:
        App__SendGrid__ApiKey: ${{secrets.STAGING_SENDGRID_APIKEY }}
        App__SendGrid__EmailFrom: test@dex.software

  integration-test:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Docker Compose
      run: docker-compose up --build -d

    - name: Sleep for 90 seconds
      uses: juliangruber/sleep-action@v1
      with:
        time: 90s

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '10.15.3'

    - name: Postman tests
      run:  npm install -g newman && newman run Postman/dex.postman_collection.json -e Postman/local.postman_environment.json --insecure --reporter-cli-no-console --reporter-cli-no-success-assertions -n 3

    - name: Recommendation tests
      run: npm install -g newman && newman run Postman/ElasticSearch/DeX_Elastic.postman_collection.json -e Postman/ElasticSearch/DeX_Elastic.postman_environment.json --insecure --reporter-cli-no-console --reporter-cli-no-success-assertions -n 3
